Change recurring sort to grab first instance of date of event listing pages
department-of-veterans-affairs/content-build pull request #1011
Opened 2022-03-01 21:32 UTC by ethanteague

## Description
When event listings have events with multiple recurrences, we want the soonest one to appear.

## Testing done
Visual

## Screenshots
Yes:
![image](https://user-images.githubusercontent.com/2404547/156252001-5f51c8aa-ad92-4e4d-9894-417a733e035f.png)

No:
![image](https://user-images.githubusercontent.com/2404547/156252144-f401a93a-5cf6-4161-b893-381b25e80b24.png)

## Acceptance criteria
- [ ] Recurring events created for Pittsburgh in https://pr7981-5kfpv6vznchkcxw4bgycflzjjodfbtbe.ci.cms.va.gov/ environment show soonest occurrence on listing page https://pr7981-5kfpv6vznchkcxw4bgycflzjjodfbtbe.ci.cms.va.gov/pittsburgh-health-care

2022-03-01 21:59 UTC, GcioNapoleon approved these changes

2022-03-01 23:03 UTC, swirtSJW commented on src/site/filters/liquid.js
> +      return dates[0];
This seems like a more dramatic change to this filter and makes the comment one line up a bit of a lie.   If there are no future dates, doesn't this grab the very first date in the the series  (essentially grabbing the oldest expired) rather than the most recent expired?

2022-03-01 23:05 UTC, swirtSJW commented on src/site/filters/liquid.js
> +      return dates[0];
This does not seem to be covering case in the issue where it need to grab the next upcoming.  For future dates.  This line is for if there are no future dates.

2022-03-04 01:17 UTC, ethanteague commented on src/site/filters/liquid.js
> +      return dates[0];
Think I got it now, @swirtSJW

2022-03-07 14:54 UTC, kevwalsh requested changes
Not sure if the [Tugboat environment](https://web-5kfpv6vznchkcxw4bgycflzjjodfbtbe.ci.cms.va.gov/pittsburgh-health-care/events/) has the latest code, but it seems like we have the opposite issue now. Clicking the representative event in the listing brings me to a page that shows the last event in the series. 

<img width="1249" alt="Events___VA_Pittsburgh_Health_Care___Veterans_Affairs_and_VA_Pittsburgh_Health_Care___Recurring_Monthly___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/157057617-33c9e418-23c7-4114-b55a-3f216575dee1.png">

2022-03-07 15:05 UTC, swirtSJW commented on src/site/filters/liquid.js
> +  liquid.filters.deriveMostRecentDateOnEventsListingPage = fieldDatetimeRangeTimezone => {
I'm not clear on why we need two different filters to do the same thing.  The data should be the same in either case.  What's different about the use cases?

2022-03-07 17:34 UTC, ethanteague commented on src/site/filters/liquid.js
> +  liquid.filters.deriveMostRecentDateOnEventsListingPage = fieldDatetimeRangeTimezone => {
I just couldn't make the other filter work for our use case on listing pages after messing with it for days. Gave up and tried a new filter without all of the conditionals, and was able to make it fire, @swirtSJW

2022-03-07 20:09 UTC, ethanteague commented on src/site/filters/liquid.js
> +  liquid.filters.deriveMostRecentDateOnEventsListingPage = fieldDatetimeRangeTimezone => {
Alright. Think I got it, @swirtSJW

2022-03-07 21:23 UTC, swirtSJW commented on src/site/filters/liquid.unit.spec.js
> +    ).to.deep.eq({ value: 1642014000, endValue: 1642017600 });
Why did all the tests need new times?

2022-03-07 21:33 UTC, ethanteague commented on src/site/filters/liquid.unit.spec.js
> +    ).to.deep.eq({ value: 1642014000, endValue: 1642017600 });
The tests were predicated on the last occurrence in a recurring series being the item presented.

2022-03-07 21:40 UTC, swirtSJW commented on src/site/filters/liquid.js
> +    ).reverse();
This reverse is unexpected (counter intuitive).   Reversing the order seems odd.  Why do we want the dates array built from most distant to closest?

2022-03-07 21:46 UTC, ethanteague commented on src/site/filters/liquid.js
> +    ).reverse();
lodash _sortBy only allows for descending order (but it's a really quick / easy / one method way to sort an array) - seems quicker to do it this way then reverse it than with a typical three step array sort approach.

2022-03-08 00:24 UTC, swirtSJW commented on src/site/filters/liquid.js
> +    ).reverse();
That doesn't seem right.   
![image](https://user-images.githubusercontent.com/5752113/157140124-6f759acc-1bc7-43b8-98c3-e2f60312858c.png)
It is ascending by the value of a function return.  "endValue"  is neither a function return or a value. 

https://lodash.com/docs/4.17.15#sortBy

2022-03-08 01:02 UTC, ethanteague commented on src/site/filters/liquid.js
> +    ).reverse();
Sorry - misspoke when I said descending (guess it's ascending). Not sure I'm following what you are after, though. Are you saying I should just be using a compare type of function?

2022-03-08 14:46 UTC, swirtSJW commented on src/site/filters/liquid.js
> +    ).reverse();
Yes sortBy seems to need a comparing function, not just an array key.   I think you either need the comparing function or you need to use orderBy

2022-03-08 20:00 UTC, swirtSJW commented on src/site/filters/liquid.js
> +      const mostRecentEvent = liquid.filters.deriveMostRecentEventDate(
I'm a bit concerned about creating a second filter that works and leaving an old one behind that does not work.    Is there a reason we can't  re-use the same name of the filter?

2022-03-08 20:07 UTC, swirtSJW commented on src/site/filters/liquid.js
> +    return [];
If there are no future dates, this returns an empty array.   Kelson's version of this had a fallback to grab the last past date in that event.   Don't we still need that fallback?

2022-03-08 20:09 UTC, ethanteague commented on src/site/filters/liquid.js
> +      const mostRecentEvent = liquid.filters.deriveMostRecentEventDate(
Yeah, I feel that, @swirtSJW . I'm kinda nervous about doing that, because this filter is also used for clp, past events and situation updates. I just don't know what else might get broken.

2022-03-08 20:09 UTC, ethanteague commented on src/site/filters/liquid.js
> +    return [];
I tested all of the places events show up, and doesn't appear that we do - looks like past events have unique handling, @swirtSJW .

2022-03-09 13:16 UTC, ethanteague commented
Closing in favor of https://github.com/department-of-veterans-affairs/content-build/pull/1025

2022-03-09 13:16 UTC, closed without merging