VAVFA-9061: Display verbiage for hours on caps lists.
department-of-veterans-affairs/content-build pull request #1151
Opened 2022-05-27 19:12 UTC by ethanteague

## Description
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9061

## Testing done
Visual / build

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/170775439-cbaee781-6225-4e34-a3dc-07af906d729a.png)

## Acceptance criteria
- [ ] on local version of `content-build` running yarn preview with prod as endpoint, go to `preview?nodeId=28246` and visually verify cap location listings show `Veterans should call main Vet Center for hours ` verbiage below phone numbers

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-05-27 19:15 UTC, ndouglas commented on src/site/includes/vet_centers/address_phone_image.liquid
> +      {% elsif vetCenter.entityBundle == "vet_center_cap" and vetCenterUseCapHours == false %}
Seems redundant with above addition.

2022-05-27 19:16 UTC, ndouglas commented on src/site/includes/vet_centers/address_phone_image.liquid
> +      {% elsif vetCenter.entityBundle == "vet_center_cap" and vetCenterUseCapHours == true or vetCenter.entityBundle == "vet_center" or vetCenter.entityBundle == "vet_center_outstation" %}
What's the operator precedence here? 🤔

2022-05-27 19:19 UTC, ndouglas commented on src/site/includes/vet_centers/address_phone_image.liquid
> +      {% elsif vetCenter.entityBundle == "vet_center_cap" and vetCenterUseCapHours == false %}
The `vetCenterUseCapHours == false` specifically.

2022-05-27 19:46 UTC, maxx1128 commented on src/site/includes/vet_centers/address_phone_image.liquid
> +      {% elsif vetCenter.entityBundle == "vet_center_cap" and vetCenterUseCapHours == true or vetCenter.entityBundle == "vet_center" or vetCenter.entityBundle == "vet_center_outstation" %}
I'm not too clear on this either. Do liquid files allow parenthesis in their conditionals to make these more explicit?

2022-05-27 20:11 UTC, maxx1128 requested changes

2022-05-27 20:23 UTC, ethanteague commented on src/site/includes/vet_centers/address_phone_image.liquid
> +      {% elsif vetCenter.entityBundle == "vet_center_cap" and vetCenterUseCapHours == true or vetCenter.entityBundle == "vet_center" or vetCenter.entityBundle == "vet_center_outstation" %}
Parenthesis are a no-go in liquid, and operators are read right to left. That said, this is confusing, so I broke this out into an additional elsif.

2022-05-27 21:43 UTC, ndouglas approved these changes

2022-05-31 14:36 UTC, maxx1128 approved these changes

2022-05-31 20:49 UTC, merged