added closed to empty hour fields
department-of-veterans-affairs/content-build pull request #1176
Opened 2022-06-15 15:03 UTC by jtmst

## Description
Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9390
Added logic to add 'Closed' to field office hours where there are no hours or comment

## Testing done
Visual testing on local env

## Screenshots
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/61624970/173859006-fc6e3dee-2740-4d43-a85c-c88c4d5152e5.png">

<img width="1125" alt="Screen Shot 2022-06-15 at 10 57 12 AM" src="https://user-images.githubusercontent.com/61624970/173859403-6511745a-1e6e-42b8-a985-aefa7f882207.png">

## Acceptance criteria
- [ ] Visually confirm that facility hours are shown properly, and that 'Closed' is appearing instead of any blank hour fields example: (butler-health-care/billing-and-insurance)

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-06-15 19:17 UTC, kind-claudio requested changes

2022-06-15 19:17 UTC, kind-claudio commented on src/site/includes/hours-item.liquid
> +    {{ hours.comment }}
could lines 7 - 15 be moved into an `{% else %}` block down below, at line 19? This way we don't run the other conditional blocks if we don't need to.

2022-06-15 19:17 UTC, kind-claudio commented on src/site/includes/hours.liquid
> +                                Closed
You could remove "Closed" from these two conditional blocks, and instead place it only once at the end of the `<li />` block, after line 38, since it be displayed/rendered regardless of the conditional results.

2022-06-15 19:17 UTC, kind-claudio commented on src/site/includes/hours.liquid
> +                                Closed
Same comment as the one above:
 You could remove "Closed" from these two conditional blocks, and instead place it only once at the end of the <li /> block, but after line 51, since it be displayed/rendered regardless of the conditional results.

2022-06-16 19:43 UTC, maxx1128 commented on src/site/includes/hours-item.liquid
> +    {{ hours.comment }}
☝️ I second this

2022-06-16 21:38 UTC, jtmst commented on src/site/includes/hours.liquid
> +                                Closed
Good call, fixed those

2022-06-16 21:38 UTC, jtmst commented on src/site/includes/hours-item.liquid
> +    {{ hours.comment }}
Good idea,  just commited that change

2022-06-21 14:59 UTC, kind-claudio approved these changes

2022-06-30 16:22 UTC, maxx1128 requested changes
Looks good, one small question then I should be ready to approve.

2022-06-30 16:22 UTC, maxx1128 commented on src/site/includes/hours.liquid
> +							Closed
Should this "Closed" text be in another conditional like the one in the other file, that checks if there are no hours or comments?

2022-06-30 17:26 UTC, jtmst commented on src/site/includes/hours.liquid
> +							Closed
That check happens in the above if block, this Closed text will only render if Saturday / Sunday hours arent listed

2022-06-30 17:50 UTC, wullaski requested changes

2022-06-30 18:06 UTC, maxx1128 approved these changes

2022-06-30 18:16 UTC, jtmst commented on src/site/includes/hours-item.liquid
> +	{% if !hours.starthours && !hours.endhours && !hours.comment %}
The most common use of the comment block is editors writing in "closed" and i believe their is drupal logic that formats that.  This would result in "closed" being rendered twice.  The desired logic in the original issue is to only make this assumption if there is no comment.

2022-06-30 18:52 UTC, wullaski approved these changes

2022-06-30 19:04 UTC, merged