VAVSA-9549: Remove faulty conditional.
department-of-veterans-affairs/content-build pull request #1181
Opened 2022-06-21 20:06 UTC by ethanteague

## Description
Unnecessary fallback on facility pages shows an event that is not featured in featured event section
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9549

## Testing done
Visual

## Screenshots
Should not appear
![image](https://user-images.githubusercontent.com/2404547/174888076-3fa1c044-058b-48aa-844c-69306fd2b1b0.png)

## Acceptance criteria
 - [ ] Go to https://www.va.gov/minneapolis-health-care/ and visually verify featured events section no longer appears (no featured events, so expected outcome is for this section to go away)

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-06-21 20:37 UTC, JayDarnell commented on src/site/layouts/health_care_region_page.drupal.liquid
> +
Does this section also need to be removed from src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid?

2022-06-21 21:06 UTC, ethanteague commented on src/site/layouts/health_care_region_page.drupal.liquid
> +
Good catch, @JayDarnell . Removed :+1:

2022-06-22 15:24 UTC, maxx1128 requested changes

2022-06-22 15:32 UTC, ethanteague commented on src/site/layouts/liquid_template_axe_check_smoke_test.drupal.liquid
>            {% elsif eventTeasersAll.entities.0.reverseFieldListingNode.entities.length %}
My bad yall. Removed.

2022-06-23 15:20 UTC, kevwalsh commented
Don't merge this until we've had a chance to discuss more (see comments in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9549)

2022-07-06 12:43 UTC, maxx1128 approved these changes

2022-07-06 22:27 UTC, jilladams commented
Closing, determined this was not the right fix: https://dsva.slack.com/archives/CT4GZBM8F/p1656014625552849?thread_ts=1655835746.501589&cid=CT4GZBM8F

2022-07-06 22:27 UTC, closed without merging