Vet center content fixes
department-of-veterans-affairs/content-build pull request #125
Opened 2021-05-10 22:30 UTC by brangi

2021-05-11 14:14 UTC, brangi commented on src/site/layouts/vet_center.drupal.liquid
> +                                   <div class="other-locations">
ye

2021-05-11 14:19 UTC, brangi commented on src/site/layouts/vet_center.drupal.liquid
> +                                   <div class="other-locations">
actually, I am going add some more unit tests on this PR shortly

2021-05-12 17:20 UTC, mpelzsherman commented on src/site/layouts/vet_center.drupal.liquid
> +                                   <div class="other-locations">
It would be better to use an `id` for testing rather than a class. We should use the design system classes whenever possible and only add new custom classes when absolutely necessary.

2021-05-12 17:20 UTC, mpelzsherman requested changes
Please use an `id` for other locations div rather than a class, unless a custom class is definitely needed.

2021-05-12 18:52 UTC, mpelzsherman approved these changes

2021-05-12 19:13 UTC, merged