Increase build timeout from 30m to 45m
department-of-veterans-affairs/content-build pull request #1254
Opened 2022-08-11 21:55 UTC by ElijahLynn

Jobs are timing out and failing.

## Description
e.g. second failure from a timeout here > https://github.com/department-of-veterans-affairs/content-build/runs/7795882449?check_suite_focus=true

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-08-11 21:56 UTC, ElijahLynn commented
I'm still looking into if there is one thing that is taking abnormally long.

2022-08-11 22:01 UTC, ElijahLynn commented
On the timeout build, GQL seems normal. So maybe it is the file downloads?

> https://prod.cms.va.gov/ response time: : 2:55.254 (m:ss.mmm)
> Total time to load content from GraphQL: 2:57.619 (m:ss.mmm)
> Drupal successfully loaded!

2022-08-11 22:07 UTC, alexandec approved these changes

2022-08-11 22:35 UTC, cweagans commented
Looks like the file downloads are the culprit to me.

https://github.com/department-of-veterans-affairs/content-build/runs/7795404712?check_suite_focus=true says it took 99465ms (succeeded).

https://github.com/department-of-veterans-affairs/content-build/runs/7794734477?check_suite_focus=true was 729281ms (failed).

2022-08-11 22:35 UTC, cweagans requested changes
The CMS considers the state stale if it hasn't gotten a status update in more than 40 minutes. 45 minutes is going to cause issues here. It would be better to let it fail + then the CMS will retry.

2022-08-11 23:03 UTC, ElijahLynn commented
> Looks like the file downloads are the culprit to me.

Thanks, I couldn't see the end time in the one I was looking at but that one you linked to did finish that step and shows the end time. So, I just verified on the PROD EFS volume that the files are stored on that we aren't reaching any throughput limits:

![image](https://user-images.githubusercontent.com/1504756/184256624-f3ae2ea5-51f1-4cb0-b8f1-d22eecac0473.png)
https://console.amazonaws-us-gov.com/efs/home?region=us-gov-west-1#/file-systems/fs-1c9ba71d?tabId=monitoring

2022-08-11 23:04 UTC, ElijahLynn commented
> The CMS considers the state stale if it hasn't gotten a status update in more than 40 minutes. 45 minutes is going to cause issues here. It would be better to let it fail + then the CMS will retry as a result of the error (as of today).

Good to know! I think we should close this for now then. I had just posted this in Slack too, so I'm on the same page:

> Thanks, maybe we keep the PR open for a bit to see if it flickers again. I am thinking maybe it was just an issue with runner resource utilization or a network path thing.

2022-08-15 17:23 UTC, timcosgrove commented
FWIW I don't think we should do this, except as a possible stopgap measure. If the build is consistently over 30 minutes, that is a problem that should be addressed directly.

2022-08-15 19:33 UTC, closed without merging