9755 add qa to support detail page
department-of-veterans-affairs/content-build pull request #1256
Opened 2022-08-12 13:34 UTC by jtmst

## Description
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9901

Adds Q&A component to the support_resources_detail_page template
## Testing done

## Screenshots

## Acceptance criteria
- [ ] Q&As render on on support resource detail page type pages when data is provided

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-08-24 14:25 UTC, maxx1128 approved these changes

2022-08-24 16:42 UTC, allisonlu approved these changes

2022-08-24 16:46 UTC, ryguyk requested changes

2022-08-25 15:46 UTC, jtmst commented on src/site/stages/build/drupal/graphql/paragraph-fragments/qaGroup.paragraph.graphql.js
> +                  value
fixed

2022-08-25 15:46 UTC, jtmst commented on src/site/paragraphs/q_a_group.drupal.liquid
> +        {% assign bundleComponent = "src/site/paragraphs/" | append: "rich_text_char_limit_1000" | append: ".drupal.liquid" %}
good call, fixed

2022-08-25 15:59 UTC, ryguyk approved these changes

2022-08-25 17:05 UTC, timwright12 commented on src/site/layouts/support_resources_detail_page.drupal.liquid
> +                <button type="button" class="vads-u-visibility--screen-reader">Back to top</button>
```suggestion
                <button type="button" class="vads-u-visibility--screen-reader" type="button">Back to top</button>
```

2022-08-25 17:05 UTC, timwright12 commented on src/site/layouts/support_resources_detail_page.drupal.liquid
> +              <button type="button" class="vads-u-visibility--screen-reader">Back to top</button>
```suggestion
              <button type="button" class="vads-u-visibility--screen-reader" type="button">Back to top</button>
```

2022-08-25 17:06 UTC, timwright12 commented on src/site/layouts/support_resources_detail_page.drupal.liquid
> +              <button type="button" class="vads-u-visibility--screen-reader">Back to top</button>
Can we use the back to top component here https://design.va.gov/components/back-to-top

2022-08-25 17:26 UTC, ndouglas commented on src/site/layouts/support_resources_detail_page.drupal.liquid
> +                <button type="button" class="vads-u-visibility--screen-reader">Back to top</button>
Why the second `type="button"`?

2022-08-25 17:30 UTC, jtmst commented on src/site/layouts/support_resources_detail_page.drupal.liquid
> +              <button type="button" class="vads-u-visibility--screen-reader">Back to top</button>
fixed

2022-08-25 17:32 UTC, timwright12 approved these changes

2022-08-25 19:40 UTC, merged