10166 fe lovell menu bifurcation
department-of-veterans-affairs/content-build pull request #1274
Opened 2022-08-22 21:11 UTC by wullaski

## Description
Bifurcates menus for Lovell pages.

## Testing done

Visual

## Screenshots
![Screen Shot 2022-08-22 at 5 09 08 PM](https://user-images.githubusercontent.com/2982977/186019569-772b5f8f-9ae3-4813-a8be-0e425628a19f.png)

![Screen Shot 2022-08-22 at 5 08 48 PM](https://user-images.githubusercontent.com/2982977/186019587-5f1230b7-f73e-4a07-87fe-e5fc7a00cd6f.png)

## Acceptance criteria
- [ ] Menu is created for Tricare
- [ ] Menu is modified for VA
- [ ] Menu links are modified to match new urls

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-08-25 15:26 UTC, maxx1128 requested changes
I have a couple suggestions for refactoring, but otherwise this looks good to me 👍

2022-08-25 15:26 UTC, maxx1128 commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +      const lovellClonePages = drupalData.data.nodeQuery.entities.filter(
**Refactor:** this variable is only used for `appendDrupalDataWithLovellTricarePages`, so it can be moved to that function and it'll only need to take `drupalData` as an argument.

2022-08-25 16:48 UTC, maxx1128 approved these changes
🎉

2022-08-25 17:41 UTC, allisonlu approved these changes

2022-08-25 19:46 UTC, ryguyk reviewed
I left a couple comments about some small clean up.

2022-08-25 19:46 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +  page.fieldAdministration.entity.entityId === '347';
Replace with optional chaining? This would remove the need for the check on line 312.

`page?.fieldAdministration?.entity?.entityId === '347`

2022-08-25 19:46 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +const isLovellClonePage = page =>
It seems a bit out of place to have a function expression here when all other functions are function declarations. I prefer function expressions, personally, but it feels out of place in this file.

2022-08-25 19:54 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +  page.fieldAdministration.entity.entityId === '347';
Is it sufficient to check only this field to determine if the page should be cloned? I don't know the answer, to be clear. I'm just wondering if there might be (now or in the future) pages with this administration-field value that should not be cloned.

2022-08-25 20:17 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +function lovellPageModify(page, variant) {
I don't love that this function modifies one its parameters. In the name of functional programming principles, I'd like to see us all strive for pure functions wherever possible.

In light of how this is being called in the `forEach` below, though, changing this to be more pure would likely require overarching changes to how the page-data array is being modified.

2022-08-25 20:17 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
>    });
This can likely be simplified to `page => lovellPageModify(page, 'tricare')`.

2022-08-25 20:17 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +  });
This commentary relates to the discussion of pure functions and, more generally, functional programming at large. What's happening here can be quite tricky and confusing, and I'd like to strive for changing this.  Here's my take on the confusion:

- `drupalData.data.nodeQuery.entities` is an array of all page data
- `lovellClonePages` is a subset _separate array_ that is a subset of the array above. It's _pointing_ at objects in the array above, though. 
- So, in this `foreach` call, we are actually indirectly modifying `drupalData.data.nodeQuery.entities` and that is not immediately obvious (and likely very ripe for bugs).

2022-08-25 21:28 UTC, swirtSJW reviewed
@wullaski This is looking really good.  
I have a couple concerns  related to our search strings being too small to avoid crossfire and wonder if we should stabilize some of the string re-use with some constants.

2022-08-25 21:28 UTC, swirtSJW commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +    page.title = page.title.replace('Federal', 'Federal VA');
If it works, we might want to consider a more long tail search "Lovell Federal " (note the trailing space) to avoid the risk of "federal" being in the title for some other reason.  I see a bit of risk of something getting caught in the crossfire.

2022-08-25 21:28 UTC, swirtSJW commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +      link.label = link.label.replace('Federal', `Federal ${titleVar}`);
Similar consideration for if a more specific search string would reduce the risk of crossfire.

2022-08-25 21:28 UTC, swirtSJW commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +          variation === 'tricare'
I feel like we are repeating a lot of the same strings.  Should some of these be set up as constants to make it more maintainable?

2022-08-25 21:28 UTC, swirtSJW commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +    'Federal',
crossfire risk?

2022-08-25 21:40 UTC, swirtSJW commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +function lovellPageModify(page, variant) {
I think I am following what you are saying @ryguyk but I want to make sure.  Your objection is to altering the variable "page" by reference as opposed to a pure function that would return a new page and need to be stuck back into the original pagedata?

2022-08-25 21:44 UTC, swirtSJW commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +function lovellPageModify(page, variant) {
nevermind... I just read your other comment down farther. ;)

2022-08-25 21:47 UTC, swirtSJW commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +  });
> but I think that could be made more clear without implicit mutations.

By implicit are you meaning consistent naming, like any thing that is a modifier begin with the verb "modify" or are something more than that?

2022-08-26 02:16 UTC, swirtSJW commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +  });
Sorry I just realize I completely misread that line.    Disregard my last comment.

2022-08-26 02:18 UTC, swirtSJW commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +  page.fieldAdministration.entity.entityId === '347';
No if they have that value specifically, they are must be cloned.

2022-08-26 13:05 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +  });
These two fiddles might help clarify my general point:

1. Not so good: https://jsfiddle.net/rh7nepy8/2/
2. Better solution: https://jsfiddle.net/nkem4vgw/2/

2022-08-26 16:45 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +  });
And here's a fiddle that roughly captures what I see as a more clear/immutable approach: https://jsfiddle.net/wszpa3qo/2/

2022-08-30 17:25 UTC, ryguyk reviewed
Added some commentary. Let's chat if it's helpful.

2022-08-30 17:25 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +        delete drupalData.data.nodeQuery.entities[index];
I'm not sure `delete` is the best option, as this will leave a hole in the existing data. This _might_ be fine, but it feels odd.

2022-08-30 17:25 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +}
I think `filter` _combined_ with `map` would be better here. The current solution will return an array with a _lot_ of `false` values that are unnecessary. All you really want, in the end, is a list of index values that represent the Lovell pages. If it's not a Lovell page, you just don't want to worry about it. We can filter those out.

Beyond this, the manner in which this is being used (`delete data[index]`) doesn't seem to make a lot of sense with a `false` value passed in. It might work, but it's confusing and unnecessary. Please see note around use of the `delete` as well. I'm not sure this is the best solution.

2022-08-30 17:25 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +      delete drupalData.data[lovellMenuKey];
Could all this Lovell-specific work be pulled out into a wrapper function? It feels like this function is pretty cleanly laid out with high-level steps that constitute the work of getting Drupal content. This Lovell code feels like it makes this harder to read.

Ex:
```
      await loadCachedDrupalFiles(buildOptions, files);
      processLovellPages(drupalData);
      pipeDrupalPagesIntoMetalsmith(drupalData, files);
```

2022-08-30 17:25 UTC, ryguyk commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +        delete drupalData.data.nodeQuery.entities[index];
My preference would still be for constructing a new array of pages by building up from scratch and including the processed pages as you process them. This would remove the need for anything like `delete`.

Ex:
```
const {
    lovellFederalPages,
    lovellVaPages,
    lovellTricarePages,
    otherPages,
  } = drupalData.data.nodeQuery.entities.reduce(
    (acc, page) => {
      if (isLovellFederalPage(page)) {
        acc.lovellFederalPages.push(page);
      } else if (isLovellTricarePage(page)) {
        acc.lovellTricarePages.push(page);
      } else if (isLovellVaPage(page)) {
        acc.lovellVaPages.push(page);
      } else {
        acc.otherPages.push(page);
      }

      return acc;
    },
    {
      lovellFederalPages: [],
      lovellTricarePages: [],
      lovellVaPages: [],
      otherPages: [],
    },
  );

  // modify tricare pages
  const modifiedLovellTricarePages = lovellTricarePages.map(page =>
    getModifiedLovellPage(page, 'tricare'),
  );
  // modify va pages
  const modifiedLovellVaPages = lovellVaPages.map(page =>
    getModifiedLovellPage(page, 'va'),
  );
  // Each federal page needs to be duplicated and modified once each for tricare/va
  const lovellFederalPagesClonedTricare = lovellFederalPages.map(page =>
    getModifiedLovellPage(cloneDeep(page), 'tricare'),
  );
  const lovellFederalPagesClonedVa = lovellFederalPages.map(page =>
    getModifiedLovellPage(cloneDeep(page), 'va'),
  );

  drupalData.data.nodeQuery.entities = [
    ...modifiedLovellTricarePages,
    ...modifiedLovellVaPages,
    ...lovellFederalPagesClonedTricare,
    ...lovellFederalPagesClonedVa,
    ...otherPages,
  ];
```

This would require a few additional changes:
1. `getModifiedLovellPage` would be a function just like the existing `lovellPageModify`, but would return a value (the modified page).
2. Page checks for tricare/va would only check for their individual entity id, then a new function `isLovellFederalPage(page)` would check for `entityId = LOVELL_FEDERAL_ENTITY_ID`
```
function isLovellFederalPage(page) {
  return (
    page?.fieldAdministration?.entity?.entityId === LOVELL_FEDERAL_ENTITY_ID
  );
}
function isLovellTricarePage(page) {
  return (
    page?.fieldAdministration?.entity?.entityId === LOVELL_TRICARE_ENTITY_ID
  );
}
function isLovellVaPage(page) {
  return page?.fieldAdministration?.entity?.entityId === LOVELL_VA_ENTITY_ID;
}
```

2022-08-30 20:32 UTC, wullaski commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +      delete drupalData.data[lovellMenuKey];
Yes for sure! Max and I were both thinking that this should happen.

2022-09-01 11:40 UTC, maxx1128 commented on src/site/stages/build/drupal/metalsmith-drupal.js
> +      delete drupalData.data[lovellMenuKey];
100% agree here

2022-09-01 12:54 UTC, swirtSJW requested changes
This is all a lot more readable and consistent.  Thank you for taking on all the refactoring.
Just made one little minor suggestion.

2022-09-01 12:54 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
> +  const titleVar = variant === 'va' ? 'VA' : 'Tricare';
This has been finalized to be all caps.
```suggestion
  const titleVar = variant === 'va' ? 'VA' : 'TRICARE';
```

2022-09-01 14:35 UTC, maxx1128 commented on src/site/stages/build/drupal/process-lovell-pages.js
> +  processLovellPages,
🔥 for this entire page

2022-09-01 19:02 UTC, wullaski commented on src/site/stages/build/drupal/process-lovell-pages.js
> +  const titleVar = variant === 'va' ? 'VA' : 'Tricare';
@swirtSJW I made this change and pushed up another commit.

2022-09-01 19:33 UTC, merged