[VA-10168] Add Lovell categorized event listings
department-of-veterans-affairs/content-build pull request #1308
Opened 2022-09-21 22:03 UTC by maxx1128

## Description

The event listing pages on Lovell Tricare and VA only have federal events, but not events specific to Tricare or the VA. This takes the Tricare or VA specific events and adds them to their respective listings.

## Testing done

Visual, see [this local link and its included switch link.](http://localhost:3002/lovell-federal-va-health-care/events/)

## Screenshots

<img width="789" alt="Screen Shot 2022-09-21 at 5 55 59 PM" src="https://user-images.githubusercontent.com/10790736/191618238-be1f3c5e-d2be-4e83-987e-421721351162.png">

<img width="759" alt="Screen Shot 2022-09-21 at 5 55 35 PM" src="https://user-images.githubusercontent.com/10790736/191618241-b5fa41c0-221a-4e8d-879c-6ad8125ae1ad.png">

## Acceptance criteria
- [ ] The Lovell Tricare event listing page has federal and Tricare events, but not VA events
- [ ] The Lovell VA event listing page has federal and VA events, but not Tricare events
- [ ] The event listings still sort and filter events as expected

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-09-22 13:04 UTC, swirtSJW commented
@maxx1128 something doesn't look right in these screenshots.  There should be another event showing up on both 
![image](https://user-images.githubusercontent.com/5752113/191753255-3a6345f8-9f7e-4e9b-9d76-fe67371b6d66.png)

It should be the one that is pulled from /lovell-federal-health-care/events   (node id 36319)  


Also this is only for events,  The https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10168 is for 4 types of list pages.  Wee need the logic to cover all 4

2022-09-22 16:10 UTC, maxx1128 commented
I amended the commit so the federal event appears for both and still filters properly.

<img width="774" alt="Screen Shot 2022-09-22 at 12 06 43 PM" src="https://user-images.githubusercontent.com/10790736/191797596-99c0f713-e52c-469a-b952-2f93d5d4b82a.png">
<img width="770" alt="Screen Shot 2022-09-22 at 12 06 50 PM" src="https://user-images.githubusercontent.com/10790736/191797598-49d0c316-86f0-4536-8da4-bc4a5a162cb6.png">
<img width="712" alt="Screen Shot 2022-09-22 at 12 07 51 PM" src="https://user-images.githubusercontent.com/10790736/191797600-0dc0a717-544b-4701-9314-d4a55a4ae5c1.png">
<img width="720" alt="Screen Shot 2022-09-22 at 12 07 58 PM" src="https://user-images.githubusercontent.com/10790736/191797601-2f10750a-e659-4e2e-99a0-6e811b7d9560.png">

2022-09-23 00:55 UTC, swirtSJW requested changes
I think this pattern is more intensive than it needs to be and does not scale to the two other listing pages.  See my comments below for more details.

2022-09-23 00:55 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
> +    const allPastEvents = [...page.pastEvents.entities, ...addedEvents]
I am concerned that we are duplicating this process which already gets applied to event listing pages,  If we just get the data on the page, the normal processing that occurs during the page build should handle it.

2022-09-23 00:55 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
> +      'lovell-federal-tricare-health-care',
Looking up the pages by path seems problematic / fragile.  We should be able to look them up by type and fieldAdminstration.  We might not have that filter build yet.   

This particular lookup is not needed since the processing of individual events is not needed.  However it would still be needed for grabbing the list pages.

2022-09-23 00:55 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
> +function updateEventPageListings(page, pages) {
Can we make this less specific to event listing pages?  it should be something like updateListingPages
that iterates through the three types of listing pages.  They should each have the structure that I show a bit farther down in the comments.  Ideally there should be nothing specific to events in this.  It is just about copying and appending the reverseFieldListingNodes entities .

2022-09-23 00:55 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
> +        eventPage.entityBundle === 'event' && isLovellTricarePage(eventPage),
I don't think we need to process individual events.

Here we are kind of querying the events individually, but I don't think we have to. They exist correctly on the listing pages (same for stories and press releases)


The data for the events is already on the listing page.
![image](https://user-images.githubusercontent.com/5752113/191861121-afd6a1aa-1643-46db-b2eb-1ed2cb626bc3.png)

You should just be able to grab it from the page and move it, then delete the original page.
![image](https://user-images.githubusercontent.com/5752113/191873878-4fdae730-4df8-4679-9ca6-2891ddacf56f.png)

This should all take place before any of the bifurcation logic makes copies of the "both" page.

2022-09-27 17:37 UTC, longmd submitted a review, later dismissed
LGTM 🚀

2022-09-27 22:01 UTC, swirtSJW requested changes
Looks like you are on the right track but we have some timing / order of operations issues that need to be worked out.

2022-09-27 22:01 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
> +function updateListingsForSection(page, federalPages) {
Immediately after this is called for both VA and TRICARE, the "both" pages need to removed from the page data so they do not run through the bifurcation.

2022-09-27 22:04 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
> +  if (page.reverseFieldListingNode && futureEvents.length > 0) {
If we could get your modification to happen in front of that  step, where those are processed for future and passed, it would ideal.  Not sure if it is possible.

2022-09-28 11:48 UTC, maxx1128 commented on src/site/stages/build/drupal/process-lovell-pages.js
> +  if (page.reverseFieldListingNode && futureEvents.length > 0) {
This is just a check to make sure past and future events are only added to pages where they exist. But I can see the issue with this in hindsight - if there are no Tricare/VA events, but there are several federal events, then they won't be added together. I'll try removing it now.

2022-09-28 11:51 UTC, maxx1128 commented on src/site/stages/build/drupal/process-lovell-pages.js
> +    .map(page => updateListingsForSection(page, lovellFederalPages))
The real bifurcation takes place with the `getModifiedLovellPage` functions. Before that, they're just being sorted into different groups for the bifurcation. So the listing updates are happening right before the bifurcation page updates unless I'm misunderstanding the full scope of the process.

2022-09-28 11:57 UTC, maxx1128 commented on src/site/stages/build/drupal/process-lovell-pages.js
> +function updateListingsForSection(page, federalPages) {
Since the function is only run when making the VA and Tricare pages (and they're the only ones passed to the function), I don't believe the federal pages are actually affected here, just used to modify the VA/Tricare pages. The line that sets the Drupal data, `drupalData.data.nodeQuery.entities = [...processedLovellPages, ...otherPages]`, shows the Va/Tricare pages are still the only ones being added back to the main Drupal data so the "both" pages aren't used.

2022-09-28 12:14 UTC, maxx1128 commented on src/site/stages/build/drupal/process-lovell-pages.js
> +  if (page.reverseFieldListingNode && futureEvents.length > 0) {
Tried removing it but I went back to getting this error, the page went back to throwing this error. Going to add the checks back.

```javascript
Drupal successfully loaded!
TypeError: Cannot set property 'entities' of undefined
    at mergeListItemsFromLovellBoth (/Users/maxwellantonucci/Desktop/Repos/content-build/src/site/stages/build/drupal/process-lovell-pages.js:297:33)
    at /Users/maxwellantonucci/Desktop/Repos/content-build/src/site/stages/build/drupal/process-lovell-pages.js:349:18
    at Array.map (<anonymous>)
    at processLovellPages (/Users/maxwellantonucci/Desktop/Repos/content-build/src/site/stages/build/drupal/process-lovell-pages.js:349:6)
    at Ware.<anonymous> (/Users/maxwellantonucci/Desktop/Repos/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:357:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Failed to pipe Drupal content into Metalsmith!

```

2022-10-18 20:28 UTC, swirtSJW reviewed
I left a couple comments/questions.  
Depending on the answer to the question about the catchall, it may need changes or not.

2022-10-18 20:28 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
> + */
Thank you for the docblock

2022-10-18 20:28 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
> +function isLovellListingPage(page) {
minor:  Reports doing something that it is not 'isLovellListingPage'  gives the impression it is checking for it being a lovell page, but is only checking for it being a listing page.  `isListingPage` would be more truthful.

2022-10-18 20:28 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
> +    }
Did we need a catchall (default) for event?  If we don't really need the catchall it might be tighter to use the actual value as a map to avoid something unexpected
```suggestion
    const typePastMap = [
      'event_listing' => 'pastEvents',
      'press_releases_listing' => 'pastPressReleases',
      'story_listing' => 'pastNewsStories',
    ];
    pastObjectLabel = typePastMap[listingPage.entityBundle];   
```

2022-10-19 13:24 UTC, maxx1128 commented on src/site/stages/build/drupal/process-lovell-pages.js
> +    }
This looks like a good idea, going to try it out now and commit it if it works.

2022-10-19 14:35 UTC, maxx1128 commented
@swirtSJW Updates have been made and I confirmed it still works for me locally, should be good for another (and hopefully final 🙏) round of review.

2022-10-19 23:08 UTC, ryguyk requested changes
This is looking pretty good overall. I added a few comments and listed one big concern that I think should be changed.

2022-10-20 16:21 UTC, maxx1128 commented on src/site/stages/build/drupal/process-lovell-pages.js
> +    !page.entityUrl.path.includes('/lovell-federal-health-care') &&
Good catch, this check isn't needed here.

2022-10-20 16:24 UTC, maxx1128 commented on src/site/stages/build/drupal/process-lovell-pages.js
>  function getModifiedLovellPage(page, variant) {
I agree that a lot of pieces in this function could be broken up into smaller functions, likely ones that just need a page, the variant, and maybe a few of the values defined at the top level. But this kind of refactor seems better suited to a follow-up ticket.

2022-10-21 04:51 UTC, swirtSJW commented on src/site/stages/build/drupal/process-lovell-pages.js
>  function getModifiedLovellPage(page, variant) {
Yah lets clean up this bit in a different round.  This is going to integration for now so we can do a final round of refactoring separately.

2022-10-21 04:54 UTC, swirtSJW approved these changes
Nice work @maxx1128 and @ryguyk   If Ryan approves it is go for merge to integration.
I will build our demo env from this branch so we should be good.

2022-10-27 17:55 UTC, swirtSJW commented
I am merging this based on conversation that we will followup on the integration branch with a round of refactoring and documentation.

2022-10-27 17:55 UTC, merged