[VA-10707] Only show published vet center locations
department-of-veterans-affairs/content-build pull request #1318
Opened 2022-10-03 18:51 UTC by maxx1128

## Description

Facility locations can show draft and archived location pages when they should only show published ones. This adjusts the GraphQL query so only published ones are used on the page.

## Testing done

Visual.

## Screenshots

### Before

[Seen on this Tugboat page.](https://web-ersyymdhh8rrzxlevrh1xsmeyx7pzcpv.demo.cms.va.gov/duluth-vet-center/locations/)

<img width="804" alt="Screen Shot 2022-09-30 at 5 13 03 PM" src="https://user-images.githubusercontent.com/10790736/193655222-5d070f9c-3b63-43c2-875c-8e34db5fbcc5.png">

### After

[Seen on this local page pulled from the previous Tugboat instance.](http://localhost:3002/duluth-vet-center/locations/)

<img width="808" alt="Screen Shot 2022-10-03 at 2 40 52 PM" src="https://user-images.githubusercontent.com/10790736/193655252-e1dedb67-f429-4b0b-b08d-cec2fc1b8ebf.png">

## Acceptance criteria
- [ ] Published satellite locations are shown, while Draft and Archived ones are not.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-10-04 13:47 UTC, JayDarnell approved these changes
Seems straightforward to me @maxx1128

2022-10-04 14:23 UTC, swirtSJW commented
@maxx1128  isn't this approach circumventing this logic?  
https://github.com/department-of-veterans-affairs/content-build/blob/32813016cd0f2268b07127d5880f56f2932eb7f5/src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js#L178

I believe this is the logic that allows the preview server to show draft content.

2022-10-04 14:28 UTC, swirtSJW requested changes
I think this direct modification of the query would break the functionality for draft content to appear on preview.

All the other content types seem to use this pattern https://github.com/department-of-veterans-affairs/content-build/blob/32813016cd0f2268b07127d5880f56f2932eb7f5/src/site/stages/build/drupal/graphql/healthCareLocalFacilityPage.graphql.js#L158-L172  and it is working for them.  Something about the pattern on vet center locations is not working as expected and needs tweaking, but directly adding status to the query is kind of a nuclear option.

2022-10-04 14:45 UTC, ryguyk commented
This relates back to what I flagged up when we initially discussed this. There are a few things going on here.

2022-10-04 19:48 UTC, swirtSJW commented
The content-build from this PR seems to be falling down.  I don't believe it is related to this as the log seems to show failure long before it gets to the query, so I kicked it off again.
![image](https://user-images.githubusercontent.com/5752113/193912012-1d0f537e-6ffc-4995-8268-bc87e2d203fb.png)

2022-10-05 12:25 UTC, maxx1128 commented
@swirtSJW I checked the build this morning and it's still preparing, looks like another failure.

2022-10-11 14:33 UTC, maxx1128 commented
@swirtSJW Looks like the demo environment is up, but the duluth URL isn't working for some reason.

2022-10-18 13:55 UTC, maxx1128 commented
Rebuild has worked, can see the code in action here - https://web-ersyymdhh8rrzxlevrh1xsmeyx7pzcpv.demo.cms.va.gov/duluth-vet-center/locations/

2022-10-18 15:03 UTC, ryguyk approved these changes
This looks good to solve [#10707](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10707), though I'm not sure it's going to do anything towards [#10706](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10706). I [added a comment there](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10706#issuecomment-1282535160).

2022-10-18 16:35 UTC, swirtSJW approved these changes

2022-10-18 16:36 UTC, swirtSJW commented
Nice work getting this finished and jump starting the testing.

2022-10-18 16:36 UTC, merged