10785 connect homepage prototype to backend
department-of-veterans-affairs/content-build pull request #1326
Opened 2022-10-12 20:23 UTC by apisandipas

## Description
NOT READY FOR REVIEW

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10785
Connects the new homepage prototype template to the Drupal backend via GraphQL. This PR modified the templates and integrated the queries into the home page build script.

## Testing done
Manual testing completed locally.

## Screenshots

## Acceptance Criteria
- [ ] Benefit Promo block content displays title, description, and CTA with a link using a new clearly labeled content block type in Drupal.
- [ ] VA News promo content displays link, description, CTA with link and photo using Drupal content. 
- [ ] Popular on VA.gov link menu references heading, links, link labels, and their ordering from Drupal. 
- [ ] The Other search tools link menu references heading, links, link labels, and their ordering from Drupal.  

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-10-17 20:49 UTC, ryguyk requested changes
This looks really good. I requested a couple very small changes.

2022-10-18 17:47 UTC, apisandipas commented on src/site/stages/build/drupal/graphql/homePage.graphql.js
> +    }
Negative on the nested links requirement. I merely copied the queries as they were supplied. I will remove them.

2022-10-21 19:46 UTC, jilladams commented
Updated to point to Integration branch (per [discussion with Ryan](https://dsva.slack.com/archives/C52CL1PKQ/p1666376331770019)) and removed Do Not Merge label. @apisandipas if nothing else is blocking review, feel free to un-draft it and get this merged to integration.

2022-10-21 19:58 UTC, ryguyk approved these changes
Looks good. Thanks for making those few changes.

2022-10-21 21:13 UTC, jilladams commented
Re: merging to integration branch: I think I'm now understanding that the automated tests here can't pass until the Drupal work is merged to main, yeah?

2022-10-25 19:58 UTC, ryguyk commented
@jilladams 
>the automated tests here can't pass until the Drupal work is merged to main, yeah?
I believe this is true. In fact, it appears the tests cannot even begin because the build itself is failing. I assume this is due to trying to query data structures that are not yet in place.

2022-10-25 20:11 UTC, jilladams commented
Ok. That in mind, repointing PR back to main, since there's no longer a use case for the integration branch.

2022-10-31 16:10 UTC, longmd approved these changes

2022-11-03 17:03 UTC, jilladams commented
un-drafting / rerunning tests -- Bryan is out sick, but Drupal backend work has merged, so this PR can go ahead to review & can merge if it's in good shape.

2022-11-08 17:22 UTC, ryguyk requested changes

2022-11-08 17:22 UTC, ryguyk commented on src/site/stages/build/drupal/home.js
> +          ?.itemsOfEntitySubqueueHomePageNewsSpotlight?.[0]?.entity || {};
Very nice!

2022-11-08 17:22 UTC, ryguyk commented on src/site/includes/common-tasks.drupal.liquid
> +                <a href="{{ link.url.path }}">{{ link.label }}</a>
I notice a very defensive approach in many places, but not all. I wonder here if `link.url.path` or `link.label` can ever be undefined or empty if `link` itself is defined. Might be worth being extra defensive.

2022-11-08 17:22 UTC, ryguyk commented on src/site/includes/common-tasks.drupal.liquid
> +              <a href="{{ link.url.path }}">{{ link.label }}</a>
Same comment about defensive checking.

2022-11-08 17:22 UTC, ryguyk commented on src/site/includes/hero.drupal.liquid
> +          <a class="vads-c-action-link--white" href="{{ fieldPromoCta.entity.fieldButtonLink.url.path }}">
Same comment about defensive checks.

2022-11-08 17:22 UTC, ryguyk commented on src/site/includes/news-spotlight.drupal.liquid
> +            alt="{{ fieldImage.entity.image.alt }}" />
Just for contrast, I'm not sure we should block rendering of the image if the alt-text property is not defined. But this is probably a question for @laflannery more than anything. If we don't have alt text provided for some reason, should we still render the image?

2022-11-08 17:22 UTC, ryguyk commented on src/site/includes/news-spotlight.drupal.liquid
> +          {% endif %}
Probably should check for existence of both the `href` and link text.

2022-11-08 17:22 UTC, ryguyk commented on src/site/includes/news-spotlight.drupal.liquid
> +            {% endif %}
Same idea. We're checking that the link text is defined, but not the link `href`.

2022-11-08 17:29 UTC, laflannery commented on src/site/includes/news-spotlight.drupal.liquid
> +            alt="{{ fieldImage.entity.image.alt }}" />
@ryguyk I do agree that we should still render the image, even if alt text is not provided.  However, the image is coming from Drupal correct? Alt text is required in the CMS, an editor should not be able to add an image without filling out the alt text field so I didn't think this scenario would apply. Is there a a different way images could be added in which alt text may not be present?

2022-11-08 18:20 UTC, ryguyk commented on src/site/includes/news-spotlight.drupal.liquid
> +            alt="{{ fieldImage.entity.image.alt }}" />
@laflannery Thanks for the feedback. You're right. It's likely not possible that the alt text would be undefined. In writing our front-end code, though, we prefer to be extra defensive in checking for existence before we attempt to render something. In this case, it doesn't seem necessary to be so defensive around the alt text.

2022-11-08 18:21 UTC, laflannery commented on src/site/includes/news-spotlight.drupal.liquid
> +            alt="{{ fieldImage.entity.image.alt }}" />
Thanks for clarifying! I just wanted to make sure I was understanding correctly.

2022-11-08 20:11 UTC, dsasser requested changes
Only issue I found was that the alert on the main homepage was not visible on the new homepage.
<img width="1916" alt="missing-alert" src="https://user-images.githubusercontent.com/221539/200665036-944602bf-596a-40d3-8606-e9cb8041ecc0.png">

Other components appear to be rendering correctly, and respecting order defined in CMS:
<img width="1623" alt="Screen Shot 2022-11-08 at 12 06 21 PM" src="https://user-images.githubusercontent.com/221539/200665299-30cd217c-7c71-4bbd-a0b3-6e7b922c35e5.png">
<img width="1813" alt="Screen Shot 2022-11-08 at 12 04 58 PM" src="https://user-images.githubusercontent.com/221539/200665302-886e8d23-9b00-431d-9871-67647753751a.png">
<img width="1387" alt="Screen Shot 2022-11-08 at 12 04 01 PM" src="https://user-images.githubusercontent.com/221539/200665306-5ab5a555-d37b-44d2-8478-71bfe76ec47b.png">
<img width="1821" alt="Screen Shot 2022-11-08 at 12 03 10 PM" src="https://user-images.githubusercontent.com/221539/200665314-d66becd8-00c4-4e7c-87ce-c425cc34f6cf.png">
<img width="1893" alt="Screen Shot 2022-11-08 at 11 57 48 AM 1" src="https://user-images.githubusercontent.com/221539/200665316-7a8fd0c0-86e6-40f0-8fb1-181981e14228.png">

2022-11-08 20:28 UTC, apisandipas commented
@dsasser  Great callout on the alert banner. I raised this in the Homepage Sync today and it's not a blocker at this time.

2022-11-08 20:36 UTC, it-harrison approved these changes

2022-11-08 20:50 UTC, ryguyk commented on src/site/includes/hero.drupal.liquid
> +          <a class="vads-c-action-link--white" href="{{ fieldPromoCta.entity.fieldButtonLink.url.path }}">
Nice fixes. This is the only one I still see.

2022-11-08 20:56 UTC, dsasser commented
> @dsasser Great callout on the alert banner. I raised this in the Homepage Sync today and it's not a blocker at this time.

Perfect, approval inbound.

2022-11-08 20:57 UTC, dsasser approved these changes

2022-11-08 20:58 UTC, ryguyk approved these changes
Thanks for fixes. Looks great.

2022-11-08 21:45 UTC, merged