Outreach filteres added and sorted
department-of-veterans-affairs/content-build pull request #1350
Opened 2022-11-04 17:24 UTC by jtmst

## Description
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11153

Adjusted graphql query to allow outreach filters to be added dynamically

## Testing done
Local testing with backend tugboat instance

## Screenshots
<img width="284" alt="Screen Shot 2022-11-02 at 9 45 32 AM" src="https://user-images.githubusercontent.com/61624970/200036755-c2be002b-4c4d-4820-8913-50b0c6abeb88.png">
<img width="678" alt="Screen Shot 2022-11-04 at 1 14 48 PM" src="https://user-images.githubusercontent.com/61624970/200036761-d228df87-6a96-40e6-b0b4-1d2fc09152c8.png">

## Acceptance criteria
- [ ] The topic filter options are powered by field_lc_categories from the data items on the page (this is a new field and will need to be added to the graphql.)
- [ ] ~~The file type filter options are powered by field_format  (this is not a new field)~~
- [ ] Topic filter and type filter select lists are alpha sorted
- [ ] A veteran should never be able to select a topic option that has no data. (example: Disability should not appear as a filter if there are no data items of topic Disability.)
- [ ] The field field_benefits is no longer referenced on the template and no longer in the graphQL 
- [ ] Accessibility review - receives 508 approval 
- [ ] Create future issue -  The two filters are aware of each other and self restrict the other's limits.  (example: If I select format = video, I should not see types in the filter that contain no videos. This would prevent from selecting a filter combination that has no results.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-11-07 15:54 UTC, apisandipas requested changes
I had one concern/comment/question. I don't think it should be a blocker, but perhaps check with @ryguyk for his opinion.

2022-11-07 15:54 UTC, apisandipas commented on src/site/filters/liquid.js
> +
For building up an array like this, I think it's a little more idiomatic and easier to read if you use `reduce` function. I'm interested to know @ryguyk's take on that though.

2022-11-08 17:56 UTC, apisandipas approved these changes
LGTM, refactor looks good .

2022-11-09 19:50 UTC, merged

2022-11-09 22:10 UTC, jilladams commented
One flag here: 
https://prod.cms.va.gov/admin/content?title=PACT&type=outreach_asset&moderation_state=All&owner=All -- in Prod we now have a batch of Publications using the PACT act taxonomy, as of EOD yesterday 11/8

Verified that those nodes contain that data on Staging, e.g. https://staging.cms.va.gov/node/50916/edit

But on Staging (where this fix is now deployed), filtering by PACT act doesn't show any publications: https://staging.va.gov/outreach-and-events/outreach-materials/

2022-11-09 22:12 UTC, jilladams commented
(Will take a look once it's on prod, just in case this is some Staging data weirdness.)