[VA-11538] New Homepage "Create Account" Updates
department-of-veterans-affairs/content-build pull request #1385
Opened 2022-11-30 18:59 UTC by maxx1128

## Description

closes [#11538](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11538)
relates to [#11570](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11570)

## Testing done & Screenshots

Visual

<img width="1251" alt="Screen Shot 2022-11-30 at 1 50 23 PM" src="https://user-images.githubusercontent.com/10790736/204883703-66e01a69-8f6f-49e1-8127-552d00817c42.png">

## QA steps

What needs to be checked to prove this works?

1. Check out this branch and do a local PR build
2. Go to `http://localhost:3002/new-home-page/`
3. Confirm that the Create Account area has the new styles and elements as expected

What needs to be checked to prove it didn't break any related things?  

1. The other areas of the new homepage need to be checked for proper styling and functionality to make sure they weren't indirectly broken.

What variations of circumstances (users, actions, values) need to be checked?  

1. Test the page on different screen sizes
   - [ ] Validate that the Create Account area still renders properly, visibly, and is still accessible
2. Then try using the page with a screen reader
   - [ ] Validate that the content is read properly and not conveying any different meaning than what visual users get.

## Acceptance criteria

- [ ] "Welcome to VA.gov" is bigger and doesn't have lines above and below
    * Using a larger font size broke the text into two lines, so changing this will likely require an additional change from `vets-website` where the headline width is set.
- [ ] The link to the new account creation page in Resources and Support has the "Learn how an account helps you" label and is styled as a link. 
- [ ] A Veteran or beneficiary can click on the "Learn how an account helps you" label to view the new Resource and Support account creation page [_link TBD_, left as `#` placeholder for now]
- [ ] "Create account" component has updated intro text. 

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-11-30 21:53 UTC, jilladams requested changes

2022-11-30 21:53 UTC, jilladams commented on src/site/includes/hero.drupal.liquid
> +              Create an account to manage your VA benefits and care in one place - any time, from anywhere."
s/-/—

2022-11-30 21:54 UTC, jilladams requested changes

2022-11-30 21:54 UTC, jilladams commented on src/site/includes/hero.drupal.liquid
> +              Create an account to manage your VA benefits and care in one place - any time, from anywhere."
- [ ] Remove trailing "

2022-11-30 22:01 UTC, jilladams requested changes

2022-11-30 22:01 UTC, jilladams commented on src/site/includes/hero.drupal.liquid
> +              Create an account to manage your VA benefits and care in one place - any time, from anywhere."
@maxx1128 can you also confirm the font treatment for the "create an account" copy here? Two questions: 
1. the line-height is more spaced out in the design vs. your screenshot of build. We should lean on the design system, so if you can point to design system guidance, that's prob fine. If not, let's try to match the design.
2. The markup looks like that text is being handled as an h2. Ticket doesn't spell out how this should be handled semantically, so you may need to consult with @laflannery if we aren't sure whether / why that's the right call.

2022-12-01 13:36 UTC, laflannery commented on src/site/includes/hero.drupal.liquid
> +              Create an account to manage your VA benefits and care in one place - any time, from anywhere."
@jilladams I believe you are talking about the "Create an account to manage...." text and if so an H2 is correct, it's my original guidance from the mural, I would still like this to be an H2 even though the text changed:
![image](https://user-images.githubusercontent.com/106678594/205066245-6b9d66f0-5786-4384-bb64-066ba1f6dd18.png)

Also, looking at the screenshots above I noticed in the PR screenshot there is a " character at the end but that isn't in sketch.  I didn't notice that in your comment so just making sure we remove that extra character if that is in fact just a typo.
![image](https://user-images.githubusercontent.com/106678594/205066609-f011fbf8-4a42-4815-8af3-aa7bbb2d367d.png)

2022-12-01 14:06 UTC, maxx1128 commented on src/site/includes/hero.drupal.liquid
> +              Create an account to manage your VA benefits and care in one place - any time, from anywhere."
@jilladams Good catch with the line-height, I agree it's off from what's in the design. I'll adjust that now along with all the other updates.

2022-12-01 14:15 UTC, maxx1128 commented
Updated local homepage.

<img width="1218" alt="Screen Shot 2022-12-01 at 9 14 38 AM" src="https://user-images.githubusercontent.com/10790736/205075179-e329621f-dcc1-4135-9ab2-46ce36ead6b7.png">

2022-12-01 16:01 UTC, apisandipas approved these changes
This looks good to me. Noting that the link for “Learn how an account helps you” is TBD.

2022-12-01 22:31 UTC, jilladams commented
@mmiddaugh FYI this is ready to go, with one placeholder link: “Learn how an account helps you" in the Create Account section. Any update on where that should point?

2022-12-01 22:32 UTC, jilladams approved these changes

2022-12-01 22:34 UTC, mmiddaugh commented
@jilladams The page is in process but the URL won't be finalized until the content is (since it uses the H1). We may not have the URL for that page until the staging review.

2022-12-01 22:43 UTC, jilladams commented
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11771 ticketed for follow up on that URL later.

2022-12-02 13:13 UTC, merged