added alert
department-of-veterans-affairs/content-build pull request #1387
Opened 2022-12-01 17:49 UTC by jtmst

## Description
Adds an alert to forms rendered by forms detail page with an issue date before 3/1/2022

closes 11022

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11022
## Testing done & Screenshots

## QA steps
1. Navigate to form 22-5490 from find-forms
    - Observe that the form is unchanged, there is no alert
2. Navigate to form 10-0386/
    - Observe that the alert renders as expected 

## Acceptance Criteria
- [ ] Alert shows only if `issue date` is before <=3/1/22
- [ ] Not dismissible
- [ ] There is no `role="alert"` attribute
- [ ] Requires design review - schedule meeting with Wes & @thejordanwood 
- [ ] Requires accessibility review by @laflannery. Can add her to the PR for awareness.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-12-01 19:01 UTC, maxx1128 approved these changes

2022-12-01 23:09 UTC, jilladams commented
Form detail page last updated May 2022: 
http://73d23d9b4b5a9239e916302056b68f62.review.vetsgov-internal:3001/find-forms/about-form-22-1990/
<details>
<summary>22-1990</summary>

![Screen Shot 2022-12-01 at 3 03 35 PM](https://user-images.githubusercontent.com/85581471/205177518-4825e202-6f55-460e-aa04-ab1a6ecf80dd.png)
</details>

Form detail page last updated Oct 2013:
http://73d23d9b4b5a9239e916302056b68f62.review.vetsgov-internal:3001/find-forms/about-form-of-306/
<details>
<summary>OF-306 screenshot</summary>

![Screen Shot 2022-12-01 at 3 01 58 PM](https://user-images.githubusercontent.com/85581471/205177360-88ce06b6-c3fa-4855-bb29-57640adb6a03.png)
</details>

Form detail page last updated March (3) 2022
<details>
<summary> VA21a </summary>

![Screen Shot 2022-12-01 at 3 05 37 PM](https://user-images.githubusercontent.com/85581471/205177813-ded466b2-0760-49f7-ad97-69c6f3cceb95.png)
</details>

2022-12-01 23:11 UTC, jilladams commented
Approving - I'd love to make sure either Ryan or Bryan get a look at it pre-merge, if they haven't already talked to you about these changes elsewhere.

2022-12-01 23:12 UTC, jilladams approved these changes

2022-12-01 23:17 UTC, jilladams requested changes
caught the copy issue late, changing from Approved to Request Changes to make sure this is signed off before merge

2022-12-01 23:17 UTC, jilladams commented on src/site/layouts/va_form.drupal.liquid
> +                If you download this form now, you won't be able to use it after January 7, 2023. You can download a new copy in January.
@wesrowe same flag in the other pr: the copy in our ticket doesn't match the copy Laura provided in https://github.com/department-of-veterans-affairs/va.gov-team/issues/48458#issuecomment-1320500257. Can you confirm whether our ticket copy is ok to merge, or needs to be updated to use the SWC copy provided?

2022-12-02 16:56 UTC, wesrowe commented
✅ Looks good in review instance

DO NOT MERGE, we want to hold this back for Staging Review etc.

2022-12-02 22:31 UTC, jilladams approved these changes

2022-12-07 18:12 UTC, merged