Allow sitewide asset opt-out in production
department-of-veterans-affairs/content-build pull request #1391
Opened 2022-12-06 23:35 UTC by bkjohnson

## Description

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1211
Relates to https://github.com/department-of-veterans-affairs/content-build/pull/1358

This will allow the particular script and link tags to be excluded from production pages if an application has a truthy `useLocalStylesAndComponents` in its registry.

Right now the `pre-check-in` application is the only one that will be impacted by this change:

https://github.com/department-of-veterans-affairs/content-build/blob/69dbfa52df4c220c4827e2f35b583ad8c7973bc5/src/applications/registry.json#L1113-L1122

## Testing done & Screenshots

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

1. Do this
   - [ ] Validate that
2. Then
   - [ ] Validate that
3. Then validate Acceptance Criteria from issue

## Acceptance criteria

- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2023-01-04 23:26 UTC, acrollet requested changes
The logical NOT operator does not exist in liquid, but these suggestions should work. (Discovered this while working on #1425)

2023-01-04 23:26 UTC, acrollet commented on src/site/includes/header.html
>      {% endif %}
```suggestion
    {% unless useLocalStylesAndComponents %}
      <script nonce="**CSP_NONCE**" defer data-entry-name="web-components.js"></script>
    {% endunless %}
```

2023-01-04 23:26 UTC, acrollet commented on src/site/includes/header.html
>    {% endif %}
```suggestion
  {% unless useLocalStylesAndComponents %}
    <link rel="stylesheet" data-entry-name="style.css">
  {% endunless %}
```

2023-01-24 18:12 UTC, longmd approved these changes
LGTM 🚀

2023-01-24 19:40 UTC, jtmst approved these changes

2023-01-24 23:50 UTC, acrollet approved these changes
We reviewed this today and it's good to go from our perspective - only ask is that we can coordinate when this gets merged because we'd like to be able to validate that things function correctly in prod when it goes out. Thanks!

2023-01-25 15:49 UTC, Andrew565 commented
> only ask is that we can coordinate when this gets merged

If it's more convenient, I can re-assign this PR to you and you can handle the merge when you're ready?

2023-01-26 16:55 UTC, merged