[VA-12011] Fix Lovell Tricare Menu links
department-of-veterans-affairs/content-build pull request #1409
Opened 2022-12-20 20:33 UTC by maxx1128

## Description

The "opposite variant" URL checks need to be applied to menu links as well as page links. This change puts that logic into a function that can be applied to both and fix the broken Tricare links that would otherwise bring links back to the VA pages.

closes [#12011](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12011)
relates to [#11026](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11026)

## Testing done & Screenshots

Visual testing. See URLs from the highlighted menu links in the bottom left of each screenshot.

<img width="1179" alt="Screen Shot 2022-12-20 at 3 28 47 PM" src="https://user-images.githubusercontent.com/10790736/208760439-7e669af9-6325-4b26-bfae-6ade8daaaee3.png">
<img width="1179" alt="Screen Shot 2022-12-20 at 3 28 52 PM" src="https://user-images.githubusercontent.com/10790736/208760444-f76dd45d-d3ac-4b94-91ae-fa34c5264754.png">

## QA steps

What needs to be checked to prove this works?  

Tricare menu links, and they link to other Tricare pages.

What needs to be checked to prove it didn't break any related things?  

The menu links on VA pages still link to VA pages, and the switch links still work properly.

## Acceptance criteria

- [ ] The side menu on Tricare pages link to other Tricare pages, not VA pages
- [ ] VA pages still link to other VA pages

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-12-21 20:39 UTC, ryguyk requested changes
A few changes to consider. It largely boils down to naming, though might possibly imply a few other tweaks.

2022-12-21 20:39 UTC, ryguyk commented on src/site/stages/build/drupal/process-lovell-pages.js
> +
**CONSIDER**
I think my personal preference would be to name this starting with lowercase: `urlOppositeVariant`. I'm not sure if we have any coding standards specifically mandating that.

2022-12-21 20:39 UTC, ryguyk commented on src/site/stages/build/drupal/process-lovell-pages.js
> +
**SHOULD**
I don't think this function is doing what it advertises. I'm not sure it actually ever returns the opposite-variant url, does it? There are two possible return values:
1. If the condition included on lines 48-50 evaluates to true, it will return a url without any variant (a federal url).
2. If the condition evaluates to false, it'll return the original path.

2022-12-21 20:39 UTC, ryguyk commented on src/site/stages/build/drupal/process-lovell-pages.js
> +    page.entityUrl.path = URLOppositeVariant(page.entityUrl.path, variant);
This relates to the comment above about the function not doing what it advertises. It seems to be confirmed here. If this were doing strictly what is advertised, I don't think it would make sense. I don't think we would want to set the page path to be the opposite variant. I think what this function is really doing is _resetting_ the page path to be the federal path.

2022-12-22 13:38 UTC, maxx1128 commented on src/site/stages/build/drupal/process-lovell-pages.js
> +    page.entityUrl.path = URLOppositeVariant(page.entityUrl.path, variant);
Resetting it to the federal path is a better name for it, the opposite URL part is more part of the logic used instead of the larger purpose. Some better names would probably be `resetToFederalUrl` or `resetFederalUrlIfNeeded`.

2022-12-29 18:51 UTC, ryguyk approved these changes
I think this name change makes things much more clear!

I still wonder if this is the best overall approach to this particular logic. It seems confusing (though I ultimately understand what's going on) to reset the url based on the opposite variant. All this said, I think we can address this in our pending work to refactor this function.

2022-12-30 17:05 UTC, swirtSJW approved these changes
This is approved.  Waiting only on code freeze to be lifted to merge.

2022-12-30 17:21 UTC, swirtSJW commented
I am closing the corresponding ticket.

2023-01-03 14:29 UTC, merged