VACMS-11967 update manage health block for lovell system pages
department-of-veterans-affairs/content-build pull request #1413
Opened 2022-12-22 17:09 UTC by tjheffner

## Description

closes [#11967](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11967).

Removes "manage health block" for Lovell TRICARE system. Updates title of "manage healthy block" for Lovell VA system. Unchanged for other VA system pages.

## Testing done & Screenshots
Lovell TRICARE system, no block
![Screen Shot 2022-12-22 at 9 04 15 AM](https://user-images.githubusercontent.com/11279744/209188530-4098c11f-a0ca-431a-82f7-f1b2174a9331.png)

Lovell VA system, updated title ("Manage your VA health online")
![Screen Shot 2022-12-22 at 9 04 25 AM](https://user-images.githubusercontent.com/11279744/209188531-57d1155b-9334-4ce6-8b73-8ddee24bdf8e.png)

Non-Lovell VA system, no change to title
![Screen Shot 2022-12-22 at 9 04 08 AM](https://user-images.githubusercontent.com/11279744/209188523-a11d20a1-4b8c-4397-b26c-9eed98158913.png)

## QA steps

**What needs to be checked to prove this works?**  
- View Lovell system pages for TRICARE and VA.
- http://localhost:3002/lovell-federal-tricare-health-care/
- http://localhost:3002/lovell-federal-va-health-care/
**What needs to be checked to prove it didn't break any related things?**  
- View a system page for a non-Lovell VA system
- http://localhost:3002/new-mexico-health-care/

## Acceptance criteria
- [x] When viewing the Lovell TRICARE system page the Manage your health online block should not be present
- [x] When viewing the Lovell VA system page the heading for this block should read as Manage your VA health online
- [x] When viewing any other system page the heading and block should still be present and unchanged

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-12-29 19:04 UTC, swirtSJW commented on src/site/layouts/health_care_region_page.drupal.liquid
> +          {% if title != 'Lovell Federal TRICARE health care' %}
Do we have access to fieldAdministration in the template?  If we do, I'd rather see that be used as the condition since it is less mutable than the title.

2022-12-29 20:00 UTC, tjheffner commented on src/site/layouts/health_care_region_page.drupal.liquid
> +          {% if title != 'Lovell Federal TRICARE health care' %}
We do. This is the value for Lovell TRICARE,
![Screen Shot 2022-12-29 at 11 58 55 AM](https://user-images.githubusercontent.com/11279744/210005746-e6fce9e0-8033-451a-b126-181e7de089d1.png) & `1040` for Lovell VA. Should I base on those entity ids instead of the title?

2022-12-29 20:05 UTC, maxx1128 requested changes

2022-12-29 20:05 UTC, maxx1128 commented on src/site/layouts/health_care_region_page.drupal.liquid
> +          {% if title != 'Lovell Federal TRICARE health care' %}
I think that field is available here, and I agree that should be used instead.

2022-12-29 20:29 UTC, swirtSJW commented on src/site/layouts/health_care_region_page.drupal.liquid
> +          {% if title != 'Lovell Federal TRICARE health care' %}
Confirmed  This looks good.

2022-12-29 20:30 UTC, swirtSJW approved these changes
Waiting on tests to pass.

2022-12-30 01:40 UTC, maxx1128 approved these changes

2022-12-30 02:36 UTC, merged