VACMS-11996: adds unit tests for Lovell listing pages
department-of-veterans-affairs/content-build pull request #1418
Opened 2022-12-28 20:32 UTC by ryguyk

## Description
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11996

Listing pages (stories, events, news) for Lovell Health Care are created by combining the entities from the Lovell Federal with the entities from Lovell Tricare and Lovell VA. Entities on Lovell Federal should ultimately be displayed on both Lovell Tricare and Lovell VA listing pages so that a listing page for Lovell Tricare, for example, is comprised of entities that are specific to Tricare _combined with_ entities that are defined at the Federal level (Federal entities should display on both Tricare _and_ VA listing pages).

This PR adds unit tests to confirm that the Lovell-specific processing correctly handles things as described above.

## Testing done & Screenshots
This PR is entirely focused on creating tests. The tests all pass with the created fixtures.

## QA steps
Locally
1. `yarn test:unit src/site/stages/build/drupal/tests/lovell/listingPages.unit.spec.js`
   - [ ] Validate that there are six (6) passing tests and no failing tests.

On review instance
1. Examine unit tests
   - [ ] Validate that the six (6) tests in question pass.

2022-12-29 14:37 UTC, apisandipas approved these changes
Looks good to me.

2022-12-29 15:23 UTC, maxx1128 requested changes
The tests technically pass here and the data is set up well, but I think the unit tests need to check more than the number of stories. The test checking that Federal and Tricare stories are properly merged could accidentally merge the Federal and VA stories together, but since the total number of stories is still two, the test would still pass. They should also check the correct groupings of stories/news/events.

The easiest way I think to do this is to check the titles of whatever is being filtered. Since it would be in each test, my thought is to add a function like this to the top:

```javascript
const checkEntitiesFromCategories = (entities, category) => {
  return entities
    .map(entity => entity.title)
    .every(
      title =>
        title.includes('Both') ||
        title.includes('Federal') ||
        title.includes(category),
    );
};
```

Then each test could have a check like this:

```javascript
const hasEventsFromProperCategories = checkEntitiesFromCategories(
  mergedEvents.pastEvents.entities,
  'TRICARE', // Or 'VA', depending on the test
);
expect(hasEventsFromProperCategories).to.be.true;
```

I tried this out on a few of the unit tests and it works as expected, it just may need some editing or renaming.

2022-12-29 18:36 UTC, ryguyk commented
@maxx1128 That's some very good feedback. I agree the tests would be much more robust with checks beyond simply entity counts, so I've added tests to check merged titles. 

Just a note: I did not implement exactly in the fashion you laid out above. Instead, similar to the existing tests checking the counts, I am comparing the exact merged titles to the exact initial data. I think that is a bit more robust than hard-coding in the test the expected strings.

Thanks for the thoughtful feedback!

2022-12-29 19:59 UTC, maxx1128 approved these changes
This looks good! The tests are great and check the titles, I played with them a bit locally and they check out 👍

2022-12-30 15:11 UTC, swirtSJW approved these changes
Nice work!

2022-12-30 15:12 UTC, merged