Adjusted header levels bene hub-rail (12169)
department-of-veterans-affairs/content-build pull request #1455
Opened 2023-01-30 16:20 UTC by jtmst

## Description
Updates header levels on the benefit hub rail without changing visual presentation

closes #12169

## Testing done & Screenshots
<img width="1414" alt="Screen Shot 2023-01-30 at 11 14 43 AM" src="https://user-images.githubusercontent.com/61624970/215532587-8133471e-281a-4e8e-bac0-2a4f24751a4a.png">
<img width="1414" alt="Screen Shot 2023-01-30 at 11 15 01 AM" src="https://user-images.githubusercontent.com/61624970/215532589-51650df0-19df-4944-85a6-6ff478018659.png">
<img width="1414" alt="Screen Shot 2023-01-30 at 11 15 11 AM" src="https://user-images.githubusercontent.com/61624970/215532592-da3f091d-6f48-41c1-8166-bb3d484551b9.png">

## QA steps

- Navigate to a benefit hub landing page (eg /health-care) 
- Verify that header levels are appropriate for hub rail.
- Verify that there are no visual changes

## Acceptance criteria

- [ ] Header levels updated to not skip any levels
- [ ] No visual changes

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2023-01-30 19:34 UTC, maxx1128 requested changes
One small question otherwise it looks good to me.

2023-01-30 19:34 UTC, maxx1128 commented on src/site/blocks/promo.drupal.liquid
> +        <h2 class="vads-u-font-size--h4 vads-u-text-decoration--underline vads-u-margin-top--0">
Why were the `vads-u-text-decoration--underline vads-u-margin-top--0` classes added here when they weren't added before?

2023-01-30 20:07 UTC, jilladams commented on src/site/blocks/promo.drupal.liquid
> +        <h2 class="vads-u-font-size--h4 vads-u-text-decoration--underline vads-u-margin-top--0">
I believe the answer is: we wanted a semantic h2 but a visual h4, so guessing these styles are achieving the visual h4 overrides to native h2 behavior. 

But that's a guess Josh can confirm/deny.

2023-01-30 20:09 UTC, jilladams commented
These changes align with decisions in the [Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1674589567866/77a3856eae75e3b9df28f0f7092efbcf717c95ff?sender=u252e7152800e3981889d1910). Still getting a 502 on the RI, so can't check visual preso yet.

2023-01-30 20:35 UTC, jtmst commented on src/site/blocks/promo.drupal.liquid
> +        <h2 class="vads-u-font-size--h4 vads-u-text-decoration--underline vads-u-margin-top--0">
Yep thats correct.  Switching to an h2 was removing the underline and adding margin.  This way keeps the visual presentation the same

2023-01-30 22:34 UTC, jilladams approved these changes
Compared markup and visuals to prod: 

![promo box](https://user-images.githubusercontent.com/85581471/215611269-15f3be87-99ce-42eb-896d-5a7f7250acd4.png)
![ask questions](https://user-images.githubusercontent.com/85581471/215611280-c87a8873-e3ae-424f-af06-f9c2db24515f.png)
![connect with us](https://user-images.githubusercontent.com/85581471/215611295-25cd1a96-16f4-4063-b97e-de547b65b910.png)

2023-01-31 13:11 UTC, maxx1128 approved these changes

2023-01-31 13:27 UTC, laflannery approved these changes
Looks good, no axe heading errors

2023-01-31 14:31 UTC, rmessina1010 commented
Have we checked to see if any unit test/E2E test would be affected by the change in header levels?

2023-01-31 14:40 UTC, jtmst commented
> Have we checked to see if any unit test/E2E test would be affected by the change in header levels?

Not beyond seeing that the tests are all passing still on this PR

2023-01-31 15:13 UTC, jtmst commented
It does not appear as if any other unit or e2e tests will be affected @rmessina1010

2023-01-31 16:29 UTC, rmessina1010 approved these changes
LGTM

2023-01-31 17:12 UTC, merged