VA-12717: Facility health services use phone number component
department-of-veterans-affairs/content-build pull request #1521
Opened 2023-04-03 15:37 UTC by maxx1128

## Description

Facility health services have phone numbers that are improperly formatted. This uses our existing `va-telephone` component which fixes these formatting issues and gets it set up for better maintainability.

closes [#12717](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12717)

## Testing done & Screenshots

Visual, see below

<img width="1393" alt="Screen Shot 2023-04-03 at 11 35 10 AM" src="https://user-images.githubusercontent.com/10790736/229558159-c9942bf1-ac80-4ce6-8251-5a097ff2d9a3.png">

## QA steps

What needs to be checked to prove this works?  
What needs to be checked to prove it didn't break any related things?  
What variations of circumstances (users, actions, values) need to be checked?  

1. Do a new build with this pull request
2. Check that the [Jamaica Plain VA Medical Center](http://localhost:3002/boston-health-care/locations/jamaica-plain-va-medical-center/) "Blind and Low Vision Rehabilitation" section phone number is correct
   - [ ] The `aria-label` includes the extension
   - [ ] The anchor tag's `href` includes a "+1" at the start
   - [ ] The anchor tag's `href` has the extension after a comma

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2023-04-04 15:37 UTC, jtmst approved these changes

2023-04-04 19:12 UTC, ryguyk requested changes

2023-04-04 19:12 UTC, ryguyk commented on src/site/facilities/health_care_local_health_service.drupal.liquid
> +      />
This doesn't look right to me. This `else` block is the fallback for when there is no phone number available on the service itself. In this `else` block, as was previously the case, it should fall back to the facility phone number. In fact, `number.entity.fieldPhoneNumber` should never be defined here. `number` is scoped to the `for` loop in the `if` block.

2023-04-04 20:24 UTC, laflannery commented
@maxx1128 I just looked at this - why does this not look like the component in the design system?

**Design system:**
![image](https://user-images.githubusercontent.com/106678594/229911751-0b25b4ba-8aa4-418e-940e-f812f9b40d95.png)

- No spaces in the href
- periods in the aria-label

**Review instance:**
![image](https://user-images.githubusercontent.com/106678594/229911886-aa3405f9-44ac-42ce-bc4a-08cd4316ea71.png)

- Spaces in the href
- dashes in the aria-label

Why wouldn't this be identical to the DS component?

2023-04-04 21:12 UTC, maxx1128 commented on src/site/facilities/health_care_local_health_service.drupal.liquid
> +      />
This is a good catch. I'll try to get in a fix for this early tomorrow.

2023-04-06 15:04 UTC, maxx1128 commented
@laflannery I got it working with the dashes filtered from the numbers and the code is lining up better with what's needed now. This component also includes the extension in the visible phone number as it does in the component library.

<img width="1559" alt="Screen Shot 2023-04-06 at 11 00 11 AM" src="https://user-images.githubusercontent.com/10790736/230420271-f4d1964f-930d-48bf-b841-8248d082134f.png">

2023-04-06 18:28 UTC, maxx1128 commented
@ryguyk This is ready for re-review.

2023-04-10 14:52 UTC, ryguyk requested changes

2023-04-10 14:52 UTC, ryguyk commented on src/site/filters/liquid.js
> +  };
If `data` is not a string, this will throw an error. I think there are two options:
1. `if (data && data.replace)`
   - This will return null if it's undefined or if it's not a string (doesn't have the `replace` method).
2. `return data.replace?.(/-/g, '')`
   - This will return `undefined` if `replace` is not available. You could return `null` by instead doing `return data.replace?.(/-/g, '') || null`, if returning `null` is actually necessary.

Further, I wonder about the naming/usage of this function. Right now, it's really just `removeDashes`. The passed in value does not need to be a string representing a number. So, this function could theoretically be used elsewhere. This might be a good thing. If it is, I'd suggest renaming to reflect that. 

If not, and we instead want to limit this function call to strings representing phone numbers, we could perhaps ensure that the passed in data is actually of the format `nnn-nnn-nnnn` or whatever format we're expecting. If the passed-in value is not of that format, the function could return either `undefined` or the original value (I'm not sure which makes more sense).

2023-04-10 15:22 UTC, maxx1128 commented on src/site/filters/liquid.js
> +  };
This is good feedback, I'm going with this for the code and name changes:

```javascript
liquid.filters.removeDashes = data => {
  return data.replace?.(/-/g, '') || null;
};
```

2023-04-10 16:48 UTC, maxx1128 commented on src/site/filters/liquid.js
> +  };
Got a build error, went back to the conditional check.

2023-04-10 18:58 UTC, ryguyk approved these changes
This looks great. Nice job on the fixes.

2023-04-10 19:10 UTC, merged