Refactors Google Maps directions links
department-of-veterans-affairs/content-build pull request #1629
Opened 2023-07-07 16:50 UTC by ryguyk

## Description

closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12085
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13837

- Google Maps directions links are implemented in multiple places. This adds a reusable abstraction (template) for this component.
- The links themselves needed two tweaks:
   - Visually, they now read, "Get directions on Google Maps"
   - For screen readers, they add the title of the facility that the directions are to
- This allows consistency across the website. Previously, these were being handled in multiple ways.

## Screenshots
### VAMC-facility page:
![image](https://github.com/department-of-veterans-affairs/content-build/assets/6863534/fed4ea9b-dbc7-4d1e-b6c7-0390d941a4f4)
```
<div>
  <a href="https://maps.google.com?saddr=Current+Location&amp;daddr=113 Comanche Road, Fort Meade, SD 57741-1002" hreflang="en">
    Get directions on Google Maps <span class="sr-only">to Fort Meade VA Medical Center</span>
  </a>
</div>
```

### VAMC-region page:
![image](https://github.com/department-of-veterans-affairs/content-build/assets/6863534/3f97cd84-bd15-4de4-84d0-f7ca9ce99ed0)
```
<div>
  <a href="https://maps.google.com?saddr=Current+Location&amp;daddr=1500 East Woodrow Wilson Avenue, Jackson, MS 39216-5116" hreflang="en">
    Get directions on Google Maps <span class="sr-only">to G.V. (Sonny) Montgomery Department of Veterans Affairs Medical Center</span>
  </a>
</div>
```

### VAMC-locations-list page:
![image](https://github.com/department-of-veterans-affairs/content-build/assets/6863534/188e2e6c-ba91-414a-a80b-17cbca096fa1)
```
<div>
  <a href="https://maps.google.com?saddr=Current+Location&amp;daddr=500 East Veterans Street, Tomah, WI 54660-3105" hreflang="en">
    Get directions on Google Maps <span class="sr-only">to Tomah VA Medical Center</span>
  </a>
</div>

<div>
  <a href="https://maps.google.com?saddr=Current+Location&amp;daddr=8 Johnson Street, Owen, WI 54460-9534" hreflang="en">
    Get directions on Google Maps <span class="sr-only">to Clark County VA Clinic</span>
  </a>
</div>
```

### Vet-center page:
![image](https://github.com/department-of-veterans-affairs/content-build/assets/6863534/0c81b152-42f0-404f-b2c8-6140347802b1)
```
<div>
  <a href="https://maps.google.com?saddr=Current+Location&amp;daddr=5139 Deer Park Drive, New Port Richey, FL 34653" id="6f210ebe7570987a9ddc2d906917a874" hreflang="en">
    Get directions on Google Maps <span class="sr-only">to Pasco County Vet Center</span>
  </a>
</div>
```

### Vet-center-locations-list page:
![image](https://github.com/department-of-veterans-affairs/content-build/assets/6863534/e2c5812b-f510-4781-82f8-a08d89f8d26e)
```
<div>
  <a href="https://maps.google.com?saddr=Current+Location&amp;daddr=2114 Ben Craig Drive, Charlotte, NC 28262" id="a61388506e598f2630b759282e3e6c1a" hreflang="en">
    Get directions on Google Maps <span class="sr-only">to Charlotte Vet Center</span>
  </a>
</div>

<div>
  <a href="https://maps.google.com?saddr=Current+Location&amp;daddr=1050 Devore Lane, Matthews, NC 28105" id="680defd2ac8f15bc07ef4aaa3f4b837b" hreflang="en">
    Get directions on Google Maps <span class="sr-only">to Charlotte Vet Center - Matthews</span>
  </a>
</div>
```

## Testing done & QA steps
### VAMC pages
On review instance, visit the following pages, and on each page, follow remaining QA steps:
   - `/black-hills-health-care/locations/fort-meade-va-medical-center/`
   - `/jackson-health-care/`
   - `/tomah-health-care/locations/`
1. - [ ] Validate that all directions links read "Get directions on Google Maps"
2. - [ ] Inspect the directions link and validate that there is an `sr-only` element that includes the facility title
3. - [ ] Inspect the directions link and validate that an address is properly included
4. - [ ] Click the link and ensure you're taken to Google Maps _in the same tab_.

### Vet Center pages
On review instance, visit the following pages, and on each page, follow remaining QA steps:
   - `/pasco-county-vet-center/`
   - `/charlotte-vet-center/locations/`
1. - [ ] Validate that all directions links read "Get directions on Google Maps"
2. - [ ] Inspect the directions link and validate that there is an `sr-only` element that includes the facility title
3. - [ ] Inspect the directions link and validate that an address is properly included
4. - [ ] Click the link and ensure you're taken to Google Maps _in the same tab_.
5. - [ ] Return to previous page and ensure `onclick` handler works to record the click event:
       - Get ready to click the link again, but _immediately_ after clicking the link, hit the `esc` key on your keyboard.
       - In the developer tools console, type `window.dataLayer`.
       - Expand the returned object and ensure there is an object in the array with property: `event: "directions-link-click"`

## Acceptance criteria
See original tickets.

2023-07-07 19:51 UTC, laflannery commented
Noting that for both VAMCs and Vet centers, the nearby locations have directions links that are not following the pattern mentioned in the QA steps. However, these are out of the scope of the original ticket so I'm going to open a separate ticket to be addressed later.

2023-07-10 16:16 UTC, maxx1128 requested changes
This checks out for me and builds appropriately. There's just one minor tweak with the properties.

2023-07-10 16:16 UTC, maxx1128 commented on src/site/layouts/vet_center.drupal.liquid
> +                        directionsLinkOnClickPropValue = title
**Todo:** `directionsLinkTitle` and `directionsLinkOnClickPropValue` look like they should be `entityLabel`.

2023-07-13 16:46 UTC, maxx1128 approved these changes
I made the change I requested feedback on, so for me this is good to merge.

2023-07-18 00:18 UTC, jilladams commented
@ryguyk ok to merge, or do we need to pester 1010 Health Apps folks for review?

2023-07-18 22:05 UTC, jilladams commented
Ryan confirmed he was waiting on Max's review. Merging.

2023-07-18 22:05 UTC, merged

2023-07-19 16:09 UTC, ryguyk commented on src/site/layouts/vet_center.drupal.liquid
> +                        directionsLinkOnClickPropValue = title
Just pointing out that both `title` and `entityLabel` are available from the GraphQL query (and, as such, in the template in question). I chose title to align with the one that was already being used in this template. It'll work with `entityLabel` here, but the change was not necessary.