Added tests for 3 liquid.filter functions
department-of-veterans-affairs/content-build pull request #168
Opened 2021-05-20 16:38 UTC by gescobardev

## Description
Created tests for the following functions:

1. `benefitTerms()`
2. `findCurrentPathDepth()`
3. `hashReference()`

Additionally, I combed through `liquid.js` and found that the following tests are not currently being utilized:

- `humanizeTime()`
- `unixFromDate()`
- `modulo()`
- `breakTerms()`
- `facilityIds()`
- `widgetFacilitiesList()`
- `eventSorter()`
- `getPagerPage()`
- `isPitt()`
- `isPastDate()`

## Acceptance criteria
- [ ] All tests must pass

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-05-20 16:59 UTC, mpelzsherman commented on src/site/filters/liquid.js
> +    if (data === null) return null;
Thanks for adding this! I think it's even better to check for any "falsy" value for data, e.g. `undefined`.
We usually just do `if (!data)` for these sorts of checks. Another option might be to see if `data` has a `toString()` property. EIther way works for me.

2021-05-20 17:10 UTC, gescobardev commented on src/site/filters/liquid.js
> +    if (data === null) return null;
That makes sense and I like `if (!data)`.
I will update

2021-05-20 17:44 UTC, mpelzsherman commented on src/site/filters/liquid.unit.spec.js
> +  });
I prefer to add a space between each test case. Could you add those please? (Sorry, I know it's a pain. 🙏 )

2021-05-20 17:46 UTC, mpelzsherman commented on src/site/filters/liquid.unit.spec.js
> +  });
Does it collapse multiple spaces into one space? Does it matter? Might want to check with @ethanteague ?

2021-05-20 17:47 UTC, mpelzsherman commented on src/site/filters/liquid.unit.spec.js
> +  });
I'm not seeing a happy path test here? How about `foo.txt`? Also try `foo.bar.txt`.

2021-05-20 18:02 UTC, gescobardev commented on src/site/filters/liquid.unit.spec.js
> +  });
No worries! I'll add them

2021-05-21 13:21 UTC, gescobardev commented on src/site/filters/liquid.unit.spec.js
> +  });
Thank you for catching that!
I have now added spacing between tests, removed the list of unused liquid filter functions and added 5 more tests to `fileExt()`

2021-05-21 15:44 UTC, mpelzsherman requested changes
Please add a test for `hashReference` to confirm that it handles multiple spaces correctly.

I think the correct behavior is to condence multiple spaces into a single dash. So:

`"foo<space><space>bar" => "foo-bar"`

Thanks!

2021-05-21 16:51 UTC, gescobardev commented
@mpelzsherman I have added about 4 more tests to `hashReference`

2021-05-21 19:54 UTC, mpelzsherman approved these changes

2021-05-21 19:57 UTC, merged