buttons -> action links on facility and main locations pages
department-of-veterans-affairs/content-build pull request #1708
Opened 2023-09-11 23:20 UTC by eselkin

## Description

closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14928   

## Testing done & Screenshots

Changed the links that looked like buttons in facility health services pages and main buttons to action links.

## QA steps

1. Go to http://localhost:3002/boston-health-care/locations/ and http://localhost:3002/locations/brockton-va-medical-center/
2. Then validate Acceptance Criteria from issue

## Acceptance criteria

- [ ] The top tasks links use the Design component for action links and meet accessibility best practices.
- [ ] Accessibility Lead review

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2023-09-12 20:52 UTC, laflannery approved these changes
Checked all 3 instances, they look good!

2023-09-15 18:31 UTC, maxx1128 requested changes
One small change with the classes, and then this should be good to go.

2023-09-15 18:31 UTC, maxx1128 commented on src/site/facilities/facilities_health_services_buttons.drupal.liquid
> +    <div class="vads-u-margin-y--0">
**Nitpick:** All the `vads-u-margin-y--0` classes on the `div` elements aren't needed since they already have no vertical margin. They can be removed in both files in this pull request.

2023-09-20 15:50 UTC, eselkin commented on src/site/facilities/facilities_health_services_buttons.drupal.liquid
> +    <div class="vads-u-margin-y--0">
removing and testing.

2023-09-20 23:17 UTC, maxx1128 approved these changes
👍

2023-09-21 00:10 UTC, merged