[VA-15424] Add common and official names to Vet Center locations
department-of-veterans-affairs/content-build pull request #1815
Opened 2023-12-01 18:38 UTC by maxx1128

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

Veterans may know and search for their closest Vet Center by a common name, rather than an official name. This shows the common names alongside the official names when available on location listings and location details pages.

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-cms repo_
[department-of-veterans-affairs/va.gov-cms#15424](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15424)

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-12-05 23:10 UTC, jilladams commented
@maxx1128 here, too: this PR autotagged Public Websites for review, but not Facilities. Could you add a line to `codeowners` that will auto-tag Facilities for anything in the vet-centers path? Can be added to this PR, or make a new one, either way.

2023-12-05 23:25 UTC, eselkin requested changes
I'm not seeing the locations change on the review instance
<img width="1507" alt="Screenshot 2023-12-05 at 3 20 35 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/5606931/334b78d9-2793-4d01-896a-b0c0088dc3ac">

2023-12-06 15:45 UTC, maxx1128 commented
@jilladams Just added that change to this repository. It also triggered a rebuild of the demo environment since it said the current was outdated. I will then double-check it since @eselkin noticed the changes weren't there.

2023-12-18 22:22 UTC, eselkin approved these changes
Looks good too me. Not sure why the review instances are so flaky.

2023-12-19 19:36 UTC, maxx1128 commented
Update on the QA criteria:

* I added an extra commit to fix #3.
* #5 already has the logic to show common and official names for the satellite locations. The example in the link has the same common and official name so that it won't show both. Finding another example with different names should show it's working.

I just started building another deploy on my tugboat with the change to confirm it works.

2023-12-19 20:26 UTC, thejordanwood commented
@maxx1128 I have some design notes:

1. On the [Prescott Vet Center main page](https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/prescott-vet-center/): To align with the styling in [the Sketch file](https://sketch.com/s/83e13c18-5a9f-40ed-860f-61b9ead58bd6), can the official name use h4 styling instead?
2. On the [Prescott Vet Center Locations page](https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/prescott-vet-center/locations/): This looks pretty close to the Sketch file, but I think the text needs to be a smaller size to align with the h6 styling that was suggested in the Sketch file.

2023-12-19 20:36 UTC, laflannery commented
@maxx1128 I don't see the official name on the [Prescott locations page](http://e67700abb1e7f21c7d943304b3a52126.review.vetsgov-internal/prescott-vet-center/locations/) and I also only see one name under [Satellite locations on this page](http://e67700abb1e7f21c7d943304b3a52126.review.vetsgov-internal/salt-lake-city-vet-center/locations/) for "Major Brent Taylor Vet Center Outstation"

2023-12-19 21:28 UTC, maxx1128 commented
@thejordanwood I should be able to resize the headings as needed.

@laflannery I checked the two names for "Major Brent Taylor Vet Center Outstation" and they're the same so it won't show two different names. To save time for finding another, I can change the names in the CMS and do another quick rebuild.

2023-12-20 03:59 UTC, maxx1128 commented
@laflannery I can confirm the common and official name logic works with the Satellite locations.

<img width="853" alt="Screen Shot 2023-12-19 at 10 58 38 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/10790736/39fc7612-a05f-46f5-87f9-8b7e231aac06">

2023-12-20 13:00 UTC, maxx1128 commented
@thejordanwood I changed the font sizes and did another build overnight. It should be ready for another round of review.

2023-12-20 13:58 UTC, laflannery commented
@maxx1128 The Brent taylor one I see is correct now however every sattelite location has an `aria-describedby` that is pointed to the Brent Taylor official name, we need to remove that and make sure that:
- Each satellite location points to it's own official name
- A satellite location points to NO official name if it doesn't have one
![Screenshot 2023-12-20 at 8 56 32 AM](https://github.com/department-of-veterans-affairs/content-build/assets/106678594/b0cfbd9f-d3f1-482e-970f-e7ead862698f)

2023-12-20 17:05 UTC, thejordanwood commented
@maxx1128 Thanks for changing the font size! 

I should have clarified more on my first point. On the [Prescott Vet Center main page](https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/prescott-vet-center/), can the official name be a serif font instead of sans serif? This will get it to look like the h4 styling in [the Sketch file](https://sketch.com/s/83e13c18-5a9f-40ed-860f-61b9ead58bd6).

2023-12-20 17:59 UTC, maxx1128 commented
@laflannery @thejordanwood I started another rebuild with changes for all the recent feedback.

2023-12-20 18:47 UTC, thejordanwood commented
@maxx1128 This looks good to me. Thanks for making those changes!

2023-12-21 13:16 UTC, laflannery commented
Satellite locations look good @maxx1128!

2023-12-21 16:39 UTC, eselkin approved these changes
Looks perfect to me.

2023-12-21 16:42 UTC, jilladams approved these changes

2023-12-21 18:05 UTC, ataker approved these changes

2023-12-21 19:04 UTC, jilladams commented
@maxx1128 approved by FE COP, and tests are passing, so I'm gonna merge so we can hit daily deploy. 🤞

2023-12-21 19:04 UTC, merged