VA Police Query and Page Skeleton
department-of-veterans-affairs/content-build pull request #1825
Opened 2023-12-06 17:33 UTC by eselkin

## Summary

- Creates Query for `NodeVamcSystemVaPolice`
- Creates Page skeleton for VA Police 
- Sitewide Facilities
- No flipper

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16278

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-12-15 13:28 UTC, laflannery approved these changes
Approved, but just a reminder that the `<title>` still needs to be updated

2023-12-15 21:46 UTC, maxx1128 requested changes
Overall, this looks really good to me. I just have a few small pieces of feedback.

2023-12-15 21:46 UTC, maxx1128 commented on src/site/layouts/vamc_system_va_police.drupal.liquid
> +                  fieldSectionHeader = policeFeatured.fieldSectionHeader
**Suggestion:** The way this page is structured, it looks like this header should be an `h3` instead of an `h2`. It's technically a sub-category or subsection of "how to contact us," so it would need to be a header level lower. Cc'ing @laflannery for her thoughts on this.

2023-12-15 21:46 UTC, maxx1128 commented on src/site/layouts/vamc_system_va_police.drupal.liquid
> +              <div class="vads-u-margin-bottom--6" id="field-phone-numbers">
**Suggestion (non-blocking):** This is more of a personal preference, but `vads-u-margin-bottom--4` looks like better spacing to me.

2023-12-16 00:42 UTC, eselkin commented on src/site/filters/liquid.js
> +    return processed;
sure, had consoled out in development and forgot to simplify back.

2023-12-16 00:45 UTC, eselkin commented on src/site/layouts/vamc_system_va_police.drupal.liquid
> +                  fieldSectionHeader = policeFeatured.fieldSectionHeader
@laflannery indicated that it couldn't go directly to an h3 before, but it's technically a featured content that may go back to not having that h2 text above (that h2 headed section about contact will go into the facility selected area later, right?)

2023-12-16 00:46 UTC, eselkin commented on src/site/layouts/vamc_system_va_police.drupal.liquid
> +              <div class="vads-u-margin-bottom--6" id="field-phone-numbers">
Sure, 3 was just too small. 6 was even with the spacing below it, but 4 is good as well.

2023-12-16 00:46 UTC, eselkin commented on src/site/layouts/vamc_system_va_police.drupal.liquid
> +              {{ overview }}
done

2023-12-18 13:34 UTC, laflannery commented on src/site/layouts/vamc_system_va_police.drupal.liquid
> +                  fieldSectionHeader = policeFeatured.fieldSectionHeader
@maxx1128 and @eselkin I can definitely see Max's logic here and make a case for the "Police Report" heading being hierarchically a child of "How to contact", I can also make a case for it being a sibling as well so either way is acceptable. Thinking future state however, when this moves into MVP and beyond, the Contact section is going to be moved down and the featured block will be the first heading after the H1 - which bring us back to Eli's point - that this heading cannot be an H3. To make things easier when moving to MVP and to stay more consistent for the user experience going forward, keeping this an H2 would be my choice.

2023-12-18 17:33 UTC, maxx1128 approved these changes
👍

2023-12-19 15:19 UTC, harshil1793 approved these changes

2023-12-19 17:11 UTC, chriskim2311 approved these changes
LGTM

2023-12-19 18:53 UTC, merged