Codeowner updates for Facilities/PW ownership in layouts/tests folders
department-of-veterans-affairs/content-build pull request #1840
Opened 2023-12-21 20:52 UTC by jilladams

This started bc I realized that the va_police layout wasn't set for Facilities as codeowner. Give a mouse a cookie. 🐭 🍪 

Done: 
* Specified which layouts for which products belong to PW vs. Fac. That will be useful as AP team moves forward, for knowing who to coordinate with about what.
* Specified Test folders that are owned by Facilities.
* Grouped Facilities-owned items into product buckets (VAMC/VBA/Vet Centers)
* Added @department-of-veterans-affairs/ap-admins as codeowners of Events, so they'll get notified of any changes to the Events liquid template. Can remove this once PW owns the Next implementation and we have a path to Prod. 

Didn't do: Anything else, including but not limited to: 
* paragraphs
* navigation
* includes that aren't in a subfolder
* blocks

Looking at those helped me realize I was a mouse with a cookie. I'm interested in whether reviewers think the changes I _did_ make are at all useful / should merge, or create a burden and it's easier just to leave things co-owned and let everyone get the PR noise and decide where they want to / should weigh in. 

## Why do I care
1. PR noise. It's nice to get notified where you're needed, instead of everywhere every time.
2. Expedient reviews: less noise means the people who need to actually review will take the time to do so more readily.
3. Growing contributor base: for example, the IIR team will soon join in on the fun. We need to be able to spell out ownership in here, as easily as we do in vets-website.

And maybe a note to @timcosgrove that it would be so cool if it were easy to establish full codeownership of features / related files in Next. I don't know if that's real, but: consider it a request to consider.

2023-12-21 21:05 UTC, randimays approved these changes
LGTM. Agree 100% with reducing PR noise. Thanks Jill!

2024-01-04 00:29 UTC, timcosgrove approved these changes
I think this is fine. It may remove ownership from the primary teams up top, but if it does we can rectify that later.

2024-01-05 17:08 UTC, CBonade requested changes

2024-01-05 17:08 UTC, CBonade commented on .github/CODEOWNERS
> +src/site/layouts/event* @department-of-veterans-affairs/vfs-public-websites-frontend @department-of-veterans-affairs/ap-admins
It looks like one of the groups added here is flagged as not existing

2024-01-08 17:50 UTC, jilladams commented
@department-of-veterans-affairs/ap-admins definitely exists. @timcosgrove or @tjheffner I think you both probably have repo level permissions. Could you add @ap-admins as a content-build contributor, here: https://github.com/department-of-veterans-affairs/content-build/settings/access.  I don't have perms to do that. Or: if @accelerated-publishing is already added, I could change the codeowner line to use that group instead. (I chose @ap-admins bc it's a smaller set of folks who actually need the code change awareness, vs. the bigger group with administrative interest but who wouldn't need to do actual code reviews.)

2024-01-08 22:10 UTC, eselkin approved these changes
Looks good to me as long as the group gets added.

2024-01-10 00:01 UTC, tjheffner commented
I've added the `@ap-admins` team to this repo.

2024-01-10 00:01 UTC, tjheffner approved these changes
![Screenshot 2024-01-09 at 4 01 32 PM](https://github.com/department-of-veterans-affairs/content-build/assets/11279744/3414990a-0d66-45dd-a2c6-3bcdf58660cd)

2024-01-10 00:02 UTC, merged