Vacms 14936 vba service location paragraph testing new
department-of-veterans-affairs/content-build pull request #1898
Opened 2024-02-02 23:52 UTC by eselkin

## Summary

- Updates [va-14957](https://github.com/department-of-veterans-affairs/content-build/pull/1880) to handle facilityService and regionalService representing the same service.
- Tests services liquid (Service Location paragraph)
- Sitewide Facilities

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14936

## Testing done

- Created unit tests for VBA service locations
- Updating testing for liquid filters

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

<details>
<summary>Desktop Max's tugboat content</summary>
</details>

<details>
<summary>Desktop Eli's tugboat content (with regional service and facility service with same name)</summary>
![screencapture-localhost-3002-cleveland-va-regional-benefit-office-locations-cleveland-va-regional-benefit-office-2024-02-02-14_42_39](https://github.com/department-of-veterans-affairs/content-build/assets/5606931/16a12f05-8ae1-4315-b5db-ecbafe1602ca)
</details>

<details>
<summary>Mobile Max's tugboat content</summary>
![screencapture-localhost-3002-cleveland-va-regional-benefit-office-locations-cleveland-va-regional-benefit-office-2024-02-02-15_37_51](https://github.com/department-of-veterans-affairs/content-build/assets/5606931/dc3ee32f-a4a5-4f80-af16-4f4d2fd27d0b)
</details>

## What areas of the site does it impact?

Affects VBA facility pages.

## Acceptance criteria

Testing done for trimAndCamelCase, regional and facility service consolidation, components of VBA facility regional sections

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-02-03 00:17 UTC, eselkin commented on src/site/tests/vba/vba.unit.spec.js
> +/* eslint-disable @department-of-veterans-affairs/axe-check-required */
Not a cypress test, cannot include this axe check

2024-02-03 00:19 UTC, eselkin commented on src/site/filters/liquid.unit.spec.js
> +    for (let i = 0; i < 7; i += 1) {
These come up as complaints by the linter

2024-02-03 00:19 UTC, eselkin commented on src/site/filters/liquid.unit.spec.js
> +    for (let i = 0; i < 7; i += 1) {
Linting complaints

2024-02-06 22:45 UTC, maxx1128 requested changes
This code looks good overall and the tests are passing. I only found one small blocking change and a few suggestions for how the code is organized.

2024-02-06 22:45 UTC, maxx1128 commented on src/site/filters/liquid.js
> +    }
**Suggestion:** It looks like there is some repeated code between offices and service regions. Something like the below code would shorten the function and make the code more DRY. But you understand the code better, so I don't think it's a blocking change.

```javascript
function sortVbaServices(vbaServices, type) {
  vbaServices.forEach(vbaService => {
    if (
      vbaService?.fieldvbaServiceNameAndDescripti?.entity
        ?.fieldShowForVbaFacilities
    ) {
      const {
        fieldVbaTypeOfCare,
      } = vbaService.fieldServiceNameAndDescripti.entity;

      const key = liquid.filters.trimAndCamelCase(
        'vba_',
        fieldVbaTypeOfCare,
      );

      if (type === 'serviceRegions') {
        const indexOfFacilityService = accordions[key].findIndex(
          service =>
            service.facilityService?.fieldServiceNameAndDescripti.entity
              .name === name,
        );
        if (indexOfFacilityService !== -1) {
          accordions[key][
            indexOfFacilityService
          ].regionalService = vbaService;
        } else {
          accordions[key].push({
            regionalService: vbaService,
          });
        }
      } else {
        accordions[key].push({
          facilityService: vbaService,
        });
      }
    }
  });
}

if (hasOffices) {
  sortVbaServices(offices, 'offices');
}

if (hasServiceRegions) {
  sortVbaServices(offices, 'serviceRegions');
}
```

2024-02-06 22:45 UTC, maxx1128 commented on src/site/filters/liquid.unit.spec.js
> +  expect(allVbaServices.familyMemberCaregiverBenefits.length).to.equal(1);
**Praise:** Thank you for catching this mislabeling from my pull request 😅

2024-02-06 22:45 UTC, maxx1128 commented on src/site/includes/vba_facilities/service_location.liquid
> +      {% endif %}
**Todo:** The indentations this code had in `src/site/includes/vba_facilities/services.liquid` got lost in the transition. They should be added back before they get merged to preserve readability.

2024-02-06 22:45 UTC, maxx1128 commented on src/site/includes/vba_facilities/services.liquid
> +        {% if entity.facilityService %}
**Suggestion:** These are a lot of variable assignments to mix into a template file. Lines 9-52 could be extracted into their own partial with a name like `service_variables.liquid`. Everything should carry over in this template, so nothing more needs to be passed into `service_location.liquid`.

2024-02-06 22:45 UTC, maxx1128 commented on src/site/tests/vba/vba.unit.spec.js
> +describe('VBA accordions for Service Locations', () => {
**Praise:** Love the way these tests are written 🎆

2024-02-06 22:48 UTC, eselkin commented on src/site/filters/liquid.js
> +    }
Could do that. Just one more thing that needs to add a test for 😄

2024-02-06 22:48 UTC, eselkin commented on src/site/includes/vba_facilities/service_location.liquid
> +      {% endif %}
Yeah. Will do that.

2024-02-06 22:49 UTC, eselkin commented on src/site/includes/vba_facilities/service_location.liquid
> +      {% endif %}
I turned off the auto-formatter because it was making includes into single lines.

2024-02-06 23:58 UTC, eselkin commented on src/site/includes/vba_facilities/services.liquid
> +        {% if entity.facilityService %}
Evidently you can't do this. I tried just creating a liquid template just of assignments and it didn't work. The variables don't extend at a sibling level, just at a child level.

2024-02-07 00:00 UTC, eselkin commented on src/site/includes/vba_facilities/service_location.liquid
> +      {% endif %}
Fixed

2024-02-07 00:01 UTC, eselkin commented on src/site/filters/liquid.js
> +    }
refactored

2024-02-08 14:57 UTC, IGallupSoCo approved these changes
LGTM

2024-02-08 21:53 UTC, merged