Vacms 16144 VAMC service location paragraphs - and merge VBA
department-of-veterans-affairs/content-build pull request #1912
Opened 2024-02-13 08:25 UTC by eselkin

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16144

## Testing done

- VAMC service locations were just inline with the accordions but the paragraphs were difficult to parse and now more information is added to the paragraph types (including appointment info, etc). 
- VAMC still render as do VBA facilities for regional and facility services

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-02-15 07:04 UTC, eselkin commented on src/site/paragraphs/tests/vamc/vamc_field_service_location.unit.spec.js
> +/* eslint-disable @department-of-veterans-affairs/axe-check-required */
Not a cypress test

2024-02-16 20:40 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +        <i class="fas fa-building vads-u-margin-right--0p5"></i>
Requested by design

2024-02-16 20:40 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +      <p>
Requested by design

2024-02-16 20:40 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +          {% when "1","2" %}
Requested by design

2024-02-16 20:40 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +          {% when "not_applicable","0" %}
Requested by design

2024-02-16 20:40 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +        <i class="fas fa-calendar vads-u-margin-right--0p5"></i> Schedule a virtual appointment
Requested by design

2024-02-16 20:40 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +          {% when "1","2" %}
Requested by design

2024-02-16 21:07 UTC, eselkin commented
@davidmpickett There's a concern I had when displaying the Appointments header. Certain service location paragraphs like the Emergency care department at the DC VAMC facility show `"fieldOfficeVisits": "yes_with_or_without_appointment"` which doesn't make sense but because they do it shows the Appointments header.

Also certain facilities show the appointments header because of the above issue but have no Appointments context within the section. Like no custom text even though they selected "customize_text". I'm wondering if we need a more complex condition on whether to show Appointments. Like all the conditions of your matrix plus whether customize text is selected and if there's actually text or if use_default_text is selected.

2024-02-16 21:26 UTC, eselkin commented
@laflannery thanks for your fast feedback. 

The i tags will be updated. 

I was working on the conditional heading level stuff. I must have left it out in the commit. The VAMC accordions are awash with weird liquid stuff. Will fix. 

I can update the non-clinical services that don't have accordions in this PR.

2024-02-17 00:55 UTC, eselkin commented
@laflannery I misinterpreted what you were saying when I first re-looked at this. The facility name (that has a link) should be in an h4 but the sections in the card/box should be at h5 level? I think that's what you're saying. We should double check that also works on other non-clinical pages. I'll link some later.

2024-02-17 05:30 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +        <i class="fas fa-building vads-u-margin-right--0p5" aria-hidden="true"></i>
requested in design

2024-02-17 05:30 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +            <i class="fas fa-check-circle vads-u-margin-right--0p5" aria-hidden="true"></i> A referral is required
requested in design

2024-02-17 05:30 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +            <i class="fas fa-times-circle vads-u-margin-right--0p5" aria-hidden="true"></i> A referral is not required
requested in deisn

2024-02-17 05:31 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +        <i class="fas fa-calendar vads-u-margin-right--0p5" aria-hidden="true"></i> Schedule a virtual appointment
requested in design

2024-02-19 17:23 UTC, thejordanwood commented
@eselkin I have some notes on some spacing inconsistencies. If the way I worded any of this is confusing then we can meet up to discuss if that works better. 

<details>
<summary>Desktop non-clinical</summary>

1. The spacing between the top and bottom of the card should be the same. The design has these at 16px, which I think is closer to what you have for the bottom spacing here. 

<img src="https://github.com/department-of-veterans-affairs/content-build/assets/104526584/f813465f-5680-4131-882b-396d3a72a48d">
</details>

<details>
<summary>Desktop clinical</summary>

1. The "Nurse advice line" heading should be closer to the Main Phone section. It should have the same spacing as Main Phone does to the Appointments section.
<img src="https://github.com/department-of-veterans-affairs/content-build/assets/104526584/028756f8-e7ee-4c0e-a68b-476de8609f5e">

2. Spacing below the Main Phone section is too big here as well. It should have the same spacing as the top. 
<img src="https://github.com/department-of-veterans-affairs/content-build/assets/104526584/29e8cfa1-4461-435e-803d-03d3c0781a34">

3. Can the spacing between the CTA and Audiology and Speech Clinic section be the same as the spacing between the CTA and Appointments section?
<img src="https://github.com/department-of-veterans-affairs/content-build/assets/104526584/290f5e99-d7a7-4215-99bd-b2763940d24a">

4. The spacing between the Main Phone section and Service Hours is a bit big here too. Also, the sentence "The service hours are the same..." has too much space from the Service Hours heading. It should be the same spacing as the phone number is to the Main Phone heading here. 
<img src="https://github.com/department-of-veterans-affairs/content-build/assets/104526584/06362fee-6733-4759-809d-7e180e85b832">
</details>

<details>
<summary>Desktop VBA</summary>

1. Spacing looks pretty good overall. Only minor thing I see is the sentence "The service hours are the same..." and Service Hours heading should be closer together. 
<img src="https://github.com/department-of-veterans-affairs/content-build/assets/104526584/c92a3382-1cbb-4a7b-bfb3-cf0e598095f0">


</details>

2024-02-19 18:54 UTC, eselkin commented
@thejordanwood The problem with the spacing is that sometimes some sections appear and sometimes they don't because of the data. I'll work to see if we can make some sort of indicator for prior paragraphs. When we make test data we're always guaranteed that the data exists so it looks good like with VBA. But in the real data it's a little more chaotic.

2024-02-19 19:23 UTC, thejordanwood commented
@eselkin I had a feeling that was probably the case. Thanks for looking into it!

2024-02-19 22:37 UTC, davidmpickett commented
> @davidmpickett There's a concern I had when displaying the Appointments header. Certain service location paragraphs like the Emergency care department at the DC VAMC facility show `"fieldOfficeVisits": "yes_with_or_without_appointment"` which doesn't make sense but because they do it shows the Appointments header.
> 
> Also certain services show the appointments header because of the above issue but have no Appointments context within the section. Like no custom text even though they selected "customize_text". I'm wondering if we need a more complex condition on whether to show Appointments. Like all the conditions of your matrix plus whether customize text is selected and if there's actually text or if use_default_text is selected.

I might have been misinterpreting your original question. The matrix logic I mapped out applies to the Appointments Information as a whole. So appointment Header, intro text, appointment phone, online scheduling available. 

![Appointments](https://github.com/department-of-veterans-affairs/content-build/assets/51967950/16c0dd50-4040-4069-bfea-7b32728eed21)

In the 4 scenarios where an editor has indicated that appointments don't apply to this service location then none of the appointment information should display. All of it should be hidden. 

![Logic for displaying Appointment Info on Front End](https://github.com/department-of-veterans-affairs/content-build/assets/51967950/02f13704-ff65-421f-a4e8-bceb0235d03c)

However, in the 12 scenarios in which appointments are a possibility, then each of the individual items should have it's own logic:
-  Online scheduleing link only shows if online scheduling set to true
- Appointment phone number(s) show if populated (it's possible to unselect use facility phone and not add any phone numbers)
- Appointment text should show if default or custom is selected (plus guard against empties)
- Appointment header should show if default or custom is selected (plus guard against empties)?

I'm still conflicted about the logic for removing appointment header. It is functioning as a pseudo-semantic element where it contextualizes the text, the phone number, and the link. So for instance if appointments are possible, but an editor chooses to remove the lead in text (or enters empty custom text) but still adds a phone number for appointments, but doesn't label that phone number as being for appointments we basically are choosing between two bad options. A header with no content under it or a phone number that doesn't give the user enough info to understand it's purpose 

![Service Location 1](https://github.com/department-of-veterans-affairs/content-build/assets/51967950/a25d19cb-0763-4857-9ee8-d5b887d5e7d2)

![Service Location 2](https://github.com/department-of-veterans-affairs/content-build/assets/51967950/80848c94-4f01-4dd3-b725-d7e52e9bcbd2)

Not sure if I cleared anything up, or just added to the confusion.

2024-02-19 22:46 UTC, davidmpickett commented
> * The h5 headings within the Service accordions need to be conditional. If you look at [the Sketch](https://www.sketch.com/s/8bda90fd-99e8-4761-9210-3a24282eb811) It has "Optional service location title" assigned as the h4. However, because this is optional, it means the heading structure in Sketch is only applicable **IF** that title is present. You can see this as correct on the [VBA service accordions](https://web-pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/). If the optional title is not present though, then all the h5s indicated in Sketch need to be h4s. You can see that currently on the [VAMC service accordions](https://web-pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/washington-dc-health-care/locations/washington-va-medical-center/) there is an incorrect heading structure because the h4 level is being skipped.
> * This might be out of scope so if it is, I can ticket it separately:

So we currently don't have any data/content model to support the "optional service location title" for VAMC services health or non-clinical). We probably shouldn't be building with an expectation of it being present until we at least have a plan for what the data source would be. This is likely a vestige of the VAMC accordion being based on the VBA accordion design, but somehow this slipped past the Refinement process

2024-02-20 16:02 UTC, eselkin commented
> > * The h5 headings within the Service accordions need to be conditional. If you look at [the Sketch](https://www.sketch.com/s/8bda90fd-99e8-4761-9210-3a24282eb811) It has "Optional service location title" assigned as the h4. However, because this is optional, it means the heading structure in Sketch is only applicable **IF** that title is present. You can see this as correct on the [VBA service accordions](https://web-pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/). If the optional title is not present though, then all the h5s indicated in Sketch need to be h4s. You can see that currently on the [VAMC service accordions](https://web-pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/washington-dc-health-care/locations/washington-va-medical-center/) there is an incorrect heading structure because the h4 level is being skipped.
> > * This might be out of scope so if it is, I can ticket it separately:
> 
> So we currently don't have any data/content model to support the "optional service location title" for VAMC services health or non-clinical). We probably shouldn't be building with an expectation of it being present until we at least have a plan for what the data source would be. This is likely a vestige of the VAMC accordion being based on the VBA accordion design, but somehow this slipped past the Refinement process

I think it's alright if it doesn't exist. The service location title/name @laflannery was talking about was outside the box not something inside the box there.

2024-02-23 14:53 UTC, laflannery commented
@eselkin I took another look at the headings and on the [VAMC Clinical page](https://web-pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/washington-dc-health-care/locations/washington-va-medical-center/) I think there was a case that wasn't accounted for or wasn't clearly labelled in the Sketch designs.

There are phone numbers being added in the appointment section in Drupal and these numbers need to remain close to the "Appointments" heading in the new display so it is clear why a person would use this number. Here's an example of the new confusing scenario I'm looking at:
![image](https://github.com/department-of-veterans-affairs/content-build/assets/106678594/5c81d8fa-d97d-425d-aa72-97f58565de26)

- The H5 Geriatric Service is actually for appointments:
![image](https://github.com/department-of-veterans-affairs/content-build/assets/106678594/bce8c85a-62ac-4d27-8118-2be891200904)
- The H4 Geriatric Service and the Main Phone have been indicated in the general Contact Info
![image](https://github.com/department-of-veterans-affairs/content-build/assets/106678594/aeabd91d-92ad-45a1-a751-320481faa138)

**Looking at the Sketch and the information provided I would recommend the following:**
- H4 "Appointments"
  - H5 Specific Appointments Phone label
    - Specific Appointments Phone number
  - Secondary CTA to Schedule an appointment
- H4 Specific Address label
  - Address info
- H4 "Main Phone"
  - Phone number
- H4 Specific Contact phone label
  - Specific Contact phone number
- H4 Specific Contact email label
  - Specific Contact email address
- H4 Specific Hours label
  - Hours info

@davidmpickett and/or @thejordanwood to also weight in

2024-02-25 20:52 UTC, davidmpickett commented
> **Looking at the Sketch and the information provided I would recommend the following:**
> 
> * H4 "Appointments"
>   
>   * H5 Specific Appointments Phone label
>     
>     * Specific Appointments Phone number
>   * Secondary CTA to Schedule an appointment
> @davidmpickett and/or @thejordanwood to also weight in

I do think that @laflannery's suggestion of changing the semantics of the Appointments section makes sense. This could also help with some of the confusing logic of when to hide or show the Appointments header that I responded to above. But I also want to call out that these might qualify as product decisions, and/or be out of scope. 

Flagging @xiongjaneg @jilladams for un-blocking / scope assessment

2024-02-26 05:39 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +            <i class="fas fa-building vads-u-margin-right--0p5" aria-hidden="true"></i>
required by design

2024-02-26 05:39 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +            <i class="fas fa-calendar vads-u-margin-right--0p5" aria-hidden="true"></i> Schedule a virtual appointment
required by design

2024-02-26 05:39 UTC, eselkin commented on src/site/paragraphs/service_location.drupal.liquid
> +              <i class="fas fa-times-circle vads-u-margin-right--0p5" aria-hidden="true"></i> A referral is not required
required by design

2024-02-26 05:43 UTC, eselkin commented
@laflannery I think I can pull up that 2nd geriatric up under appointments. It's odd and a bug that it's an h5 in there now, but it works for your updated organization.

Re @davidmpickett's comment I will wait on suggestions from @jilladams  and @xiongjaneg and will keep working on merging in the conflicts from the MH phone number stuff from Max.

2024-02-26 15:19 UTC, davidmpickett commented
While poking around, I noticed a few other things

**Requested change to content:**
- When by appointment only is selected, the displayed text should be "Visit our office, ~~with an~~ by appointment only"

**Not matching the design**
- The accordions should be the borderless variant.
![Screenshot 2024-02-26 090149](https://github.com/department-of-veterans-affairs/content-build/assets/51967950/b865b946-986e-46fe-abbf-c5c9a8e2e518)

**This isn't good, but I don't know how to fix it**

- If an editor has entered `building name/number` or `wing, floor or room number`, but not `Service location address` this information now will be floating around without context. Vs on Prod, this information would default to falling under the generic **Contact Info** header

![Screenshot 2024-02-26 091548](https://github.com/department-of-veterans-affairs/content-build/assets/51967950/0b435df2-2a98-45fe-b363-b8b2142d3c96)

![Screenshot 2024-02-26 091407](https://github.com/department-of-veterans-affairs/content-build/assets/51967950/814d1768-987b-4e2b-977b-128dc5ed79a4)

![Screenshot 2024-02-26 091428](https://github.com/department-of-veterans-affairs/content-build/assets/51967950/c67f3e1a-53f3-418c-a027-ef49aee3468d)

2024-02-26 17:29 UTC, aklausmeier commented
@thejordanwood Can you confirm if accordions should have a border like the VBA RO designs? 

(below, pulled Dave's comment above)

> Not matching the design
> 
> The accordions should be the borderless variant.

2024-02-26 17:33 UTC, jilladams commented
We chatted about Laura's a11y feedback notes in scrum this morning. There are 2 pieces: 

1. **Appt phone number needs to be right after Appt header.** Agreed, and we want to handle this in this PR.

2. **Header level:** Semantically changing header levels doesn’t fit in the current ticket but makes sense and is a good idea. 
  * To get it done: Needs design review, signoff, and Sketch update 
  * Jordan would like to keep this out of current PR, to make sure we take a bigger look and don’t miss other tweaks we need

I'm working today on scheduling a bigger design/FE call to review the situation with service location accordions across VBA, VAMC, VA Police, (which @laflannery will be invited to) so we can touch on #2 in that meeting as well. (Scrum notes in Trello for reference: https://trello.com/c/jDLQgJ8m/385-service-location-accordions-numbers-spacing)

2024-02-26 18:16 UTC, thejordanwood commented
@davidmpickett After some discussion with @aklausmeier, we've decided that VBA accordions should also have borders to stay consistent with the accordions on VAMC pages. 

@eselkin Can borders be added to the VBA pages?

2024-02-26 20:26 UTC, eselkin commented
@thejordanwood Yes, VBA pages can have borders on the accordion items. I think you mean the gray (? colorblind) borders. Right?

2024-02-26 20:34 UTC, eselkin commented
@davidmpickett 

> While poking around, I noticed a few other things
> 
> **Requested change to content:**
> 
> * When by appointment only is selected, the displayed text should be "Visit our office, ~with an~ by appointment only"
> 
**Changed**

> **Not matching the design**
> 
> * The accordions should be the borderless variant.

**Changing VBA to bordered as well**

> 
> **This isn't good, but I don't know how to fix it**
> 
> * If an editor has entered `building name/number` or `wing, floor or room number`, but not `Service location address` this information now will be floating around without context. Vs on Prod, this information would default to falling under the generic **Contact Info** header
> 
Right now if there's no clinic name but there is subsequent data, we could default to something like:
`Location Info`
In the header space for that section.

2024-02-26 21:29 UTC, thejordanwood commented
@eselkin Yes, I meant the gray borders. Here's [an example of the bordered accordions](https://design.va.gov/components/accordion#bordered) in the design system. Thanks!

2024-02-27 00:22 UTC, eselkin commented
@thejordanwood finally got the borders on VBA. It had bordered on the va-accordion but it's the items that also need that attribute, but the design website doesn't specify it. It should be up in an hour on https://web-pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/

So, tomorrow.

2024-02-28 14:10 UTC, laflannery approved these changes
Approved!

2024-02-28 16:58 UTC, thejordanwood commented
Approved by me!

2024-02-28 16:58 UTC, thejordanwood approved these changes

2024-03-01 15:05 UTC, Andrew565 commented
PR has failing required tests, opting not to review at this time. - Tier 2/FE COP

2024-03-01 18:27 UTC, eselkin commented
@Andrew565 It's going to have failing tests until CMS has merged in the Service Location Paragraphs from their PR/integration branch.

2024-05-10 15:35 UTC, jilladams commented
@maxx1128 : reminder re: review and I'm going to go ahead and ping Platform FE just for safety, since this needs to merge by EOD Monday if the CMS deploy goes well.

2024-05-10 15:36 UTC, jilladams commented
@eselkin actually: should I wait til CI is passing?

2024-05-10 15:37 UTC, eselkin commented
Platform likes to review only after tests pass, but since this is dependent on CMS merging SL it's probably ok to ping them now.

2024-05-10 15:39 UTC, jilladams commented
ugh right, I keep forgetting that. Thank you!

2024-05-10 21:37 UTC, harshil1793 approved these changes

2024-05-13 16:19 UTC, maxx1128 requested changes
One small concern to address before I think it's good.

2024-05-13 17:57 UTC, eselkin commented on src/site/facilities/service_address.drupal.liquid
> +{% endif %}
ok, will add that

2024-05-13 17:59 UTC, eselkin commented on src/site/facilities/service_address.drupal.liquid
> +{% endif %}
Changed

2024-05-13 23:33 UTC, maxx1128 approved these changes

2024-05-14 17:37 UTC, merged