16986 Resources & Support taxonomy pages pagination
department-of-veterans-affairs/content-build pull request #1941
Opened 2024-03-01 20:23 UTC by randimays

## Summary
Upgrade the custom pagination code with the v3 pagination design system web component. This required creating a `script` for adding the `pageSelect` event handler and using `localStorage` to store the current page number since pagination on static pages requires a full page reload when navigating.

This pagination template is used on Resources & Support taxonomy, story listings and press release pages.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17199

## Testing done
Tested these URLs locally:

- `/resources/va-account-and-profile`
- `/north-texas-health-care/stories`
- `/clarksburg-health-care/news-releases/` (one page only)
- `/sheridan-health-care/news-releases/`

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?
Resources & support taxonomy pages, news releases and story lists.

## Acceptance criteria
 - [x] Pagination uses V3
 - [x] other features display correctly
 - [x] verify/review the E2E tests
 - [x] check desktop and mobile
 - [ ] a11y review

2024-03-05 15:59 UTC, randimays commented
@chriskim2311 @laflannery This is ready for your review please!

2024-03-05 16:49 UTC, laflannery commented
@randimays Can we make the "Go to all articles" taxonomy page link use the `active` prop? This will make them a bit closer to the current design and differentiate them from the other detail page links in the lists:
![Screenshot 2024-03-05 at 11 47 08 AM](https://github.com/department-of-veterans-affairs/content-build/assets/106678594/9682e0c5-895d-4edd-987f-5dd600679ade)

Otherwise, everything else looks good!

2024-03-05 23:03 UTC, maxx1128 requested changes
This is close, but I found a few blocking bugs while testing it on a few pages.

2024-03-05 23:03 UTC, maxx1128 commented on src/site/includes/pagination.drupal.liquid
> +    pagination.setAttribute('page', currentPage);
**Bug (blocking):** This works but is leaking over to other pages. If I go to `http://8d6f2582491bf122dc332524c18ae7b3.review.vetsgov-internal/resources/va-account-and-profile/` and click on page 2 of the pagination and then go to `http://8d6f2582491bf122dc332524c18ae7b3.review.vetsgov-internal/sheridan-health-care/news-releases/`, it goes to the first page but the second pagination link is active. So, `currentPage` needs to distinguish between the pagination locations in different URLs for where the current page is.

<img width="836" alt="Screen Shot 2024-03-05 at 5 58 49 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/10790736/9f4041b6-fc0f-49ce-be91-e7c1c464559a">

2024-03-05 23:03 UTC, maxx1128 commented on src/site/includes/README-pagination.md
> +# Pagination in Drupal static pages
**Praise:** 👏 for writing the documentation; it made this pull request review _so much_ smoother.

2024-03-06 14:57 UTC, randimays commented
Thanks so much for testing, @maxx1128! I'll get to work on those defects.

2024-03-06 16:51 UTC, Andrew565 commented
PR has requested changes pending, opting not to review at this time. - Tier 2/FE CoP

2024-03-11 20:45 UTC, randimays commented
@maxx1128 @laflannery @chriskim2311 This is ready for your review please!

2024-03-12 09:21 UTC, chriskim2311 commented on src/site/includes/pagination.drupal.liquid
> +  <script>
Great work and nice solution w/ docs . Glad you got it to work!

2024-03-12 09:22 UTC, chriskim2311 approved these changes
LGTM great work! Tested in review instance

2024-03-12 16:27 UTC, laflannery commented
@randimays I am now clear that this covered Stories ( I didn't realize before) and I tested [Boston Stories](http://369ed02e98ebfc26082bf788fd2f23a3.review.vetsgov-internal/boston-health-care/stories/) because there are multiple pages. However, Page 2 doesn't work, it goes to here: http://369ed02e98ebfc26082bf788fd2f23a3.review.vetsgov-internal/[object%20Object]/2

2024-03-12 17:21 UTC, maxx1128 approved these changes
The pages are working as expected, this looks great!

2024-03-12 21:07 UTC, ataker approved these changes

2024-03-12 21:07 UTC, merged