VACMS-17178: Update CLP Links to V3 components
department-of-veterans-affairs/content-build pull request #1943
Opened 2024-03-05 18:43 UTC by chriskim2311

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary
Update CLP links to use V3 components

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17178

## Testing done
Tested locally

## Screenshots

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-03-11 19:19 UTC, chriskim2311 commented on src/site/layouts/campaign_landing_page.drupal.liquid
> +                Download (PDF)
Thanks, re-read your comment about pdf downloads and misunderstood thought it was for all pdf downloads. I will add the va-link here.

2024-03-11 19:31 UTC, randimays commented on src/site/layouts/campaign_landing_page.drupal.liquid
> +                Download (PDF)
Oh, thank you for reminding me about that! You're right - you interpreted the comment about PDF downloads correctly. This should **not** be using a `<va-link>`. Apologies for the confusion!

2024-03-11 19:33 UTC, chriskim2311 commented on src/site/layouts/campaign_landing_page.drupal.liquid
> +                Download (PDF)
Got it thanks for the sanity check here!

2024-03-12 20:43 UTC, chriskim2311 commented
@randimays I addressed the missing pieces from your comments. The accordion bug has been ticketed with DST and they will resolve the issue.

2024-03-12 20:55 UTC, randimays requested changes

2024-03-12 20:55 UTC, randimays commented on src/site/layouts/campaign_landing_page.drupal.liquid
> +                  <va-link
This needs to be wrapped in the `h3` for semantics and style, please! Ours vs prod:

<img width="1032" alt="Screenshot 2024-03-12 at 3 49 34 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/c23ae6ae-9e7d-4342-a5b0-6838f19a65a7">
<img width="909" alt="Screenshot 2024-03-12 at 3 49 30 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/22ff6245-df36-4c18-9f4f-ecdc539dfb7b">

2024-03-12 21:09 UTC, laflannery commented
@chriskim2311 I have 1 update and 2 questions:
- Actual update: You can remove `role="presentation"` from the icons (social links at the top and Benefits at the bottom) because you already have `aria-hidden`.
- The social links open in a new window, how did you do this? I can't see anything in the code that is making this happen (e.g. target="_blank") and we were pretty sure the link component didn't allow this
- This is the only ticket so far we've updated the Feedback button - I think I was under the impression this was more of a overall sitewide update, not a template by template thing? I do not want an aria-label here (I know that there currently is one), would that be my decision to make? Or is that a larger decision, do we know?

2024-03-12 21:26 UTC, jamigibbs commented
> There's also a bug with accordions on CLPs. When you hover over the button, the hovered plus icon gets small and thinner. If possible, could we fix this as part of this PR as well?

@chriskim2311 @randimays Just a head's up that we have recently fixed the issue of the accordion icons resizing on hover. That update will be in the next component-library release:

- https://github.com/department-of-veterans-affairs/component-library/pull/1083

2024-03-14 20:56 UTC, randimays commented on src/site/layouts/campaign_landing_page.drupal.liquid
> +                  <va-link
@chriskim2311 I think we lost some styles here controlling the look of the `<h3>`

<img width="617" alt="Screenshot 2024-03-14 at 3 55 47 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/7900ffbd-0f78-4505-b54c-333aba4779ea">

2024-03-15 17:32 UTC, randimays approved these changes
LGTM!

2024-03-15 17:42 UTC, laflannery commented
Looks good, thanks!

2024-03-18 18:38 UTC, merged