Lovell TRICARE pages now present MHS site when cerner/cerner_staged
department-of-veterans-affairs/content-build pull request #1945
Opened 2024-03-06 00:28 UTC by eselkin

## Summary

- Pages with fieldAdministration of Lovell TRICARE now show MHS Genesis Patient Portal link instead of link to Make an appointment page. Things remain the same for Lovell VA and Lovell Federal pages (Program pages except ones that have Lovell TRICARE as fieldAdministration)
- Sitewide Facilities

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17299
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17416

## Testing done

- Top task link to Make an appointment was visible on all Lovell TRICARE pages
- Checked all pages as Lovell TRICARE user in staging/localhost build and vagovprod build

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |     ![Screenshot 2024-03-05 at 4 14 01 PM](https://github.com/department-of-veterans-affairs/content-build/assets/5606931/9e1e4ed5-b6ca-497f-9337-ae47f7917135)   |     ![Screenshot 2024-03-05 at 4 13 41 PM](https://github.com/department-of-veterans-affairs/content-build/assets/5606931/afe41ec7-cf79-463d-84ec-8f35b730f721)  |
| Desktop |    ![Screenshot 2024-03-05 at 4 14 59 PM](https://github.com/department-of-veterans-affairs/content-build/assets/5606931/7abb3412-5545-4773-9d3c-508f6f074098)    |    ![Screenshot 2024-03-05 at 4 13 31 PM](https://github.com/department-of-veterans-affairs/content-build/assets/5606931/cce7e6ac-31f6-4931-8002-5ae2d2d9dbc3)   |

## What areas of the site does it impact?

Affects all pages where fieldAdministration is Lovell TRICARE entity Id 1039. Changes the top task link from Make an appointment to MHS Genesis Patient Portal

## Acceptance criteria

- [x] On the Lovell Tricare page, the "Make an appointment" top task link on the following pages links to the [MHS GENESIS Patient Portal](https://my.mhsgenesis.health.mil).
  - [x] [TRICARE Main system page](https://www.va.gov/lovell-federal-health-care-tricare/)
  - [x] [Locations page](https://www.va.gov/lovell-federal-health-care-tricare/locations)
  - [x] [Health services page](https://www.va.gov/lovell-federal-health-care-tricare/health-services/)
  - [x] [Contact us page](https://www.va.gov/lovell-federal-health-care-tricare/contact-us/)
  - [ ] [Programs](https://www.va.gov/lovell-federal-health-care-tricare/programs/)
- [x] For the Lovell Tricare page, the transitioning to Cerner EHR toggle being present in staging is confirmed.

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated (N/A)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-03-06 03:08 UTC, eselkin commented on src/site/stages/build/drupal/graphql/facilities-fragments/healthCareLocalFacility.node.graphql.js
> -      entityBundle
This was duplicated

2024-03-06 16:11 UTC, maxx1128 reviewed
This looks good on the tugboat environment. I have a suggestion for refactoring the code, but it's not a blocker for an approving review.

2024-03-06 16:11 UTC, maxx1128 commented on src/site/filters/liquid.js
> +  liquid.filters.findEhr = (value, fieldRegionPage, fieldOffice) => {
**Suggestion (non-blocking)** it looks like the Tricare check (if `entityID` is 1039) and these two liquid filters are always used together. It may be simpler on the front end if this functionality and logic was all brought together in a single liquid filter. All the needed variables would be passed in, and the code would do the following:

1. Check if it's Tricare. If it's not, it would just return the "Make an Appointment" URL and link text in an object.
2. If it is Tricare, it does everything that `findEhr` and `topTaskLovell` do to return the appropriate link text and URL in the same type of data object as the first step.

This way, the template would call this filter once and put the resulting data in a link element. It would look cleaner, and all the logic for it would be in one place.

2024-03-06 21:54 UTC, eselkin commented on src/site/filters/liquid.js
> +  liquid.filters.findEhr = (value, fieldRegionPage, fieldOffice) => {
One filter is now used.

2024-03-07 01:20 UTC, maxx1128 requested changes
One more simplification and it'll look ready to me.

Also, 👏 for the commit cleanup!

2024-03-07 01:20 UTC, maxx1128 commented on src/site/filters/liquid.js
> +    } else if (linkType === 'make-an-appointment') {
**Todo:** This conditional returns the exact same object as the fallback so it can be removed.

2024-03-07 01:22 UTC, eselkin commented on src/site/filters/liquid.js
> +    } else if (linkType === 'make-an-appointment') {
I want to leave it in so we have the option to expand it when we have links to things like pharmacy for the Lovell TRICARE, that's why there's an else if rather than an else.

2024-03-07 01:22 UTC, eselkin commented on src/site/filters/liquid.js
> +    } else if (linkType === 'make-an-appointment') {
I guess I could take it out for now, but at some point we'll have to put back in the else ifs.

2024-03-07 01:25 UTC, maxx1128 commented on src/site/filters/liquid.js
> +    } else if (linkType === 'make-an-appointment') {
If it needs to be there for a confirmed change in the future, then I'm good with leaving it there. But I would include a comment there with the reason in case someone else (or one of us in the future) reads that code again and has the same thought to remove it.

2024-03-07 01:40 UTC, eselkin commented on src/site/filters/liquid.js
> +    } else if (linkType === 'make-an-appointment') {
Added comment

2024-03-07 01:40 UTC, maxx1128 approved these changes

2024-03-07 02:48 UTC, merged