430 - Remove undesirable heading element
department-of-veterans-affairs/content-build pull request #1948
Opened 2024-03-06 21:49 UTC by nicksayre

## Summary

Removes an undesired heading element. Affected text should instead match as regular body copy.

I work for the IIR Team. We are the owners of Resources For Schools.

## Related issue(s)

Related to [vagov-content PR #925](https://github.com/department-of-veterans-affairs/vagov-content/pull/925).

## Testing done

This static site does not have testing.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

Before (Links are wrapped in H4s):
<img width="334" alt="Screenshot 2024-03-06 at 3 44 20 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/1807967/780e99cf-7edf-4707-9880-f5d5eb309eb8">
After (Links match regular body copy style):
<img width="331" alt="Screenshot 2024-03-06 at 3 43 44 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/1807967/9a2ca709-672c-4ead-abc3-a1c344c703da">

## What areas of the site does it impact?

Only effects Resources For Schools ([https://www.va.gov/school-administrators/](https://www.va.gov/school-administrators/)).

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ x ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ x ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

2024-03-06 23:34 UTC, khenson-oddball approved these changes

2024-03-07 01:14 UTC, maxx1128 requested changes
Two small additional changes and it looks good to me.

2024-03-07 01:14 UTC, maxx1128 commented on src/site/components/merger-social-sco.html
>                    {% if navPath == 'Ask questions' %}
**Todo:** This conditional was only there for the heading element being removed, so it should be removed too.

2024-03-07 01:14 UTC, maxx1128 commented on src/site/components/merger-social-sco.html
>                    {% if navPath == 'Ask questions' %}
**Todo:** This conditional should be removed here too.

2024-03-07 13:52 UTC, Andrew565 commented
PR has requested changes, opting not to review at this time. - Tier 2/FE CoP

2024-03-07 15:40 UTC, nicksayre commented on src/site/components/merger-social-sco.html
>                    {% if navPath == 'Ask questions' %}
Fixed!

2024-03-07 15:40 UTC, nicksayre commented on src/site/components/merger-social-sco.html
>                    {% if navPath == 'Ask questions' %}
Fixed this one too.

2024-03-07 15:56 UTC, Andrew565 approved these changes

2024-03-07 16:27 UTC, maxx1128 approved these changes

2024-03-07 21:51 UTC, merged