Vet Center v3 components added, built, updated
department-of-veterans-affairs/content-build pull request #1954
Opened 2024-03-11 21:54 UTC by eselkin

## Summary

- Adds va-links where possible (not possible in contents of accordions for the most part because those are controlled by CMS editors - we have to inform them to create links in text bodies with the `<va-link href="" text="">` component). Updated to v3 accordions and items. Updated nested content paragraph items to use v3 (like alerts in accordions). Replaced vets-website operating status with generalized facility liquid template with va-alert-expandable (should merge VBA one and this one). Updated all telephone links (when not brought in as an `<a href="tel:...">` tag from drupal) to use va-telephone. Used liquid filter to separate phone numbers and extension when unprocessed phone numbers are received.
- Sitewide Facilities

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16945

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-03-19 00:07 UTC, jilladams commented
@eselkin @maxx1128 is this PR blocked from code review on CI stuff?

2024-03-19 16:07 UTC, maxx1128 requested changes

2024-03-19 16:07 UTC, maxx1128 commented on src/site/includes/operating_status_expandable_alert.liquid
> +      <div>
**Question:** is this extra `div` wrapper needed here? It doesn't look like it has any semantic or styling purpose.

2024-03-19 16:17 UTC, eselkin commented on src/site/layouts/vet_center.drupal.liquid
> +                        </strong><va-telephone contact="{{phoneNumber.phoneNumber}}" extension="{{phoneNumber.extension}}"></va-telephone>
I think they had it as <strong /> before, but equally pointless. Will remove.

2024-03-19 16:19 UTC, eselkin commented on src/site/includes/operating_status_expandable_alert.liquid
> +      <div>
Removed

2024-03-19 16:20 UTC, eselkin commented on src/site/layouts/vet_center.drupal.liquid
> +                        </strong><va-telephone contact="{{phoneNumber.phoneNumber}}" extension="{{phoneNumber.extension}}"></va-telephone>
removed

2024-03-19 17:01 UTC, eselkin commented on src/site/includes/vet_centers/address_phone_image.liquid
> +            </strong><va-telephone contact="{{mainPhone.phoneNumber}}" extension="{{mainPhone.extension}}"></va-telephone>
changed

2024-03-19 19:48 UTC, maxx1128 approved these changes
👍

2024-03-19 20:54 UTC, chriskim2311 approved these changes
LGTM!

2024-03-20 13:39 UTC, laflannery commented
@eselkin I took a look at this and found a couple things:
- The expandable alert is not showing up on the main vet center page. [Harlem Vet center](http://9e11b355dbb7bbb39750e86ce0cd6b12.review.vetsgov-internal/harlem-vet-center/) is closed and has the proper status set. When you first go to the page you see the alert for about 1 or 2 seconds and then it disappears.
  - The alerts are working correctly in [the Nearby locations section](http://9e11b355dbb7bbb39750e86ce0cd6b12.review.vetsgov-internal/harlem-vet-center/locations/) though
- However, in the nearby locations section, the Titles of the facilities no longer link. Can we relink these names using the `<va-link>` component? PR on the left, Prod on the right:
![image](https://github.com/department-of-veterans-affairs/content-build/assets/106678594/46f928bb-c290-43fc-8daf-1a43d66d1b61)

I also have one question - there are no vet centers with exts in their phone number so I just want to make sure. Will all phone numbers within the components all still display properly if an ext is added in the future?

2024-03-20 19:51 UTC, laflannery commented
@eselkin Alerts look good now, thanks!

2024-03-22 15:21 UTC, jamigibbs approved these changes

2024-03-22 15:30 UTC, merged