VACMS 17299 Lovell TRICARE MHS Genesis portal link and VA Make an appointment link testing
department-of-veterans-affairs/content-build pull request #1967
Opened 2024-03-16 03:27 UTC by eselkin

## Summary

- Adds testing now that EHR system is cerner on all platforms. Tests that MHS Genesis link is present on all necessary pages and Make an appointment link on VA pages. Tests that a user shouldn't be able to travel from VA Make an appointment page to TRICARE counterpart.
- Sitewide Facilities

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17107

## Testing done

- Added cypress E2E testing for Lovell pages/links on TRICARE and VA

## Screenshots

No visual changes. Just testing.

## What areas of the site does it impact?

Does not impact the site.

## Acceptance criteria

- [x] Testing for Lovell TRICARE MHS Genesis links working for all Lovell TRICARE pages.
- [x] Testing for absence of Experience switcher on Lovell VA Make an appointment page

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated (N/A)
- [x] Screenshot of the developed feature is added (N/A)
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed (N/A)

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user (N/A)

## Requested Feedback

Check that tests pass in CI

2024-03-19 15:42 UTC, maxx1128 requested changes
One small test to remove then it's good.

2024-03-19 15:42 UTC, maxx1128 commented on src/site/tests/cypress/vacms-lovell.cypress.spec.js
> +  it('TRICARE Health services has MHS Genesis portal link', () => {
**Todo:** This is a duplicate of the above test and should be deleted.

2024-03-19 15:47 UTC, eselkin commented on src/site/tests/cypress/vacms-lovell.cypress.spec.js
> +  it('TRICARE Health services has MHS Genesis portal link', () => {
Yep. Will do.

2024-03-19 15:48 UTC, eselkin commented on src/site/tests/cypress/vacms-lovell.cypress.spec.js
> +  it('TRICARE Health services has MHS Genesis portal link', () => {
Removed.

2024-03-19 19:47 UTC, maxx1128 approved these changes

2024-03-20 17:01 UTC, jamigibbs approved these changes

2024-03-21 23:55 UTC, merged