VACMS-17473 Vet Center Spotlights should use URL.path if available or URI if not
department-of-veterans-affairs/content-build pull request #1968
Opened 2024-03-16 05:42 UTC by eselkin

## Summary

- Internal references in links have a URL path but other links do not. If a URL path exists that should be the link used. If not, defer to the URI (most often it is the link URL). There may be edge cases where a URL path doesn't exist but I could not find them.
- Sitewide Facilities

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17473

## Testing done

- Tested on local and tugboat
- Checked the links for spotlights on: http://localhost:3002/hilo-vet-center/
- CTAs appear as normal when still a URI and appear with URL path for node's location

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-03-26 14:44 UTC, maxx1128 reviewed
One small tweak, otherwise this looks good.

2024-03-26 19:52 UTC, eselkin commented on src/site/includes/vba_facilities/spotlight_content.liquid
> +        {% if entity.fieldCta.entity.fieldButtonLink.url.path %}
updated if

2024-03-27 13:10 UTC, laflannery commented
@eselkin Is there a new link available for me to review this? The one in the testing steps above is not loading

2024-03-28 04:37 UTC, eselkin commented
@laflannery the review-instance changed: http://d14d5336cf01fbca2683256477352442.review.vetsgov-internal/hilo-vet-center

2024-03-28 12:48 UTC, laflannery commented
Looks good @eselkin, Thanks!

2024-03-29 17:14 UTC, maxx1128 requested changes

2024-03-29 17:14 UTC, maxx1128 commented on src/site/includes/vet_centers/featured_content.liquid
>          {%endif%}
**Nitpick (non-blocking):** Spaces needed `endif`.

2024-03-29 17:14 UTC, maxx1128 commented on src/site/includes/vet_centers/featured_content.liquid
> +        {% assign fieldButtonUrl = entity.fieldCta.entity.fieldButtonLink.url.path | hasCharacterOtherThanSpace %}
**Praise:** good use of this liquid filter.

2024-03-29 17:14 UTC, maxx1128 commented on src/site/includes/vba_facilities/spotlight_content.liquid
> +            <p>
**Suggestion:** I think this `div` and `p` tag could be combined to `<p class="vads-u-padding-top--1">`

2024-03-30 07:20 UTC, eselkin commented on src/site/includes/vet_centers/featured_content.liquid
>          {%endif%}
spaced

2024-03-30 07:21 UTC, eselkin commented on src/site/includes/vba_facilities/spotlight_content.liquid
> +            <p>
changed.

2024-04-11 23:39 UTC, maxx1128 approved these changes

2024-04-11 23:49 UTC, merged