Vacms 16148 update phone numbers
department-of-veterans-affairs/content-build pull request #2049
Opened 2024-04-30 19:37 UTC by eselkin

## Summary

- Changes `<a>` telephone links to `<va-telephone>` components. Updates filters for parsing phone numbers. Updates phone templates as well. Updates VAMC, Vet Center, and pre-release VBA pages
- Sitewide Facilities

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16148

## Testing done

- Manually checked that `<va-telephone>` appear and have correct aria-describedby when appropriate
- Automated testing is handled more in the vets-website PR
- Added tests for content-build filter with fallback from `<va-telephone>` to `<a href="tel:+1">`.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

<details>
<summary>
VAMC system page
</summary>
<img src="https://github.com/department-of-veterans-affairs/content-build/assets/5606931/3d745aa2-6c35-460b-b86d-3334e10b9fbe"/>
</details>

<details>
<summary>
VAMC Locations Listing Page ("Other Nearby Locations" is in a PR to vets-website)
</summary>
<img src="https://github.com/department-of-veterans-affairs/content-build/assets/5606931/f0598af4-0240-41a3-931f-63719faf1f70"/>
</details>

<details>
<summary>
VAMC Billing and Insurance
</summary>
<img src="https://github.com/department-of-veterans-affairs/content-build/assets/5606931/2d357f1f-7db8-474a-8207-0f3e1bf89e35"/>
</details>

<details>
<summary>
VAMC Facilities
</summary>
<img src="https://github.com/department-of-veterans-affairs/content-build/assets/5606931/a19271f4-8011-4ed0-bba3-c9cb309bbc6c" />
</details>

<details>
<summary>
</summary>
</details>

<details>
<summary>
</summary>
</details>

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-04-30 20:05 UTC, eselkin commented
The code is ready for review, but the Tugboat's still a couple of hours off due to multiple release requests.

2024-05-02 14:52 UTC, maxx1128 requested changes
This is looking good overall, just a couple small adjustments.

2024-05-02 14:52 UTC, maxx1128 commented on src/site/components/phone.drupal.liquid
> +          tty = false
**Question (non-blocking):** Do these values need to be passed in as `false`? Going by the liquid component setup, they'll default to `false` if nothing is passed in.

2024-05-02 14:52 UTC, maxx1128 commented on src/site/filters/liquid.js
> +  ) => {
**Suggestion:** It looks like the instances of this that are used have no `attributes,` but some do have `describedBy.` The code would be cleaner to make `describedBy` the second argument and `attributes` the third. That way `describedBy` could just be passed in as needed, and `attributes` wouldn't need to be passed in as an empty string in any usage.

2024-05-03 00:32 UTC, eselkin commented on src/site/paragraphs/staff_profile.drupal.liquid
> +          <b>Phone:</b> {{ bio.fieldPhoneNumber | processPhoneToVaTelephoneOrFallback :  '', '' }}
Literally no idea. Strong is more modern, maybe someone had a lapse of like 10 years.

2024-05-03 00:33 UTC, eselkin commented on src/site/filters/liquid.js
> +  ) => {
There are a couple with attributes

2024-05-03 00:34 UTC, eselkin commented on src/site/components/phone.drupal.liquid
> +          tty = false
I expected that, but for some reason it triggered something when they weren't passed in.

2024-05-03 00:34 UTC, eselkin commented on src/site/components/phone.drupal.liquid
> +          tty = false
I can try again, but it was odd.

2024-05-03 00:34 UTC, eselkin commented on src/site/paragraphs/staff_profile.drupal.liquid
> +          <b>Phone:</b> {{ bio.fieldPhoneNumber | processPhoneToVaTelephoneOrFallback :  '', '' }}
I'll change to strong

2024-05-03 00:35 UTC, eselkin commented on src/site/paragraphs/staff_profile.drupal.liquid
> +          <b>Phone:</b> {{ bio.fieldPhoneNumber | processPhoneToVaTelephoneOrFallback :  '', '' }}
Changed

2024-05-03 00:35 UTC, eselkin commented on src/site/components/phone-number.drupal.liquid
> +      {% if !fax %}message-aria-describedby="{{ phoneLabel | default: 'Phone' }}"{% endif  %}
Changed

2024-05-03 00:36 UTC, eselkin commented on src/site/filters/liquid.js
> +  ) => {
But definitely more do have describedBy

2024-05-03 00:39 UTC, eselkin commented on src/site/filters/liquid.js
> +  ) => {
I guess there's only one that uses attributes now, but it doesn't use describedBy, which makes it equally challenging... But if you don't pass arguments to liquid filters it takes the object of the page as an additional argument which is always present and then you wind up with object values in the contents of filter output.

2024-05-03 03:57 UTC, maxx1128 commented on src/site/filters/liquid.js
> +  ) => {
If the page object gets passed in and complicates things, then it's probably best to leave them as-is.

2024-05-03 13:24 UTC, laflannery approved these changes
Reviewed and confirmed all use cases, everything looks good! [Link to QA mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714566731945/d4e3c5cc3f2b5f19115c9494791c19174de0a80c?sender=u10a597890f85398daa3c4805) for reference

2024-05-03 23:22 UTC, eselkin commented on src/site/components/phone.drupal.liquid
> +          tty = false
I removed redundant `= false` assignments. It should be good. Just testing to make sure

2024-05-06 12:20 UTC, maxx1128 approved these changes

2024-05-06 12:51 UTC, pjhill approved these changes

2024-05-06 18:35 UTC, randimays approved these changes
LGTM, nice work!

2024-05-06 19:05 UTC, jtmst approved these changes

2024-05-07 16:37 UTC, merged