VACMS-17816 Benefit Hub landing page icon updates
department-of-veterans-affairs/content-build pull request #2077
Opened 2024-05-09 18:22 UTC by randimays

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-05-13 21:44 UTC, laflannery commented
@randimays I only looked at a couple landing pages so far but my 1 question is that there is a Youtube va-link option. Should we use that in the social nav options? I don't think it should be an issue from an a11y standpoint - because all the icons would be hidden anyway so I wouldn't be concerned about consistency - but from a tech standpoint, would there be an issue for having 1 link done differently than all the others?

2024-05-13 23:48 UTC, maxx1128 requested changes
The code looks good! I think there's one potential refactor to make it more DRY, otherwise it's 👍

2024-05-13 23:48 UTC, maxx1128 commented on src/site/layouts/landing_page.drupal.liquid
>                          <li>
**Suggestion:** There seems to be a lot of repeated code in these conditionals. Could the conditional just control some variable assignments, and then those variables could be put into the same front-end markup?

2024-05-14 22:06 UTC, randimays commented on src/site/layouts/landing_page.drupal.liquid
>                          <li>
I considered this (and tried a refactor just now). It actually made the code more complex / heavier cognitive load than to just have some repetition. Especially given that we have to do special handling for X / Twitter as well (smirk).

2024-05-14 22:11 UTC, randimays commented
@laflannery I made the update to use the YouTube `va-link`. Apologies I missed this before! The icon that comes with the video `va-link` is smaller than the others, though. I tried the "default" icon size for the others (same as font size) and they are too small and difficult to align properly with long link titles when they wrap to 2 lines. I updated the screenshots in the description.

2024-05-15 15:13 UTC, laflannery commented
Ok @randimays one more try, which I apologize for. There is an a11y defect with the Channel variant of the link component, explain in [the slack post here](https://dsva.slack.com/archives/C06NMUK12LR/p1715778493700259) so for that reason, can we go back to the way you had this before and build this like all the others - using separate `<va-icon>` and `<va-link>` components?

2024-05-15 18:18 UTC, randimays commented
@jtmst @laflannery @thejordanwood @aklausmeier This is ready for review, please.

2024-05-15 19:04 UTC, laflannery commented
One very minor update - Can we capitalize the T in "YouTube" as it currently is on Prod?

2024-05-15 22:11 UTC, thejordanwood commented
This looks good to me!

2024-05-15 22:11 UTC, thejordanwood approved these changes

2024-05-16 12:29 UTC, laflannery approved these changes
Looks good!

2024-05-16 14:50 UTC, jtmst approved these changes
looks great 🚀

2024-05-16 16:08 UTC, maxx1128 approved these changes

2024-05-16 17:29 UTC, ataker approved these changes

2024-05-16 18:12 UTC, eselkin approved these changes
LGTM

2024-05-16 19:06 UTC, merged