New va-breadcrumbs support
department-of-veterans-affairs/content-build pull request #2095
Opened 2024-05-21 18:11 UTC by Andrew565

## Summary

- Replacing 'imposter' breadcrumbs component with va-breadcrumbs
- Moving breadcrumbs rendering logic out of the template and into a filter
- This will allow for use of the V3 va-breadcrumbs component in the liquid templates which need breadcrumbs
- I work for the Design System Team

## Related issue(s)

- Closes [#2741](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2741)

## Testing done

- Before, the liquid template handled creation and rendering of breadcrumbs, using CSS classes to get the desired look and feel. Now, the rendering of breadcrumbs is handled by the va-breadcrumbs component.
- Go to va.gov/resources, notice that the breadcrumbs at the top of the page are created and rendered using plain HTML and CSS classes. Load up the code in this PR and go to /resources and notice that breadcrumbs are now handled by the va-breadcrumbs component.
- Tested locally.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Desktop | ![Screenshot 2024-05-21 at 2 08 49 PM](https://github.com/department-of-veterans-affairs/content-build/assets/147893/a51258b2-5493-4b1e-8659-017f5ef23e1e) | ![Screenshot 2024-05-21 at 2 08 23 PM](https://github.com/department-of-veterans-affairs/content-build/assets/147893/26bdc533-6277-4f04-b977-b8df8424a9bb) |

## What areas of the site does it impact?

Affects all pages that utilize breadcrumbs (a majority of static-content pages).

## Acceptance criteria

### Quality Assurance & Testing

- [X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [X] Linting warnings have been addressed
- [X] Documentation has been updated ([link to documentation](#) \*if necessary)
- [X] Screenshot of the developed feature is added
- [X] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [X] Browser console contains no warnings or errors.
- [X] Events are being sent to the appropriate logging solution
- [X] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [X] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [X] The header does not contain any web-components
- [X] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [X] I reached out in the `#sitewide-public-websites` Slack channel for questions

2024-05-21 19:00 UTC, jilladams commented
Just FYI: We'd very much like to verify our breadcrumbs, and our FE team on Facilities / Public Websites have some COVID / PTO / critical deadlines happening, so it may take us a minute to get to this review. Would be lovely if you can hold on merging until at least one of Sitewide's FE code review groups gets a chance to approve.

2024-05-21 20:16 UTC, randimays commented
I haven't had a chance to review these changes against our products but I will set aside some time tomorrow or Monday to do this.

Meanwhile I had a question: how are we planning to handle the breadcrumbs created by `breadcrumbs.html`? Any application in the `registry.json` file that has `"includeBreadcrumbs": true` uses this file. Is this work covered in a separate ticket?

2024-05-22 01:59 UTC, maxx1128 commented on src/site/filters/liquid.js
> +  liquid.filters.formatForBreadcrumbs = (
**Suggestion:** This filter should probably have a few basic tests. They should cover the basic formatting, remove duplicates or empty items, and add the current page to the breadcrumbs.

2024-05-22 01:59 UTC, maxx1128 commented on src/site/includes/breadcrumbs.drupal.liquid
> +      bcComponent.setAttribute('breadcrumb-list', {{ crumbs }});
**Question:** Does the component still render properly with the updated data this way? Or does it not kick in since the attribute is being updated in the script after the web component is referenced?

2024-05-22 12:45 UTC, Andrew565 commented on src/site/includes/breadcrumbs.drupal.liquid
> +      bcComponent.setAttribute('breadcrumb-list', {{ crumbs }});
Yes, the component still renders properly with the data being updated in this way.

2024-05-22 13:36 UTC, Andrew565 commented
> Meanwhile I had a question: how are we planning to handle the breadcrumbs created by [breadcrumbs.html](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/breadcrumbs.html)? Any application in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) file that has `"includeBreadcrumbs": true` uses this file. Is this work covered in a separate ticket?

I think this will have to be a separate ticket, due to the more complex nature of how that file is generated (with crumbs having child objects, etc. the `formatForBreadcrumbs` filter I created won't be a drop-in replacement).

2024-05-22 14:55 UTC, randimays commented
> I think this will have to be a separate ticket, due to the more complex nature of how that file is generated (with crumbs having child objects, etc. the formatForBreadcrumbs filter I created won't be a drop-in replacement).

Thanks @Andrew565. Is that work that the DST will take on, or another team? Just want to make sure we have that work captured somewhere.

2024-05-22 16:03 UTC, maxx1128 approved these changes

2024-05-22 16:04 UTC, Andrew565 commented
@randimays That would be work normally done by sitewide. CC. @jilladams

2024-05-22 20:29 UTC, randimays commented
I reviewed our Sitewide pages. I have some observations and tucked the screenshots in an accordion to keep this easier to read. CC @jilladams @laflannery if you have thoughts about 3, 4 or 6; please chime in.

<details><summary>1. I clicked on VA.gov home in the breadcrumb and it doesn't do anything. Clicking on Resources went to /resources/#content as expected</summary>
<img width="600" alt="Screenshot 2024-05-22 at 2 04 14 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/263207a8-3ffd-4964-a725-1806f13852ac">
</details>

<details><summary>
2. Similarly, if the breadcrumbs have more than 2 items, nothing but the link at the end (in this screenshot "Health services") is working as expected when clicked.</summary>
<img width="857" alt="Screenshot 2024-05-22 at 2 41 52 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/bfbf3ed3-19e7-4e14-88ee-4a0f93dfff26">
</details>


</details>

<details><summary>3. On some of our Facilities pages when the breadcrumbs get lengthy, they are truncated and do not wrap to the next line as they do in production.</summary>

### Review instance
<img width="609" alt="Screenshot 2024-05-22 at 1 58 10 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/2a8aa320-3947-434a-8fa5-a53861b97a46">

### Production
<img width="497" alt="Screenshot 2024-05-22 at 2 03 44 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/531c77dd-48c0-4847-bc17-ced57f33f9a4">

</details>

<details><summary>4. On some pages, our original breadcrumb text has been replaced with the h1. We might need to run these by CAIA if we haven't already. Not sure.</summary>

### Review instance
<img width="701" alt="Screenshot 2024-05-22 at 2 00 02 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/edfaa4e3-5e81-4523-bf94-fc1e1b67a09e">

### Production
<img width="689" alt="Screenshot 2024-05-22 at 1 59 57 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/fd233b29-4ab1-42fa-88e4-f401837dbb7a">

 </details>

<details><summary>5. On /resources/decision-reviews-and-appeals/, the breadcrumb is duplicated.</summary>
<img width="969" alt="Screenshot 2024-05-22 at 2 55 18 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/052336a0-5551-4521-a44c-e2c0fcc1d847">


</details>

<details><summary>6. On /tuscaloosa-health-care/operating-status/, the breadcrumbs are mismatched. I think we may want what is in production now to show here?</summary>

### Review instance
<img width="961" alt="Screenshot 2024-05-22 at 2 57 15 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/2e89a4c5-a315-4297-b467-9837a6144b8e">

### Production
<img width="992" alt="Screenshot 2024-05-22 at 2 57 20 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/64ab2bdd-1524-4848-a892-5c44e83e5cdb">
</details>


<details><summary>Templates I verified</summary>

- /resources
- /resources/search/?query=benefits
- /hampton-health-care/events
- /columbia-south-carolina-health-care/events/66939/
- /south-texas-health-care/locations/audie-l-murphy-memorial-veterans-hospital/
- /loma-linda-health-care/work-with-us/internships-and-fellowships/pharmacy-residency/
- /service-member-benefits/
- /south-texas-health-care
- /southeast-louisiana-health-care/about-us/leadership/
- /west-palm-beach-health-care/locations/
- /west-palm-beach-health-care/stories/the-standard-for-247365-virtual-urgent-care/
- /outreach-and-events
- /find-forms
- /southeast-louisiana-health-care/staff-profiles/mark-morgan/
- /kansas-city-health-care/news-releases/pact-act-awareness-event-at-honor-va-clinic-for-all-veterans-on-march-6/
- /kansas-city-health-care/news-releases/
- /outreach-and-events/outreach-materials/
- /resources/what-if-i-dont-have-a-bank-account-but-i-want-to-use-direct-deposit/
- /resources/how-to-get-community-care-referrals-and-schedule-appointments/
- /alexandria-health-care/stories/
- /resources/decision-reviews-and-appeals/
- /resources/reimbursed-va-travel-expenses-and-mileage-rate/
- /find-forms/about-form-10-6001a/
- /loma-linda-health-care/billing-and-insurance
- /west-palm-beach-health-care/medical-records-office
- /puget-sound-health-care/policies
- /puget-sound-health-care/register-for-care/
- /puget-sound-health-care/va-police/
- /bangor-vet-center
- /bangor-vet-center/locations/
- /south-texas-health-care/locations/

</details>

2024-05-22 20:33 UTC, randimays requested changes

2024-05-22 20:33 UTC, randimays commented on src/site/filters/liquid.js
> +// @ts-nocheck
I'm curious why this was added since this isn't a Typescript file?

2024-05-23 13:52 UTC, Andrew565 commented on src/site/filters/liquid.js
> +// @ts-nocheck
Helped alleviate some unnecessary error warnings that were getting picked up by VS Code.

2024-05-23 15:37 UTC, jilladams commented
We had some known issues with breadcrumbs in prod, so IMO these are IA questions. I'll bump it to the CAIA channel for their awareness as well.

2024-05-23 15:42 UTC, jilladams commented
CAIA thread started here: https://dsva.slack.com/archives/C01K37HRUAH/p1716478961236299

2024-05-23 15:46 UTC, laflannery commented
I have a separate accessibility concern:

We have some pages that are in Spanish and when that happens the last crumb is also in spanish - for example [this page[(http://ba63bb846b2fe34d358a43327969a116.review.vetsgov-internal/health-care/how-to-apply-esp/). However, the last crumb no longer has the `lang` designation. This is an issue for accessibility because screen readers are not going to know that they should change the pronunciation here. This is a regression from Prod as we do have the `lang` currently

Other notes:
- In response to @randimays question - I don't have any accessibility concerns (SRs still read the entire crumb when truncated for example) with anything that was pointed out but glad Jill is raising this to CAIA.
- I also reviewed VBA templates and noticed the same issues Randi pointed out (e.g. the Va.gov crumb does not work properly but the current crumb does)

2024-05-23 18:17 UTC, jilladams commented
Audited [known breadcrumb issues](https://github.com/department-of-veterans-affairs/va.gov-cms/issues?q=is%3Aopen+is%3Aissue+label%3ABreadcrumbs) and got some CAIA feedback. I think this is the punchlist of where we are at for Randi's notes: 

- [ ] VA.gov home breadcrumb: Need IA signoff on whether VA.gov home crumb should be present on every page. 
    - For VAMCs: this is a known weird thing. Within VAMCs, the previous expectation has been that "Home" will point to the VAMC System page, not to VA.gov. Mikki has previously expressed a preference to have VA.gov Home on these pages, but it was embattled in ticket / comments on [#13908](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13908), and is a known bigger picture issue being tracked in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13902. (It also affects how we go about resolving https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9439.) My opinion: we need @mnorthuis  / @mmiddaugh to agree on whether this change is ok, and we shouldn't get embroiled / block this PR on special handling for VAMC crumbs, if we can avoid it.
- [ ] Truncation / wrapping: I think we also need IA & A11y signoff (and maybe UX?) on handling here. I am not finding firm guidance.
- [ ] Where VA.gov home appears as root crumb, it should link to VA.gov
- [ ] Linked crumbs should point to the relevant page
- [ ] Final breadcrumbs should use H1 in all cases (will resolve [#16464](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16464)), including on operating status pages
- [ ] No duplicate crumbs

And just noting for Sitewide awareness, these existing tickets are not changed / resolved by the work in this ticket:
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17834 
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12326
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12125

2024-05-23 20:26 UTC, humancompanion-usds commented
> On some of our Facilities pages when the breadcrumbs get lengthy, they are truncated and do not wrap to the next line as they do in production

Wrapping in the v3 component is a prop you can pass if you want that behavior, otherwise truncation is used.

2024-05-23 21:02 UTC, randimays commented
> Wrapping in the v3 component is a prop you can pass if you want that behavior, otherwise truncation is used.

This may be a CAIA / design decision, but it doesn't seem like the best experience to truncate breadcrumbs at all. The purpose is to illustrate each layer to allow a user to "back up" intelligently and provide context. If those things are cut off at smaller screens, are we losing the benefit of the breadcrumbs at all?

2024-05-24 12:36 UTC, Andrew565 commented
Fixed links not working when clicked, wrapping breadcrumbs by default instead of truncating. Working on duplicates now.

2024-05-24 13:11 UTC, Andrew565 commented
Duplicate paths fixed.

@randimays The page at /tuscaloosa-health-care/operating-status/ is passing in "Operating status | VA Tuscaloosa health care" as the title of that page, there's not much I can do to fix that on my end.

2024-05-24 13:15 UTC, Andrew565 commented
@jilladams @randimays I believe I have fixed all of the problems I can fix on my end. The "VA.gov Home" question and the H1's matching the final breadcrumb are not issues I can address. Let me know if there's anything else I can help with.

2024-05-24 13:17 UTC, laflannery commented
@Andrew565 I had added an accessibility issue in [a comment above](https://github.com/department-of-veterans-affairs/content-build/pull/2095#issuecomment-2127464252) - is this something that can be addressed:

> I have a separate accessibility concern:
> We have some pages that are in Spanish and when that happens the last crumb is also in spanish - for example [this page](http://ba63bb846b2fe34d358a43327969a116.review.vetsgov-internal/health-care/how-to-apply-esp/). However, the last crumb no longer has the lang designation. This is an issue for accessibility because screen readers are not going to know that they should change the pronunciation here. This is a regression from Prod as we do have the lang currently

2024-05-28 13:44 UTC, mnorthuis commented
@jilladams The new V3 breadcrumb has the Va.gov home link at the beginning of the crumb as "VA.gov home" to clarify that home vs the health system home.  That was an intentional change to better accommodate the facility pages (as well as other things), so all facility breadcrumbs should now start with "VA.gov home" as the first segment.

2024-05-28 15:59 UTC, jilladams commented
Re: VA.gov home breadcrumb change: Makes sense. We'll want to notify VHA when this change ships, so will be looking out for when this PR merges / deploys.

2024-07-03 17:50 UTC, jilladams commented
Is the last step here that we need a re-review / approval from Randi in light of fixes to her requested changes? Or is there more left to be addressed than that, @Andrew565 ?

2024-07-05 20:36 UTC, Andrew565 commented
@randimays @laflannery Added language support for breadcrumbs, ready for re-review.

2024-07-08 12:32 UTC, laflannery commented
@Andrew565 The Review instance is not working for me to review, I think it might need to be refreshed because it says it was deployed 2 weeks ago. Is it possible to get a new environment up because it is not possible for me to review locally

2024-07-09 14:51 UTC, randimays commented
@Andrew565 you'll need to pull the latest from `main`. The stylesheet error in CI was fixed last week.

2024-07-12 17:38 UTC, Andrew565 commented
@randimays Ready for review

2024-07-12 18:10 UTC, laflannery commented
@Andrew565 This is not implemented in the same way as production and therefore is not fucntioning properly and some important context is lost:
- The `lang` attribute is currently on the span which is incorrect, it needs to be on the `<a>` tag in order to be interpreted and understood correctly
- The `hreflang` attribute is missing. This provides information about the language of the linked document. It's different from `lang` which is information about this particular link itself.

2024-07-12 18:42 UTC, randimays commented
This looks good to me, but I'd like Laura to give the green light from an accessibility perspective before I can approve.

2024-07-16 18:29 UTC, Andrew565 commented
Updated the breadcrumbs component based on feedback from @laflannery. Will update here when that code has been released.

2024-07-16 18:35 UTC, laflannery commented
Thanks for addressing this @Andrew565! Just to clarify, when you say "released" do you mean ready for re-review or is this going to straight to prod?

2024-08-02 16:30 UTC, Andrew565 commented
@laflannery and @randimays this is ready for re-review.

2024-08-02 19:25 UTC, laflannery commented
@Andrew565 All the language stuff looks great, thanks! I reviewed quite a few other templates as well and just have one other question - when the breadcrumbs wrap, is this the proper spacing, it's much tighter then we are used to so I want to confirm:
![image](https://github.com/user-attachments/assets/6d6a4d8d-a94d-49f1-8961-58c1663e06a5)

2024-08-05 15:53 UTC, Andrew565 commented
> @Andrew565 All the language stuff looks great, thanks! I reviewed quite a few other templates as well and just have one other question - when the breadcrumbs wrap, is this the proper spacing, it's much tighter then we are used to so I want to confirm

Looks good to me, yes.

2024-08-05 16:24 UTC, randimays approved these changes
Re-checked all the templates from [this earlier comment](https://github.com/department-of-veterans-affairs/content-build/pull/2095#issuecomment-2125691639). Looks good, thanks @Andrew565!

2024-08-05 17:06 UTC, merged