VACMS-16999 VAMC Detail page web components
department-of-veterans-affairs/content-build pull request #2100
Opened 2024-05-22 21:56 UTC by randimays

## Summary
Use web components on VAMC detail pages where possible.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16999

## Testing done
Tested locally at these routes:
- /boston-health-care/make-an-appointment/
- /boston-health-care/contact-us/
- /boston-health-care/about-us/
- /boston-health-care/work-with-us/
- /minneapolis-health-care/make-an-appointment/
- /minneapolis-health-care/contact-us/
- /minneapolis-health-care/about-us/
- /minneapolis-health-care/work-with-us/

Also tested a page [**via Tugboat**](https://web-v9l0sy4euftr8m5pebq4pxezfbvbxcnz.demo.cms.va.gov/western-colorado-health-care/about-us/important-useful-information/) for the process list web component.

## Screenshots

<details><summary>Additional info inside alert component</summary>

### Desktop
<img width="693" alt="Screenshot 2024-05-22 at 4 53 03 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/c6872c82-cbbb-44f1-a042-70390bc1c8fb">
<img width="706" alt="Screenshot 2024-05-22 at 4 53 08 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/ae3ed636-5239-4142-8cf6-49548ededd1d">

### Mobile
<img width="377" alt="Screenshot 2024-05-22 at 4 53 37 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/62bd75ec-47fb-4986-a18c-43c72550033e">

### DOM
<img width="506" alt="Screenshot 2024-05-22 at 4 53 30 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/2904d634-d93b-4344-b44e-b6d46c4849fe">

</details>

<details><summary>Back to top component</summary>
<img width="629" alt="Screenshot 2024-05-22 at 4 53 45 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/70c734d6-556d-4a0f-9b62-30a3b4fa2234">
<img width="377" alt="Screenshot 2024-05-22 at 4 53 37 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/14cf8763-ee7c-4a70-a2b4-f617f724d94f">

</details>

<details><summary>Downloadable files (on Minneapolis About Us page)</summary>
<img width="757" alt="Screenshot 2024-05-22 at 5 09 57 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/ba8f0b62-0abf-4abe-86e7-046f8c11b3f0">
<img width="422" alt="Screenshot 2024-05-22 at 5 10 30 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/2e6d1595-b19a-45de-a5a5-8efabb96f5b8">

</details>

<details><summary>Process list</summary>

### Desktop
<img width="605" alt="Screenshot 2024-05-28 at 10 46 28 AM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/73b4f006-a5a8-4d92-a1f6-fe8ba9521d22">

### Mobile
<img width="380" alt="Screenshot 2024-05-28 at 10 46 33 AM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/0a81eed3-9fbb-4947-ad97-dfadd2c1e5b4">

### DOM
<img width="450" alt="Screenshot 2024-05-28 at 10 46 24 AM" src="https://github.com/department-of-veterans-affairs/content-build/assets/19175324/17f07b2b-fe8a-43ea-acc2-58549748c783">

</details>

2024-05-28 16:50 UTC, eselkin reviewed
I remember something about @laflannery asking if when we used the download link the `filetype` should be specified. Is it not possible because we don't know it from drupal. Does it infer it from extension?

2024-05-28 17:41 UTC, randimays commented
@eselkin Good callout; I added it here!

2024-05-28 19:08 UTC, randimays commented
@eselkin The review instance is back up and ready for your review. CC @laflannery

2024-05-28 19:23 UTC, eselkin requested changes
minor tweak

2024-05-28 19:25 UTC, eselkin commented on src/site/paragraphs/downloadable_file.drupal.liquid
> +            filetype="{{ fileExt }}"
Also, if you add the filetype="..."
you can remove the part that uses that in the text="...({{ url|fileExt|upcase }}"

2024-05-28 19:50 UTC, randimays commented
@eselkin Laura and I had a discussion about `filetype` in DMs last week. I thought that situation was different from this one but it seems to be the same. When using a `va-link` with `download` and `filetype`, the `filetype` is not read aloud on a screen reader. There is an issue open for this: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2817 @laflannery I see that this issue refers specifically to `channel` and `video` types... should we add `download`?

In short: we can't use the `filetype` because it won't read "(PDF)" until they fix this, so we just have to keep the extension in the `va-link` `text` attribute.

2024-05-28 21:06 UTC, randimays commented
@eselkin @laflannery The review instance here is ready to review when you have a moment, please

2024-05-28 23:23 UTC, eselkin approved these changes

2024-05-29 12:26 UTC, laflannery commented
@randimays 2 comments:
1. I updated the DST ticket to include download, I meant to but thanks for the reminder!
2. The review instance wasn't working so I used the screenshots and the tugboat. The only difference I saw is that for the BTT, your screenshots look good but the tugboat it's way over to the right, so I'm not sure if that's just an odd Tugboat thing or if something accidently got weird:
![Screenshot 2024-05-29 at 8 25 47 AM](https://github.com/department-of-veterans-affairs/content-build/assets/106678594/03c82262-83f8-4a11-8734-be02f8caf7c4)

2024-05-29 13:46 UTC, randimays commented on src/site/paragraphs/downloadable_file.drupal.liquid
> +            filetype="{{ fileExt }}"
I added a comment on the PR about this but realized I should've put it in this thread:

> @eselkin Laura and I had a discussion about filetype in DMs last week. I thought that situation was different from this one but it seems to be the same. When using a va-link with download and filetype, the filetype is not read aloud on a screen reader. There is an issue open for this: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2817
> 
> In short: we can't use the filetype because it won't read "(PDF)" until they fix this, so we just have to keep the extension in the va-link text attribute.

2024-05-29 16:58 UTC, randimays commented
@laflannery Back to top component is fixed. Review instance is ready for your review please!

2024-05-29 17:02 UTC, laflannery approved these changes
LGTM!

2024-05-29 17:26 UTC, ataker approved these changes

2024-05-29 17:30 UTC, merged