VATEAM-87714: Add KISS configuration for Digital Forms
department-of-veterans-affairs/content-build pull request #2213
Opened 2024-07-30 21:21 UTC by derekhouck

## Summary

Creates the `data/cms/digital-forms.json` endpoint to statically generate all published Digital Forms in Drupal.

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#87714

## Testing done

- Created unit tests for the `static-data-files` config, the `digitalForm` query object, its query fragments, and the new post processor.
- Tested the new data file type against a PR CMS environment and successfully pulled down published Digital Forms.

## What areas of the site does it impact?

None at the moment as the Digital Forms frontend is not currently live in the production environment.

## Acceptance criteria

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

Normalization of the Drupal data will come in department-of-veterans-affairs/va.gov-team#88634

2024-08-01 16:33 UTC, Andrew565 approved these changes

2024-08-05 22:49 UTC, ryguyk requested changes
This looks really good! Thanks for the thorough testing. I just made a comment about one typo that we should change. I could do it quickly, but I also added a question for you about one of your tests that I'd love your insight on.

Nice work!

2024-08-05 22:49 UTC, ryguyk commented on src/site/stages/build/drupal/static-data-files/config.js
> +    query: quertyDigitalForm,
**SHOULD CHANGE**

Typo (same as above)

2024-08-05 22:49 UTC, ryguyk commented on src/site/stages/build/drupal/static-data-files/config.js
> +  query: quertyDigitalForm,
**SHOULD CHANGE**

Typo

2024-08-05 22:49 UTC, ryguyk commented on src/site/stages/build/drupal/static-data-files/config.js
> +  query: quertyDigitalForm,
`queryDigitalForm` or `queryDigitalForms` (plural). I think there's argument for using the plural here, but I'm not going to die on that hill.

2024-08-05 22:49 UTC, ryguyk commented on src/site/stages/build/drupal/static-data-files/digitalForm/index.unit.spec.js
> +    });
**CONVERSATION**
This is not a blocker to approval, but I'm interested in the conversation that might come from this.

It feels like this is testing that the _test_ imports `postProcess` and that it is a function, rather than testing anything specific to the application code. I'm curious if you can expound on why you wrote this test.

2024-08-05 22:49 UTC, ryguyk commented on src/site/stages/build/drupal/static-data-files/config.unit.spec.js
> +});
**CONSIDER**

I'm fine with this, though I wonder if we should add the other queries to this test if it's going to be there. I can understand arguments for both paths.

2024-08-06 15:34 UTC, derekhouck commented on src/site/stages/build/drupal/static-data-files/config.js
> +  query: quertyDigitalForm,
Fixed

2024-08-06 15:35 UTC, derekhouck commented on src/site/stages/build/drupal/static-data-files/config.js
> +    query: quertyDigitalForm,
Fixed

2024-08-06 15:39 UTC, derekhouck commented on src/site/stages/build/drupal/static-data-files/digitalForm/index.unit.spec.js
> +    });
It's only purpose is to test that I'm exporting `postProcessDigitalForm` as `postProcess` from the `digitalForm/index.js` file.

2024-08-06 15:40 UTC, derekhouck commented on src/site/stages/build/drupal/static-data-files/config.unit.spec.js
> +});
We can. The other queries were not relevant to the work I was doing in this PR.

2024-08-06 17:52 UTC, ryguyk approved these changes

2024-08-06 19:06 UTC, merged