Stories page is preview-able
department-of-veterans-affairs/content-build pull request #249
Opened 2021-06-11 00:55 UTC by gescobardev

## Description
Issue linked below

## Acceptance criteria
- [ ] Stories page can be view on preview
- [ ] When running a full build, there should be no changes in behavior for stories page

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-06-14 14:09 UTC, mpelzsherman commented on src/site/layouts/story_listing.drupal.liquid
> +              {% if paginator.prev == null %}
We're refercing `paginator` here, but then redefining it on line 34. Is that OK?

2021-06-14 14:27 UTC, mpelzsherman commented on src/site/layouts/story_listing.drupal.liquid
> +              {% if paginator.prev == null %}
I just confirmed that in preview mode, the paginator object is null at until we assign it on line 34.

However - apparently, liquid doesn't throw an error if you access a property of `null`. So the code works, but it's confusing.

It would make the code more explicit/easier to read if we did something like:

```liquid
            {% assign isFirstPage = isPreview or paginator | isFirstPage %}
            
            {% if isFirstPage %}
```

... and add a liquid filter:

```js
  liquid.filters.isFirstPage = paginator => {
    return !paginator || paginator.prev === null;
  };
```

2021-06-14 14:29 UTC, mpelzsherman commented on src/site/layouts/story_listing.drupal.liquid
> +            {% assign paginator = pagingResult.paginator%}
I still think it would be cleaner/less confusing to move the initialization of `paginator` above the first reference.

2021-06-14 14:30 UTC, mpelzsherman commented on src/site/layouts/story_listing.drupal.liquid
>            {% include "src/site/includes/pagination.drupal.liquid" %}
Please try installing this [plugin](https://marketplace.visualstudio.com/items?itemName=sissel.shopify-liquid) and run an auto-format on this file. If possible, please set indentation preferences to 2 spaces.

Thanks!

2021-06-14 14:30 UTC, mpelzsherman requested changes
see comments

2021-06-14 19:44 UTC, gescobardev commented on src/site/layouts/story_listing.drupal.liquid
> +            {% assign paginator = pagingResult.paginator%}
I agree, I will move it.

2021-06-14 19:55 UTC, gescobardev commented on src/site/layouts/story_listing.drupal.liquid
> +              {% if paginator.prev == null %}
@mpelzsherman Just saw this second comment after I pushed the changes I made. 
Would moving the initialization before line 22 suffice?
Similar to what I just recently did.

2021-06-14 19:56 UTC, gescobardev commented on src/site/layouts/story_listing.drupal.liquid
> +              {% if paginator.prev == null %}
I refactored further as well

2021-06-14 20:27 UTC, gescobardev commented on src/site/layouts/story_listing.drupal.liquid
>            {% include "src/site/includes/pagination.drupal.liquid" %}
installed plugin and auto formatted the file. Please let me know if it still looks off.

2021-06-14 21:00 UTC, mpelzsherman commented on .liquidrc
> +}
Hey, cool! I hope these prefs will be useful for others!

2021-06-14 21:05 UTC, mpelzsherman commented on src/site/layouts/story_listing.drupal.liquid
>            {% if paginator.prev == null %}
I was hoping to clarify the code by assigning a new variable, `isFirstPage`. Is there some reason you prefer not to do that?

In general, if someone declines to address a PR comment and just marks the issue "resolved", I like to see a comment from them explaining their rationale.

2021-06-14 21:07 UTC, mpelzsherman commented on src/site/layouts/story_listing.drupal.liquid
> +              {% if paginator.prev == null %}
I'd still prefer to see the isFirstPage variable. If you can do that without adding the filter, that's fine.

2021-06-14 21:09 UTC, mpelzsherman commented on src/site/layouts/story_listing.drupal.liquid
>            {% include "src/site/includes/pagination.drupal.liquid" %}
The formatting looks great! Thanks!

2021-06-14 23:53 UTC, gescobardev commented on src/site/layouts/story_listing.drupal.liquid
> +              {% if paginator.prev == null %}
This makes a lot of sense, I will make that change.

2021-06-14 23:53 UTC, gescobardev commented on .liquidrc
> +}
Hope so too, great idea!

2021-06-14 23:54 UTC, gescobardev commented on src/site/layouts/story_listing.drupal.liquid
>            {% if paginator.prev == null %}
Got it, I have made the requested change.

2021-06-15 05:16 UTC, mpelzsherman approved these changes

2021-06-15 15:38 UTC, U-DON approved these changes

2021-06-15 15:48 UTC, merged