Vamc make news release page previewable 25403
department-of-veterans-affairs/content-build pull request #253
Opened 2021-06-14 20:01 UTC by gescobardev

## Description
Issue is linked below
To preview use - http://localhost:3002/preview?nodeId=2805

## Acceptance criteria
- [ ] All tests pass

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-06-15 16:18 UTC, mpelzsherman commented on src/site/filters/liquid.js
> +  liquid.filters.eventOrPressReleasesDateSorter = (dates, dateKey, reverse) => {
This function could be used to sort anything with dates. How about calling it just `sortByDateKey`?

Also, `dateKey` is now a required field. You might want to use `fieldDatetimeRangeTimezone` as the default.

```suggestion
  liquid.filters.sortByDateKey = (dates, dateKey = 'fieldDatetimeRangeTimezone', reverse = false) => {
```

2021-06-15 16:19 UTC, mpelzsherman commented on src/site/filters/liquid.unit.spec.js
> +const pressReleasesMockData = [
This is kinda big. Move to a fixture file?

2021-06-15 16:53 UTC, mpelzsherman commented on src/site/filters/liquid.unit.spec.js
> +  it('returns an array of upcoming events in date order starting with most recent to least recent', () => {
Probably not a bad idea to leave "and time" in there, or just say "date/time order".

2021-06-15 16:54 UTC, mpelzsherman commented on src/site/filters/liquid.unit.spec.js
> +    ).to.have.deep.members([
Can we reference this array as `pressReleasesMockData` rather than duplicating it here?

2021-06-15 16:55 UTC, mpelzsherman commented on src/site/filters/liquid.unit.spec.js
> +  });
If we make `fieldDatetimeRangeTimezone` the default, can we add a test where we don't provide a `dateKey` param?

2021-06-15 17:02 UTC, mpelzsherman commented on src/site/filters/liquid.js
> +  liquid.filters.eventOrPressReleasesDateSorter = (dates, dateKey, reverse) => {
We should probably make this function accept an object rather than a list of params, so you can pass any combination in any order.

This is generally a good idea once a function starts getting above 2 params, esp. if they aren't all required.

2021-06-15 17:03 UTC, mpelzsherman requested changes
see comments

2021-06-15 17:46 UTC, gescobardev commented on src/site/filters/liquid.js
> +  liquid.filters.eventOrPressReleasesDateSorter = (dates, dateKey, reverse) => {
This is true, I can rename.

2021-06-15 17:50 UTC, gescobardev commented on src/site/filters/liquid.unit.spec.js
> +const pressReleasesMockData = [
Yeah, I thought about that too. Will do

2021-06-15 18:29 UTC, gescobardev commented on src/site/filters/liquid.js
> +  liquid.filters.eventOrPressReleasesDateSorter = (dates, dateKey, reverse) => {
Hmm I'm not so sure about passing `fieldDatetimeRangeTimezone` as a default value. In my opinion, if we set a default value, it should generally always work. In this case, `fieldDatetimeRangeTimezone` will work for events but will not work for sorting press releases. What are your thoughts about it?

2021-06-15 18:46 UTC, gescobardev commented on src/site/filters/liquid.unit.spec.js
> +  it('returns an array of upcoming events in date order starting with most recent to least recent', () => {
True, I will re-add

2021-06-15 20:26 UTC, mpelzsherman commented on src/site/filters/liquid.js
> +  liquid.filters.eventOrPressReleasesDateSorter = (dates, dateKey, reverse) => {
Just because it doesn't always work, doesn't mean we shouldn't have a default. `fieldDatetimeRangeTimezone` appears in many places, including `src/site/includes/date.drupal.liquid`, so it seems like a good default value to me.

2021-06-15 20:49 UTC, gescobardev commented on src/site/filters/liquid.js
> +  liquid.filters.eventOrPressReleasesDateSorter = (dates, dateKey, reverse) => {
Having a default value implies that that argument is optional to pass in - meaning that if I don't pass anything in, it will run as intended every time. I guess the way I am seeing it is, we are only using `sortByDateKey` in 2 places where the key passed in can be either `fieldDatetimeRangeTimezone ` for events or `fieldReleaseDate` for press releases.

I can add the default though 😁, maybe I'm just missing something

2021-06-15 20:56 UTC, gescobardev commented on src/site/filters/liquid.unit.spec.js
> +    ).to.have.deep.members([
This array isn't an exact clone, it represents the correct date order of press releases. 
In testing it out I realized the this doesn't quite check for that order the way I originally thought so i'll fix that. 
But thats initially why I had it like that b/c it is not quite a duplicate.

2021-06-16 03:45 UTC, mpelzsherman commented on src/site/filters/liquid.unit.spec.js
> +    ).to.have.deep.members([
OK, thanks for the explanation. It makes the test a bit verbose but I guess that's OK.

2021-06-16 03:46 UTC, mpelzsherman commented on src/site/filters/liquid.js
> +  liquid.filters.eventOrPressReleasesDateSorter = (dates, dateKey, reverse) => {
> Having a default value implies that that argument is optional to pass in - meaning that if I don't pass anything in, it will run as intended every time.

Not necessarily. Setting a parameter default just gives the parameter a default value, which I think will be the same most of the time. It doesn't guarantee that the function will "run as intended every time".

I anticipate we might use this function in more places over time as we continue to migrate code out of the build.

But this is a minor point. We can always add the default later.

2021-06-16 03:48 UTC, mpelzsherman approved these changes

2021-06-16 13:14 UTC, gescobardev commented on src/site/filters/liquid.unit.spec.js
> +  });
Yes, I can add a test for this use case.

2021-06-16 14:01 UTC, mpelzsherman commented on src/site/filters/liquid.unit.spec.js
> +
Let's remove the commented-out code...

2021-06-16 15:55 UTC, gescobardev commented on src/site/filters/liquid.unit.spec.js
> +
Oops, will remove

2021-06-16 16:22 UTC, gescobardev commented on src/site/filters/liquid.js
> +  liquid.filters.eventOrPressReleasesDateSorter = (dates, dateKey, reverse) => {
thank you for your explanation and thoughts on it, I have added the default value.

2021-06-16 16:24 UTC, merged