Make images optional
department-of-veterans-affairs/content-build pull request #269
Opened 2021-06-17 22:27 UTC by mpelzsherman

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/25599

2021-06-21 14:18 UTC, mpelzsherman commented on script/preview.js
> +        drupalSite,
These changes fix the "Edit this page in the CMS" links so they work in our local environments as well as in production.

2021-06-21 23:11 UTC, brangi approved these changes

2021-06-22 12:06 UTC, timwright12 commented on src/site/components/image.drupal.liquid
> +  {% assign height = "100%" %}
Height and width values are pixel-based and don't take a unit, so `100%` wouldn't be a valid value: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-height

> The intrinsic height of the image, in pixels. Must be an integer without a unit.

2021-06-22 12:07 UTC, timwright12 commented on src/site/components/image.drupal.liquid
> +  {% assign width = "100%" %}
Same deal with the width attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-width

> The intrinsic width of the image in pixels. Must be an integer without a unit.

2021-06-22 12:10 UTC, timwright12 commented on src/site/components/image.drupal.liquid
> +       title="{{ image.title }}"
@1Copenut what are your thoughts about removing this title attribute? I think it atleast needs a conditional so we don't end up with `title=""`

2021-06-22 12:11 UTC, timwright12 requested changes
Needs a check with accessibility and one HTML update

2021-06-22 14:21 UTC, gescobardev commented on src/site/includes/tests/facilityListing.drupal.unit.spec.js
> +    it('does not render image section if alt tag is missing', async () => {
Spelling mistake- I believe you meant to say "does not render image section if url is missing"

2021-06-22 16:14 UTC, 1Copenut commented on src/site/components/image.drupal.liquid
> +       title="{{ image.title }}"
We should stick to the `alt` attribute for verbally describing images. Adding a `title` can create unexpected experiences with screen readers.

2021-06-22 16:16 UTC, 1Copenut requested changes
Please see my comment https://github.com/department-of-veterans-affairs/content-build/pull/269/files/1f14481d2f01dbbd10ff79a2f605a9e807355fa0#r656377111 for requested change.

2021-06-22 16:31 UTC, mpelzsherman commented on src/site/components/image.drupal.liquid
> +       title="{{ image.title }}"
@1Copenut - one argument in favor us using `title` in addition to `alt` is that it creates a tooltip for sighted users.

See this [CodePen](https://codepen.io/mpelzsherman/pen/ZEeNPXy) for an example.

But if you feel the `title` tag screen reader issue outweighs the benefits of the tooltip, that's OK by me!

2021-06-22 16:40 UTC, 1Copenut commented on src/site/components/image.drupal.liquid
> +       title="{{ image.title }}"
Thanks @mpelzsherman for the Codepen link. I do feel the `alt` attribute is the right approach for adding a spoken description of the image, and removing the `title` attribute. The tooltips can't be zoomed in, and haven't been tested for consistency across screen readers and browsers.

If there's text that's important, I'd opt to put it on the page so it can be zoomed and consumed by all users, with a semantic relationship to the image.

2021-06-22 17:05 UTC, mpelzsherman commented on src/site/components/image.drupal.liquid
> +       title="{{ image.title }}"
Sounds good. I mean these image `title` tooltips have been around since the days of `<blink>`, so I don't think they will be particularly missed. 😄

2021-06-23 12:47 UTC, mpelzsherman commented on src/site/components/image.drupal.liquid
> +  {% assign height = "100%" %}
Thanks for pointing that out. Removing!

2021-06-23 16:51 UTC, timwright12 approved these changes

2021-06-23 17:05 UTC, 1Copenut approved these changes
LGTM! I talked with @mpelzsherman about `alt=""` being permissible for decorative images. He's going to add that to the Liquid template.

2021-06-23 17:32 UTC, gescobardev approved these changes

2021-06-23 17:55 UTC, merged