add use-cached-assets flag option for build
department-of-veterans-affairs/content-build pull request #295
Opened 2021-06-25 16:37 UTC by k80bowman

## Description
DRAFT

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-06-29 16:07 UTC, U-DON approved these changes

2021-06-29 17:52 UTC, mpelzsherman commented
It looks like assets are not getting copied to the `.build` folder when the `--use-cached-assets` flag is used.

So the test I’d like to see pass here is:
 

1. start from a clean state (we could use a yarn clean command BTW. I guess for now, just delete the .build and .cache folders)
2. run `yarn build --pull-drupal`
3. Confirm that assets are present in both `.cache` and `.build` folders
4. start the server and hit a static page. Assets should load in the browser.
5. run `yarn build --pull-drupal --use-cached-assets`
6. repeat steps 3 and 4

2021-06-29 18:38 UTC, mpelzsherman commented
I ran the above steps on my local machine, and got a failure at step 6:

After running `yarn build --pull-drupal --use-cached-assets`:
```
❯ find . -name "university-drive-consolidation-building2.jpg"
./.cache/localhost/drupal/downloads/img/2019-02/university-drive-consolidation-building2.jpg
./.cache/localhost/drupal/downloads/img/styles/3_2_medium_thumbnail/public/2019-02/university-drive-consolidation-building2.jpg
```

This needs to be fixed.

2021-06-29 18:41 UTC, mpelzsherman requested changes
Need to fix the bug where running `yarn build `with `--use-cached-assets ` skips moving assets back (?) into the `build `folder.

2021-06-30 13:55 UTC, k80bowman commented
@mpelzsherman the bug should be fixed now. Could you please check and make sure?

2021-06-30 17:56 UTC, mpelzsherman commented
Test passed! 🚀

2021-06-30 18:00 UTC, mpelzsherman approved these changes
Thanks for doing this!

However: If all asset links always pointed to S3, we’d never have to download them or worry about SOCKS, CORS, etc.

So while this PR will help developers in the short term, I really hope we’re moving in that direction.

2021-06-30 19:29 UTC, merged