Wrap phone numbers with parentheses around the area code
department-of-veterans-affairs/content-build pull request #401
Opened 2021-07-27 19:27 UTC by mpelzsherman

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/27501

2021-07-27 19:34 UTC, Rleahy22 approved these changes
LGTM. Only question is if we want to maintain the parentheses in the display. Good to merge though

2021-07-28 13:02 UTC, kelsonic approved these changes

2021-07-28 13:05 UTC, kelsonic commented
Just curious but do we also need to support the TTY: 711 number use case?

2021-07-28 13:06 UTC, gescobardev commented on src/site/filters/liquid.unit.spec.js
> +  it('wraps phone numbers with parentheses around the area code', () => {
Can we add another test where the phone number looks like this - `(123) 456-7890` ?

2021-07-28 13:06 UTC, gescobardev requested changes
Looks great! I just have one comment about testing.

2021-07-28 16:40 UTC, mpelzsherman commented on src/site/filters/liquid.unit.spec.js
> +  it('wraps phone numbers with parentheses around the area code', () => {
Good catch, thanks! Adding.

2021-07-28 19:01 UTC, gescobardev approved these changes

2021-07-28 19:15 UTC, merged