Sort satellite vet centers
department-of-veterans-affairs/content-build pull request #421
Opened 2021-08-03 22:03 UTC by mpelzsherman

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/26691

2021-08-04 02:07 UTC, gescobardev commented on src/site/layouts/vet_center_locations_list.drupal.liquid
> +            {% for entityVetCenter in satteliteVetCenters %}
Should change the variable to `satelliteVetCenters` for consistency.

2021-08-04 03:01 UTC, gescobardev commented
The way that I understood the ticket was that within the Satellite Locations section, there are 3 possible types of locations that can be listed - outstations, CAPs and mobile vet centers

The order in which they are listed should be as follows - outstations & CAPs (both sorted by alpha) should be shown before any mobile vet centers (sorted by alpha).
There should be 2 groupings within Satellite Locations - outstations/CAPs vs mobile centers.
If thats the case, then it looks like we can look at the `entityBundle` to discern between each of them.

2021-08-04 13:46 UTC, mpelzsherman commented
> The way that I understood the ticket was that within the Satellite Locations section, there are 3 possible types of locations that can be listed - outstations, CAPs and mobile vet centers
> 
> The order in which they are listed should be as follows - outstations & CAPs (both sorted by alpha) should be shown before any mobile vet centers (sorted by alpha).
> There should be 2 groupings within Satellite Locations - outstations/CAPs vs mobile centers.
> If thats the case, then it looks like we can look at the `entityBundle` to discern between each of them.

I'm pretty sure that the outstations & CAPs are included in the GraphQL field `fieldNearbyVetCenters`, and the mobile centers are in `fieldNearbyMobileVetCenters`. I will confirm with the CMS team.

2021-08-04 13:58 UTC, mpelzsherman commented
> There should be 2 groupings within Satellite Locations - outstations/CAPs vs mobile centers.
> If thats the case, then it looks like we can look at the `entityBundle` to discern between each of them.

Please disregard my earlier comment. 

You are correct that A/C on the ticket states:

"within the "Satellite Locations" list = outstations and community access points are grouped together and sorted by alpha order followed by Mobile Vet Centers, grouped in alpha order"

I would much rather separate out the mobile vet centers in GraphQL if possible.

It does look like the GraphQL query `fieldOffice.entity.reverseFieldOfficeNode` _might_ include some mobile vet centers. It is unclear whether these might be the same as those returned by `fieldNearbyMobileVetCenters`.

 I will check with the CMS team on this. Thanks for raising the issue!

2021-08-04 14:17 UTC, gescobardev commented
No problem! 
Yepp, separating them out in graphql would be ideal.
You're right it is confusing why that one mobile vet center isn't returned within `fieldNearbyMobileVetCenters`. 
Just thinking out loud, but could there maybe be a difference between "_nearby_ mobile vet centers" and "_satellite_ mobile vet centers"?

2021-08-04 18:51 UTC, mpelzsherman commented
From @kevwalsh in Slack:

> `reverseFieldOfficeNode` is showing the facilities that are “owned” by the parent Vet Center, such as Outstations, or MVCs that they “own”.  `fieldNearbyMobileVetCenters`   is for MVCs that they don’t “own”, but they want to highlight. 

So we need to merge, sort, and dedupe these 2 fields.

2021-08-05 19:25 UTC, mpelzsherman commented
Per @davidconlon we can skip deduping for now.

2021-08-06 13:02 UTC, gescobardev requested changes

2021-08-06 14:43 UTC, mpelzsherman commented on src/site/filters/liquid.js
> +  };
Done! Please re-review.

2021-08-06 15:42 UTC, gescobardev commented on src/site/filters/liquid.unit.spec.js
> +  it('returns all objects matching the given path and value', () => {
I believe this should say - `returns all objects that do not match the given path and value`

2021-08-06 17:01 UTC, gescobardev approved these changes

2021-08-09 13:47 UTC, merged