Hi res
department-of-veterans-affairs/content-build pull request #490
Opened 2021-08-30 21:14 UTC by gescobardev

## Description
resolves issue linked below

I confirmed that when an image is not added by the editor - `fieldMedia: null`

## Testing done
Unit tests added to cover the following use cases when displaying the `Download full bio` link

- if `fieldPhotoAllowHiresDownload = true` and we have an image (`fieldMedia`)
- if `fieldPhotoAllowHiresDownload = true` and we do not have an image (`fieldMedia`)
- if `fieldPhotoAllowHiresDownload = false` and we have an image (`fieldMedia`)
- if `fieldPhotoAllowHiresDownload = false` and we do not have an image (`fieldMedia`)

2021-08-30 21:32 UTC, mpelzsherman commented on src/site/stages/build/drupal/graphql/bioPage.graphql.js
> +          derivative(style: ORIGINAL) {
Is this the same image that will appear in teasers, e.g. https://www.va.gov/pittsburgh-health-care/about-us/leadership/ ? If so that might not be desirable.

2021-08-30 22:12 UTC, mpelzsherman commented on src/site/stages/build/drupal/graphql/bioPage.graphql.js
> +          derivative(style: ORIGINAL) {
I suggest we add a new field here, e.g.

```graphql
originalImage {
      image {
          derivative(style: ORIGINAL) {
            url
            width
            height
          }
        }
      }
```

... and use that in `src/site/layouts/person_profile.drupal.liquid` for the Download full size photo link.

2021-08-31 18:49 UTC, gescobardev commented on src/site/stages/build/drupal/graphql/bioPage.graphql.js
> +          derivative(style: ORIGINAL) {
The changes wont affect `/pittsburgh-health-care/about-us/leadership/`

graphql aliases have now been added.

2021-08-31 21:10 UTC, mpelzsherman commented on src/site/layouts/tests/person_profile/person_profile.unit.spec.js
> +});
Nice job on the tests! But since we changed the code for displaying the thumbnail image, can you please add a test to confirm that the thumbnail URL is being rendered correctly?

2021-08-31 21:28 UTC, gescobardev commented on src/site/layouts/tests/person_profile/person_profile.unit.spec.js
> +});
ahh yes, I can add that 👍

2021-09-01 16:23 UTC, timwright12 requested changes

2021-09-01 16:23 UTC, timwright12 commented on src/site/layouts/person_profile.drupal.liquid
> +                        <i class="va-c-social-icon fas fa-download"></i> <a href="{{ fieldMedia.hiRes.image.derivative.url }}"
```suggestion
                        <i class="va-c-social-icon fas fa-download" aria-hidden="true"></i> <a href="{{ fieldMedia.hiRes.image.derivative.url }}"
```

2021-09-01 16:25 UTC, mpelzsherman approved these changes

2021-09-01 16:32 UTC, gescobardev commented on src/site/layouts/person_profile.drupal.liquid
> +                        <i class="va-c-social-icon fas fa-download"></i> <a href="{{ fieldMedia.hiRes.image.derivative.url }}"
thank you!

2021-09-01 16:36 UTC, timwright12 approved these changes

2021-09-01 21:38 UTC, merged