Github Actions (daily-deploy) -- Enable daily deploy in github action for prod
department-of-veterans-affairs/content-build pull request #498
Opened 2021-08-31 20:12 UTC by oseasmoran73

## Description

This PR addresses [ticket](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/29253)

This PR enables environmental variables for prod.

## Testing done

See [Slack](https://dsva.slack.com/archives/C024DUC9S1K) for more details

2021-11-01 15:45 UTC, oseasmoran73 commented on script/github-actions/check-broken-links.js
> +  const color = shouldFail ? 'danger' : 'warning';
Looks like color has been updated at some point since it is being used in our `CI.yml`

2021-11-01 19:12 UTC, oseasmoran73 commented on .github/workflows/content-release.yml
> +        if: ${{ needs.set-env.outputs.BUILDTYPE == "vagovprod" }}
Only push release created if `prod`

2021-11-04 20:25 UTC, indytechcook commented on .github/workflows/content-release.yml
>          if: ${{ github.event_name == 'workflow_dispatch' && !contains(fromJson('["dev", "staging"]'), github.event.inputs.deploy_environment) }}
```suggestion
        if: ${{ github.event_name == 'workflow_dispatch' && !contains(fromJson('["dev", "staging", "prod"]'), github.event.inputs.deploy_environment) }}
```

2021-11-04 20:31 UTC, indytechcook requested changes
Mostly Looks great.  I just added `prod` to the allowed environments for manual deploy

2021-11-04 20:31 UTC, indytechcook commented on .github/workflows/content-release.yml
> +        run: echo "dev, staging and prod are the only supported environments" && exit 1
```suggestion
        run: echo "dev, staging, and prod are the only supported environments" && exit 1
```

2021-11-04 20:31 UTC, indytechcook commented on .github/workflows/content-release.yml
>          if: ${{ github.event_name == 'workflow_dispatch' && !contains(fromJson('["dev", "staging"]'), github.event.inputs.deploy_environment) }}
```suggestion
        if: ${{ github.event_name == 'workflow_dispatch' && !contains(fromJson('["dev", "staging", "prod"]'), github.event.inputs.deploy_environment) }}
```

2021-11-04 21:32 UTC, indytechcook commented
@oseasmoran73 can we also add an if at the `notify-start:` to only run on prod https://github.com/department-of-veterans-affairs/content-build/pull/498/files#diff-90571dbe8d8f4805db215f91f9d177538a3043d2d07cf1fcd29199bee34cfa79R172.  

`

2021-11-05 14:37 UTC, indytechcook commented
Cross linking the CMS issue which will turn on GHA for the CMS triggered release: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6906

2021-11-05 14:42 UTC, indytechcook commented
Cross linking testing issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6711

2021-11-05 15:25 UTC, indytechcook commented
Documenting a Slack conversation regarding this: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6711#issuecomment-961940533

Neil: 

> do you know if it's possible to limit which steps the cancel is allowed to run in?
> With the builds taking nearly 35 minutes (looking at the history) this feels like a pretty common scenario

Oseas:

> Potentially (leaning more on the side of no). I know we can add concurrency at a jobs.job level, so I am curious if we can override the cancel-in-progress flag it it gets the same group name. Where would we want to add, if it is possible?

Neil: 

> good question.  I'd say after the build step sometime would make the most sense.  Do you think?

Oseas:

> Ooooh! An idea came to mind as a work around! We can add the always() flag. Can try to create small POC if needed/want
> Makes sense. I would probably say in the archive step if we had to pin point to one. That is officially when it is interacting with s3 for the "first time"
> What it sounds like, must always be executed, thats how we do to notify-failures
> Normal flow is if fails, all subsquent one will not trigger, but with always() with combination of if statement, we can enforce

2021-11-05 15:28 UTC, oseasmoran73 commented
> @oseasmoran73 can we also add an if at the `notify-start:` to only run on prod https://github.com/department-of-veterans-affairs/content-build/pull/498/files#diff-90571dbe8d8f4805db215f91f9d177538a3043d2d07cf1fcd29199bee34cfa79R172.
> 
> `

@indytechcook Do we also want to have this for `notify-failure`?

2021-11-05 15:30 UTC, indytechcook commented
> @indytechcook Do we also want to have this for `notify-failure`?

Yeah.  That would be great.  Thanks @oseasmoran73

2021-11-05 18:22 UTC, indytechcook approved these changes
Given testing in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6711 along with extra flow slack testing with @oseasmoran73 , this looks good!

2021-11-08 21:54 UTC, timwright12 approved these changes

2021-11-09 00:13 UTC, merged