29611/accessible modal cypress
department-of-veterans-affairs/content-build pull request #600
Opened 2021-09-24 14:11 UTC by CBonade

## Description
This converts the Accessible Modal test to Cypress to start our journey on deprecating Nightwatch in content-build.

## Testing done
Test passed in all local runs

2021-09-24 14:29 UTC, Rleahy22 approved these changes

2021-09-24 14:29 UTC, Rleahy22 commented on src/platform/site-wide/tests/accessible-modal.cypress.spec.js
> +      .realPress('Enter');
This is nice 😎

2021-09-24 14:29 UTC, Rleahy22 commented on src/platform/testing/e2e/cypress/support/commands/keyboard.js
> +Cypress.Commands.add('repeatKey', (key, multiple) => {
🚀

2021-09-24 14:38 UTC, holdenhinkle approved these changes
Nice - LGTM!

2021-09-24 22:16 UTC, ddzz commented on package.json
> +    "cypress-real-events": "^1.5.1",
This should be moved to `devDependencies`.

2021-09-24 22:18 UTC, ddzz requested changes

2021-09-24 22:18 UTC, ddzz commented on package.json
> +    "cypress-real-events": "^1.5.1",
This should be moved to `devDependencies`.

2021-09-27 13:20 UTC, CBonade commented on package.json
> +    "cypress-real-events": "^1.5.1",
Went ahead and fixed this!

2021-09-27 13:27 UTC, ddzz approved these changes

2021-09-27 16:38 UTC, theodur approved these changes

2021-09-27 17:36 UTC, merged