Github Actions -- Add callback to daily deploy and content-release
department-of-veterans-affairs/content-build pull request #784
Opened 2021-11-24 22:29 UTC by oseasmoran73

## Description

See [Slack](https://dsva.slack.com/archives/C01512KN35G/p1637785399079500) for more details

It was pointed out that the govcallback should be added to daily deploy and content release as it is an integral part. This PR does the following:

- Grab the buildtime and store accordingly
- Grab token from SSM
- Make call to callback using token

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-11-24 22:31 UTC, oseasmoran73 commented on .github/workflows/content-release.yml
> +      vagovprod_buildtime: ${{ env.vagovprod_buildtime }}
saves buildtime for `deploy` step

2021-11-24 22:31 UTC, oseasmoran73 commented on .github/workflows/content-release.yml
> +    needs: [set-env, build, create-release]
add build as dependency to get `vagovprod_buildtime`

2021-11-24 22:31 UTC, oseasmoran73 commented on .github/workflows/content-release.yml
> +        continue-on-error: true
No return `200`. Need this flag

2021-11-24 22:31 UTC, oseasmoran73 commented on .github/workflows/daily-deploy-production.yml
> +      vagovprod_buildtime: ${{ env.vagovprod_buildtime }}
x2

2021-11-24 22:31 UTC, oseasmoran73 commented on .github/workflows/daily-deploy-production.yml
> +    needs: [set-env, build, create-release]
x2

2021-11-24 22:31 UTC, oseasmoran73 commented on .github/workflows/daily-deploy-production.yml
> +        continue-on-error: true
x2

2021-11-24 22:50 UTC, alexandec approved these changes

2021-11-29 15:59 UTC, indytechcook requested changes
I think this will be fine once we move the step to before the build.  Is it possible to test this before we merge?

2021-11-29 15:59 UTC, indytechcook commented on .github/workflows/content-release.yml
> +      - name: Get buildtime
Am I reading this correctly that this uses the a timestamp after the build.  It should use a timestamp before the build like it does in Jenkins: https://github.com/department-of-veterans-affairs/content-build/blob/master/jenkins/common.groovy#L197.  This is important since this timestamp is sent back to Drupal where it will send the emails with links to pages.  If the page was published in Drupal after the GraphQL query and before this step then emails will be sent with links to pages which do not exist.

2021-11-29 16:10 UTC, indytechcook approved these changes

2021-11-29 16:30 UTC, merged