34427 map slice content build
department-of-veterans-affairs/content-build pull request #957
Opened 2022-02-04 21:10 UTC by GcioNapoleon

## Description

This is the content build commit for this ticket.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/34427

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-02-07 20:54 UTC, srsuddath commented on src/site/includes/image_and_static_map_dynamic.liquid
> +</div>
it looks like it wants a newline here

2022-02-07 20:54 UTC, srsuddath commented on src/site/includes/image_and_static_map_satellite_main.liquid
> +</div>
and here

2022-02-07 20:56 UTC, srsuddath commented on src/site/includes/vet_centers/address_phone_image_map.liquid
> +{% endcomment %}
we should not be committing this much commented out code

2022-02-07 20:57 UTC, srsuddath requested changes

2022-02-07 20:57 UTC, srsuddath commented on src/site/includes/vet_centers/address_phone_image_map.liquid
> +{% endcomment %}
we should remove this code block?

2022-02-07 21:09 UTC, GcioNapoleon commented on src/site/includes/image_and_static_map_satellite_main.liquid
> +</div>
done

2022-02-07 21:09 UTC, GcioNapoleon commented on src/site/includes/image_and_static_map_dynamic.liquid
> +</div>
done

2022-02-07 21:14 UTC, srsuddath approved these changes

2022-02-17 16:47 UTC, mdewey approved these changes
LGTM

2022-02-17 20:26 UTC, merged